### ISSUE TITLE
prometheus  selectors not working correctly

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1]
https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#servicemonitor

 There are few selectors for filtering objects:

1) serviceMonitorNamespaceSelector/serviceMonitorSelector - filters service monitor by namespace (if not specified, use vmagent deployed namespace).  
   Atm, filters only for current namespace or namespace selector: 
 
https://github.com/VictoriaMetrics/operator/blob/master/pkg/controller/factory/serviceMonExec.go#L140

 possible solution - filter twice. 

2) podMonitorSelector/ podMonitorNamespaceSelector
https://github.com/VictoriaMetrics/operator/blob/master/pkg/controller/factory/serviceMonExec.go#L201
 The same problem

3)  ruleSelector/ruleNamespaceSelector for vmalert 
 https://github.com/VictoriaMetrics/operator/blob/master/pkg/controller/factory/rulescm.go#L145

 As example,

 You can specify for filter everything:
```yaml
apiVersion: monitoring.victoriametrics.com/v1beta1
kind: VmAgent
metadata:
  name: example-vmagent
spec:
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
```
Current every serviceMon at current namespace
```yaml
apiVersion: monitoring.victoriametrics.com/v1beta1
kind: VmAgent
metadata:
  name: example-vmagent
spec:
  serviceMonitorSelector: {}
```

Some namespaces and every service mon:

```yaml
apiVersion: monitoring.victoriametrics.com/v1beta1
kind: VmAgent
metadata:
  name: example-vmagent
spec:
  serviceMonitorNamespaceSelector: 
       matchLabels:
              name:  dev
  serviceMonitorSelector: {}
```

and etc
