### ISSUE TITLE
possibility to specify nodeSelector for vmagent and vmalert

### ISSUE THREAD

**Issue by VVvKamper** [VictoriaMetrics/operator#104]
Hello. As i understand right now one can't specify the `nodeSelector` for pods of vmagent or vmalert. Could you add such option?

**Comment by valyala** [comment]
Probably [fieldSelector](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/) can be used instead of `nodeSelector` for selecting pods that run on the given nodes. `fieldSelector` can be specified via `selectors` section inside [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config).

**Comment by VVvKamper** [comment]
I meant a possibility to specify node where the own pod of vmagent or vmalert will run.

**Comment by valyala** [comment]
@f41gh7 , could you take a look at this?

**Comment by VVvKamper** [comment]
There is already such option for alertmanager (https://github.com/VictoriaMetrics/operator/blob/master/controllers/factory/alertmanager.go#L526)

**Comment by VVvKamper** [comment]
The motivation for the feature is following - we have instance of the vmagent that gathering metrics from a large amount of server and could use something about 20Gb of memory and multiple cpu cores. We would like it to work as reliable as possible so we want to provide it a dedicated server, so no other process could steel resources from it (and also so the vmagent couldn't interfere with other production workload).

**Comment by f41gh7** [comment]
Hello, nodeSelector is very simple option for pod affinity configuration. We are providing such feature with `affinity` config spec for all components. https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity

 Simple example for binding `vmagent` to nodes with labels `group-name=foo`:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
spec:
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  replicaCount: 1
  serviceAccountName: vmagent
  affinity: 
   nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: group-name
            operator: In
            values:
            - foo
  remoteWrite:
    - url: "http://vmsingle-example-vmsingle-persisted.default.svc:8429/api/v1/write"
```
