### ISSUE TITLE
VMSingle cannot remove extraArgs

### ISSUE THREAD

**Issue by incubator4** [VictoriaMetrics/operator#1043]
I use `victoria-metrics-k8s-stack` helm chart deploy full vm stack. With enable `VMAlert` resource, VMSingle would inject extraArgs just like
```yaml
spec:
  extraArgs:
    vmalert.proxyURL: 'http://vmalert-victoriametrics.<my-namespace>.svc:8080'
```
The error occurs when I disable vmalert for test. VMSingle should remove extraArgs to `{}`, but it (extraArgs) cannot be converted from `object` to `null`

What I did was delete VMSingle and recreate it.
