### ISSUE TITLE
possible clash with configmap and secret references.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1067]
Any object `SecretOrConfigmap` structure https://github.com/VictoriaMetrics/operator/blob/master/api/operator/v1beta1/vmextra_types.go#L758C6-L758C23 may produce incorrect reference at tlsAssets, if there are references to the configmap and secret with the same name and key.

 It should be rare case.

Possible solutions:
1) do remove configmap references
2) add prefix for configmap references

To reproduce:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: with-clash
spec:
  - port: http
    targetPort: http
    path: /metrics
    scheme: http
    tlsConfig:
      ca:
        configmap:
          name: clash
          key: key
      cert:
        secret:
          name: clash
          key: key
  selector:
    matchLabels:
      app.kubernetes.io/name: example-application
      monitored-by: vm-operator
---
apiVersion: v1
kind: Secret
metadata:
 name: clash
stringData:
  key: value-1
---
apiVersion: v1
kind: Configmap
metadata:
 name: clash
data:
  key: value-1
```
