### ISSUE TITLE
config-reloader throttling of CPU in vmagent

### ISSUE THREAD

**Issue by stevenhong127** [VictoriaMetrics/operator#1079]
`Status: FIRING 🔥
Annotations:
- summary: Processes experience elevated CPU throttling.
- description: 33.33% throttling of CPU in namespace monitoring for container config-reloader in pod vmagent-***.
Details:
- container: config-reloader
`

When deploying VMAgent using vm-operator, it is currently not possible to specify the resource limits for the config-reloader, which often leads to CPU throttling alerts for VMAgent. Is there a plan to improve and add support for this in the future?

**Comment by f41gh7** [comment]
Hello,

 It's possible to globally rise limit per CRD object with env variables for operator:
VM_VMALERTDEFAULT_CONFIGRELOADERCPU  100m
VM_VMAGENTDEFAULT_CONFIGRELOADERCPU 100m
VM_VMAUTHDEFAULT_CONFIGRELOADERCPU 100m
VM_VMALERTMANAGER_CONFIGRELOADERCPU 100m
https://docs.victoriametrics.com/operator/vars/


 Or patch value directly per CRD object:


```yaml
kind: VMAgent
spec:
  containers:
  - name: config-reloader
     resources:
       limits:
          cpu: 200m
```
