### ISSUE TITLE
insecureSkipVerify: ignored in 0.47.0 

### ISSUE THREAD

**Issue by passie** [VictoriaMetrics/operator#1080]
Setting the following parameter in the alertmanager configuration is ignore in the latest operator version. 0.47.0

```yaml    
tls_config:
  insecureSkipVerify: true
```
Expexted output: (works in 0.46.4)
```yaml
- name: example-receiver
  email_configs:
  - tls_config:
      insecure_skip_verify: true
    to: info@example.com
    send_resolved: true
```
Got: (with 0.47.0)
```yaml
- name: example-receiver
  email_configs:
  - to: info@example.com
    send_resolved: true
```
