### ISSUE TITLE
Incorrect routes added to alertmanager.yaml

### ISSUE THREAD

**Issue by mattburgess** [VictoriaMetrics/operator#1089]
I'm not entirely sure this is a bug in the operator, or a bug in our config but what we're seeing is somewhat surprising. Here's the relevant bit from our VMAlertManagerConfig:

```yaml
route:
  group_by:
    - cluster
    - namespace
    - alertname
  group_interval: 5m
  group_wait: 30s
  receiver: "slack"
  repeat_interval: 12h
  routes:
    - continue: false
      matchers:
        - alertname = InfoInhibitor
      receiver: "null"
    - continue: false
      matchers:
        - alertname = Watchdog
      receiver: "null"
    - continue: true
      receiver: slack
```

and here's the generated routes in the secret:

```yaml
route:
  receiver: core-metrics-database-core-metrics-slack
  routes:
  - routes:
    - matchers:
      - alertname = InfoInhibitor
      receiver: core-metrics-database-core-metrics-null
      continue: false
    - matchers:
      - alertname = Watchdog
      receiver: core-metrics-database-core-metrics-null
      continue: false
    - receiver: core-metrics-database-core-metrics-slack
      continue: true
    matchers:
    - namespace = "core-metrics-database"
    group_by:
    - cluster
    - namespace
    - alertname
    group_interval: 5m
    group_wait: 30s
    repeat_interval: 12h
    receiver: core-metrics-database-core-metrics-slack
    continue: true
```

What we're expecting to see:

1. `Watchdog` alert goes to the `null` receiver
2. `InfoInhibitor` alert goes to the `null` receiver
3. All other alerts go to the `slack` receiver (regardless of namespace too)

What we see:

1. _All_ alerts go to the `slack` receiver, e.g. we'd expect the alert below to not reach slack.

```sh
amtool config routes --alertmanager.url https://<redacted> test alertname="Watchdog" --tree
Matching routes:
.
└── default-route  receiver: core-metrics-database-core-metrics-slack
```

Questions: What does this section do, and what controls it?

```yaml
matchers:
- namespace = "core-metrics-database
```
