### ISSUE TITLE
Webhooks get context deadline exceeded

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/operator#1094]
Pulling this in from Slack for tracking - After some time I've been unable to reliably resolve this. I am running the VM Operator on 6+ cluster but only getting this frequently on a few clusters, and I could not identify and correlation as to why.

After upgrading to 0.34.7 using the helm chart, I'm getting these errors from server-side apply:
>```Internal error occurred: failed calling webhook "vmagent.victoriametrics.com": failed to call webhook: Post "https://victoria-metrics-operator.monitoring.svc/validate-operator-victoriametrics-com-v1beta1-vmagent?timeout=10s": context deadline exceeded ```

I tried disabling the `vmagent` webhook, and then I started to get the same error with other resources like `vmalert`. There are no errors in the logs that seem directly related.

**Comment by AndrewChubatiuk** [comment]
hey @mbrancato 
what tool are you using for chart deployment?

**Comment by mbrancato** [comment]
@AndrewChubatiuk we are using the [helm-controller](https://github.com/fluxcd/helm-controller) which under the hood uses real `helm`. Its not like ArgoCD which templates charts - I've ran into multiple issues in the past using templating of charts. The helm-controller uses [`HelmRelease`](https://github.com/fluxcd/helm-controller/blob/main/config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml) CRDs to define releases.

```
% helm -n flux-system status victoria-metrics-operator
NAME: victoria-metrics-operator
LAST DEPLOYED: Wed Sep  4 17:30:47 2024
NAMESPACE: monitoring
STATUS: deployed
REVISION: 14
TEST SUITE: None
NOTES:
victoria-metrics-operator has been installed. Check its status by running:
  kubectl --namespace monitoring get pods -l "app.kubernetes.io/instance=victoria-metrics-operator"
```

**Comment by AndrewChubatiuk** [comment]
are you using default values for a chart?

**Comment by mbrancato** [comment]
Here is my whole release definition @AndrewChubatiuk. What is under `spec.values` is basically the `values.yaml`.

I added `admissionWebhooks.enabled: false` yesterday after the upgrade just to stop getting errors from a slack integration during reconciliation attempts.

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: victoria-metrics-operator
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      version: 0.34.7
  interval: 1m0s
  targetNamespace: monitoring
  releaseName: victoria-metrics-operator
  timeout: "600s"

  values:
    image:
      tag: v0.47.3
    crd:
      create: true

    # Disabled webhooks that were added somewhere around 0.34.0 due to context timeouts
    # https://github.com/VictoriaMetrics/operator/issues/1094
    admissionWebhooks:
      enabled: false

    replicaCount: 1

    rbac:
      create: true

    operator:
      disable_prometheus_converter: false
      prometheus_converter_add_argocd_ignore_annotations: false
      enable_converter_ownership: false
      useCustomConfigReloader: false

    serviceAccount:
      create: true

    extraArgs:
      loggerFormat: json
      loggerJSONFields: "ts:timestamp,msg:message,level:severity"

    resources:
      limits:
        cpu: 120m
        memory: 320Mi
      requests:
        cpu: 80m
        memory: 120Mi

```

**Comment by mbrancato** [comment]
And here is reading from helm, same data

```
% helm -n flux-system get values victoria-metrics-operator       
USER-SUPPLIED VALUES:
admissionWebhooks:
  enabled: false
crd:
  create: true
extraArgs:
  loggerFormat: json
  loggerJSONFields: ts:timestamp,msg:message,level:severity
image:
  tag: v0.47.3
operator:
  disable_prometheus_converter: false
  enable_converter_ownership: false
  prometheus_converter_add_argocd_ignore_annotations: false
  useCustomConfigReloader: false
rbac:
  create: true
replicaCount: 1
resources:
  limits:
    cpu: 120m
    memory: 320Mi
  requests:
    cpu: 80m
    memory: 120Mi
serviceAccount:
  create: true
```
