### ISSUE TITLE
Adds discovery mechanism for operator components.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#114]
I suggest to add remoteWrite, remoteRead label selectors, that will simplify installation and managing.

 Abstract example:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
 remoteWriteSelector:
    nameSpaceSelector: {}
    labelSelector: {}
```

 This setting will build proper FQDN url for `VMSingle` and `VMCluster` components. 

 The same for `VMAlert` connections.
