### ISSUE TITLE
Conversion of ScrapeConfig to VMScrapeConfig with scheme field failed

### ISSUE THREAD

**Issue by barthy1** [VictoriaMetrics/operator#1148]
In case if `scheme` value is specified in Prometheus ScrapeConfig format (HTTP or HTTPS), I have error in VM operator during conversion ScrapeConfig into VMScrapeConfig - `VMScrapeConfig.operator.victoriametrics.com \"test\" is invalid: spec.scheme: Unsupported value: \"HTTPS\": supported values: \"http\", \"https\"` 
But HTTP/HTTPS are only valid scheme values for ScrapeConfig. I guess http/https would work for conversion, but it fails validation for ScrapeConfig format.

Sample ScrapeConfig
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: test
spec:
  scheme: HTTPS
  staticConfigs:
    - targets:
        - test.target.com
```
