### ISSUE TITLE
vmsingle cannot remove pvc

### ISSUE THREAD

**Issue by whc9527** [VictoriaMetrics/operator#1159]
`helm upgrade --install vmks vm/victoria-metrics-k8s-stack -f values.yaml -n monitoring`

```
... ...
# Configures vmsingle params
vmsingle:
  # -- VMSingle annotations
  annotations: {}
  # -- Create VMSingle CR
  enabled: true
  # -- Full spec for VMSingle CRD. Allowed values describe [here](https://docs.victoriametrics.com/operator/api#vmsinglespec)
  spec:
    port: "8429"
    # -- Data retention period. Possible units character: h(ours), d(ays), w(eeks), y(ears), if no unit character specified - month. The minimum retention period is 24h. See these [docs](https://docs.victoriametrics.com/single-server-victoriametrics/#retention)
    retentionPeriod: "1h"
    replicaCount: 1
    extraArgs: {}
    nodeSelector: 
      business_type: prometheus
    resources: {}
    storage: {}
    storageDataPath: "/vmdata"
... ...
```

Use the command above to deploy, but vmSingle does not want to use PVC for storage， but not working.

I put the full information in this issue
https://github.com/VictoriaMetrics/helm-charts/issues/1750
