### ISSUE TITLE
support for global discoveryRole configuration and per-serviceMonitor discoveryRole

### ISSUE THREAD

**Issue by ethfoo** [VictoriaMetrics/operator#1162]
We are operating large-scale clusters and using `ServiceMonitor` resources (via Prometheus Operator's CRDs). However, we've encountered metric collection issues due to the inability to configure `discoveryRole` as `endpointslice` in `ServiceMonitor` objects. Specifically, the issue stems from the fact that while VictoriaMetrics-Operator automatically converts `ServiceMonitor` resources into `VMServiceScrape `objects, it does not allow for the configuration of `discoveryRole`, which by default is `endpoint`.
Prometheus-Operator has introduced support for configuring the `discoveryRole` directly on Prometheus and PrometheusAgent CRs (as referenced here: [Prometheus Operator API Reference](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.ServiceDiscoveryRole)), but this feature is currently missing in VictoriaMetrics-Operator.

**Proposed Solution:**
1. **Global discoveryRole Configuration**: Add support for a global configuration in VictoriaMetrics-Operator to allow users to specify the discoveryRole (such as endpointslice) by default across all VMServiceScrape resources.
```yaml
env:
  - name: VM_ENABLEDPROMETHEUSCONVERTER_DISCOVERYROLE
    value: "endpointslices"

```
2. **Per-ServiceMonitor discoveryRole Configuration**: Enable the ability to configure the discoveryRole field individually within ServiceMonitor resources. This would provide finer control over discovery methods at the service level.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    operator.victoriametrics.com/discovery-role: endpointslices
```

This change would improve the flexibility of metric collection in large-scale clusters and allow for the use of endpointslice discovery where required, reducing missing metric data and improving the overall monitoring setup.
