### ISSUE TITLE
Add support for horizontalPodAutoscaler in related Helm charts

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/operator#1164]
While using [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) chart, I'm forced to constantly fine-tune the 3 `vmcluster` component related resources. I see [hpa.go](https://github.com/VictoriaMetrics/operator/blob/master/internal/controller/operator/factory/build/hpa.go) is already present, I think is a matter of simply enabling it into `victoria-metrics-k8s-stack` Helm chart?

For example, `vmstorage` memory usage oscillates between 800Mi-3Gi, forcing me to define a very large resource limit to avoid OOM's. Enabling autoscaling should address the issue, I can set the `vmstorage` resource memory limit to 1Gi and the autoscaling will take care of the rest.

Please see a suggested implementation [example](https://github.com/VictoriaMetrics/helm-charts/issues/1769).

**Comment by f41gh7** [comment]
Hello, it makes no sense to use horizontal auto-scaling with vmstorage. It will only lead to cluster instability and metrics loss. It's the main reason why operator supports HPA only for - `vminsert`, `vmselect` and `vmagent` ( it also should be added to vmauth later). 

 I think VerticalPodAutoscaler could be really useful for vmstorage, when in-place resource resizing will be stable https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/

**Comment by fmunteanu** [comment]
@f41gh7 thank you for the explanation. Is is possible to extend the HPA for vminsert, vmselect and vmagent within [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) chart?

**Comment by f41gh7** [comment]
Sorry for delay, 

 Yes, it's possible to use. Just define under `vmselect` and `vminsert` needed `hpa` configuration.  https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L351

 For example:

```yaml
#values.yaml
    vmselect:
      port: "8481"
      replicaCount: 1
      cacheMountPath: "/select-cache"
      extraArgs: {}
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 2Gi
      hpa:
        minReplicas: 1
        maxReplicas: 2
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 50

      resources:
        {}
        # limits:
        #   cpu: "1"
        #   memory: "1000Mi"
        # requests:
        #   cpu: "0.5"
        #   memory: "500Mi"
    vminsert:
      port: "8480"
      replicaCount: 1
      extraArgs: {}
      hpa:
        minReplicas: 1
        maxReplicas: 3
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 50
```

 API reference https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/
