### ISSUE TITLE
Annotations cannot be removed by operator

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1171]
Currently, operator merges annotations exists at managed objects with annotations defined at `CRDs` definition.

 Consider the following example:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: example
  annotations:
      some-key: value
spec:
  # Add fields here
  retentionPeriod: "1"
```

 Created deployment has annotation:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    some-key: value
```

 Due to labels.Merge logic at `reconcile` package:  https://github.com/VictoriaMetrics/operator/blob/master/internal/controller/operator/factory/reconcile/deploy.go#L51

 Operator will always keep `some-key` annotations.

 Main reason behind that is preserving annotations added by 3rd party components, such as mutation webhooks. 

 Possible solutions:
1) use 3-way merge to properly delete annotations added and managed by operator
2) override all annotations and use `CRD` as source of truth.
