### ISSUE TITLE
[feature request] VMNodeScrape

### ISSUE THREAD

**Issue by ymmt2005** [VictoriaMetrics/operator#118]
It would be great if we can use a custom resource to scrape all the nodes of a Kubernetes cluster.

cf. https://prometheus.io/docs/prometheus/latest/configuration/configuration/#node

**Comment by f41gh7** [comment]
Hello, can you add a bit more context, which fields is needed/wanted. A draft example of custom resources would help a lot.

**Comment by ymmt2005** [comment]
Hi, thank you for maintaining the great product!

In our context, some programs including kubelet and kube-proxy runs on every node as a systemd service.
Since they are not Pods, we need to scrape node ports.  An example would look like:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: example-node-scrape
spec:
  port: 8080
  scheme: http
  selector:
    matchLabels:
     kubernetes.io/os: linux
```

We don't need a list of endpoints.  Single port/scheme per VMNodeScrape is enough.
