### ISSUE TITLE
Missing target label container after adding `discoveryRole: endpointslices` to VMServiceScrape

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/operator#1187]
I have a VMServiceScrape with default discoveryRole for a dcgm-exporter endpoint. Since its size exceed 1K, I change its discoveryRole to endpointslices. I found that the laebl `exported_container` new metric disappeared after upgrade. When I diff the config in vmagent, I found folloowing diff between two versions.

My VMOperator version is v0.42.4.

```yaml
# default discoveryRole
source_labels:
__meta_kubernetes_pod_name
target_label: pod
source_labels:
__meta_kubernetes_pod_container_name
target_label: container
source_labels:
__meta_kubernetes_namespace
target_label: namespace
```

```yaml
# discoveryRole: endpointslices
source_labels:
__meta_kubernetes_pod_name
target_label: pod
source_labels:
__meta_kubernetes_namespace
target_label: namespace
```
