### ISSUE TITLE
certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "vm-operator-ca"

### ISSUE THREAD

**Issue by AurimasNav** [VictoriaMetrics/operator#1213]
Hi,
trying to deploy vm helm chart victoria-metrics-k8s-stack 0.33.2 via kustomize + argocd

A lot of resources are failing to apply with errors similar to this:

Internal error occurred: failed calling webhook "vmagent.victoriametrics.com": failed to call webhook: Post "https://victoria-metrics-k8s-stack-victoria-metrics-operator.victoriametrics.svc:9443/validate-operator-victoriametrics-com-v1beta1-vmagent?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "vm-operator-ca")

log in operator pod:

```shell
{"level":"error","ts":"2025-01-08T10:05:57Z","logger":"manager","msg":"Reconciler error","controller":"vmsingle","controllerGroup":"operator.victoriametrics.com","controllerKind":"VMSingle","VMSingle":{"name":"victoria-metrics-k8s-stack","namespace":"victoriametrics"},"namespace":"victoriametrics","name":"victoria-metrics-k8s-stack","reconcileID":"a09a216a-1524-455b-9b32-06a99ef8d10d","error":"cannot patch finalizers for object=\"operator.victoriametrics.com/v1beta1, Kind=VMSingle\" with name=\"victoria-metrics-k8s-stack\": Internal error occurred: failed calling webhook \"vmsingle.victoriametrics.com\": failed to call webhook: Post \"https://victoria-metrics-k8s-stack-victoria-metrics-operator.victoriametrics.svc:9443/validate-operator-victoriametrics-com-v1beta1-vmsingle?timeout=10s\": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"vm-operator-ca\")"}
2025/01/08 10:06:33 http: TLS handshake error from 10.42.0.148:40954: remote error: tls: bad certificate
```

reproduce:

deploy helm chart with default values (except for grafana dependency which should be irrelevant)

kustomization.yaml

```yaml
namespace: victoriametrics

helmGlobals:
  chartHome: charts
helmCharts:
- name: victoria-metrics-k8s-stack
  version: 0.33.2
  repo: https://victoriametrics.github.io/helm-charts
  releaseName: victoria-metrics-k8s-stack
  includeCRDs: true
  namespace: victoriametrics
  valuesFile: values.yaml
```
