### ISSUE TITLE
add vmbackupmanager suffix to the job label for auto-generated vmservicescrape

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1216]
Currently, operator generates `VMServiceScrape` config for each port defined at `Service`. It produces the following configuration for the vmbackupmanager:

```yaml
  - attach_metadata: {}
    path: /metrics
    port: http
  - attach_metadata: {}
    path: /metrics
    port: vmbackupmanager
```

 It makes produces metrics with the same job name, but different addresses and container names. And it makes metrics hard to use with grafana dashboards that relies only at `job` labels to distinguish components.

 I propose the following changes:
- add `port` suffix for non default (aka `http`) ports with relabelConfigs.
- by default generate endpoints only for `http` and `vmbackupamanger` ports. Currently it will be generate for the any ports defined at `Service`.
