### ISSUE TITLE
Possible bug in ServiceMonitor → VMServiceScrape conversion (regex field incorrectly interpreted as array)

### ISSUE THREAD

**Issue by rassvetalov** [VictoriaMetrics/operator#1219]
We are experiencing an issue with the VictoriaMetrics Operator converting a Prometheus Operator ServiceMonitor resource into a VMServiceScrape. Our environment details:
	•	Kubernetes version: 1.29
	•	VictoriaMetrics Operator version: :v0.51.3
	•	Installation method: Helm 

Description of the problem

We have a ServiceMonitor resource that includes metricRelabelings and relabelings with regex and replacement fields. When the VictoriaMetrics Operator attempts to convert this ServiceMonitor into a VMServiceScrape, we receive the following error in the operator logs:
`{"level":"error","ts":"2025-01-14T19:43:42Z","logger":"controller.PrometheusConverter","msg":"cannot update VMServiceScrape","vmservicescrape":"karpenter","namespace":"kube-system","error":"VMServiceScrape.operator.victoriametrics.com \"karpenter\" is invalid: [spec.endpoints[0].relabelConfigs[0].regex: Invalid value: \"array\": spec.endpoints[0].relabelConfigs[0].regex in body must be of type string: \"array\", spec.endpoints[0].metricRelabelConfigs[0].regex: Invalid value: \"array\": spec.endpoints[0].metricRelabelConfigs[0].regex in body must be of type string: \"array\"]"}`
It appears that the operator interprets the regex field as an array, even though in our YAML we have tried putting it as a string

Steps to reproduce
	1.	Install Prometheus Operator and VictoriaMetrics Operator in the same cluster.
	2.	Deploy the following ServiceMonitor (simplified example):
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karpenter
  namespace: kube-system
spec:
  endpoints:
    - interval: 30s
      port: http-metrics
      path: /metrics
      metricRelabelings:
        - action: drop
          regex: ^karpenter_cloudprovider_instance.*
          sourceLabels:
            - __name__
        - action: replace
          replacement: 'itprod'
          targetLabel: team
      relabelings:
        - action: replace
          regex: ^(.*)$
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: nodename
        - action: replace
          sourceLabels:
            - __meta_kubernetes_service_name
          targetLabel: app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
```
**Questions / Requests**

- Could you please confirm if there is a known issue or bug with regex fields being interpreted as arrays during the automatic conversion from ServiceMonitor to VMServiceScrape?
- Are there any additional debugging steps or configuration we should apply to ensure the regex fields remain strings?
- Is there a known workaround that allows us to keep using ServiceMonitor specs with valid regex expressions without triggering this error?
