### ISSUE TITLE
Defaults CPU requests for reload container too high

### ISSUE THREAD

**Issue by datamuc** [VictoriaMetrics/operator#1235]
Currently all the configReloaders have default cpu requests like this

```
# memory omitted here they look ok to me
resources:
  requests:
    cpu: 100m
```

I think that is too much. If you spin up 5 vmauth half a cpu is gone just for triggering a config reload.

So I propose something like this:

```
resources:
  requests:
    cpu: 10m
  limits:
    cpu: 50m
```
Or maybe even 10m/10m (not sure about that). But the above is what I did to my deployments.

**Comment by f41gh7** [comment]
I think, limits must be removed by default and only requests left. So config-reloader container should have the following resources:
```
resources:
  requests:
    cpu: 10m
    memory: 56Mi
```

**Comment by f41gh7** [comment]
The feature was included into [v0.54.0 release](https://docs.victoriametrics.com/operator/changelog/#v0540)

**Comment by yuriydzobak** [comment]
Is it possible to configure the memory limit globally?

**Comment by f41gh7** [comment]
> Is it possible to configure the memory limit globally?

No, currently it's not possible.  Can you please share your case, why it's needed to have `resources.limit` set at config-reloader container?

**Comment by yuriydzobak** [comment]
Hi,
In my case, I'm using [OPA](https://www.openpolicyagent.org/docs/v0.12.2/kubernetes-admission-control/) and i have rule that verify fields for `resources.limit`. If a POD resource is misconfigured and to control eviction priority. Additionally, removing `resources.limit` has changed the [POD's QoS](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/); it is no longer [guaranteed](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#guaranteed), and we need to update each CRD accordingly. It would be helpful if we could use environment variables to configure parameters like these for config-reload in Operator globally. [LINK](https://docs.victoriametrics.com/operator/vars/) insted of expand CRD VMagent/VMalert and so on
```
  containers:
    - name: config-reloader
      resources:
        limits:
          cpu: 10m
          memory: 20Mi
```
