### ISSUE TITLE
failed to start contianer with operator image v-.53.0

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/operator#1238]
When I upgrade operator  to v0.53.0, the operator pod is always crashed. And here are message from `kubectl describe po`. It seems that this image is broken.

I use amd64 image, and the kubelet version is  v1.26.1-tke.3

```
- containerID: containerd://369ba613572fdfd02cdae53438f6f73da46defeb539c3e9e116c08b273d87367
    image: harbor.xaminim.com/minimax-pub/victoriametrics/operator:v0.53.0
    imageID: harbor.xaminim.com/minimax-pub/victoriametrics/operator@sha256:ca48d374b631d3f3e918dc5b0243cc467fd328c16ca201326a8982429a301615
    lastState:
      terminated:
        containerID: containerd://369ba613572fdfd02cdae53438f6f73da46defeb539c3e9e116c08b273d87367
        exitCode: 128
        finishedAt: "2025-02-13T06:51:06Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "manager": executable file not found in $PATH: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
```

ping @f41gh7

**Comment by xiaozongyang** [comment]
When I change to the docker io image, I got same error message.

```
  containerStatuses:
  - containerID: containerd://0abeeab55d26eddd957ea7bd520e1c3e2b29401675ac088302736da8db2f0a00
    image: docker.io/victoriametrics/operator:v0.53.0
    imageID: docker.io/victoriametrics/operator@sha256:f2a6ed52e9254dfdccae049cfc98536678b9353a57520a2943ead6f4f7fff813
    lastState:
      terminated:
        containerID: containerd://0abeeab55d26eddd957ea7bd520e1c3e2b29401675ac088302736da8db2f0a00
        exitCode: 128
        finishedAt: "2025-02-13T06:57:35Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "manager": executable file not found in $PATH: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
    name: victoria-metrics-operator
```
