### ISSUE TITLE
Possibility to target `VMuser` on `VLogs`

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/operator#1241]
At the moment such a design is not possible

```
kind: VMUser
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: vlogs
  namespace: vlogs
spec:
  username: simple-user
  password: simple-password
  targetRefs:
     - crd:
         kind: VLogs
         name: vlogs
         namespace: vlogs
       paths: ["/insert/loki/api/v1/push"]
```

> VMUser.operator.victoriametrics.com "simple-user" is invalid: spec.targetRefs[0].crd.kind: Unsupported value: "VLogs": supported values: "VMAgent", "VMAlert", "VMSingle", "VMAlertManager", "VMAlertmanager", "VMCluster/vmselect", "VMCluster/vmstorage", "VMCluster/vminsert"

and I have to use this.

```
kind: VMUser
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: vlogs
  namespace: vlogs
spec:
  username: simple-user
  password: simple-password
  targetRefs:
    - static:
        url: http://vlogs-vlogs.vlogs.svc.cluster.local:9428
      paths: ["/insert/loki/api/v1/push"]
```
