### ISSUE TITLE
StatefulSet using OnDelete update strategy have stale currentRevision

### ISSUE THREAD

**Issue by ebensom** [VictoriaMetrics/operator#1242]
The vmoperator manages the StatefulSets belonging to VMClusters and VMAlertmanagers using `OnDelete` `updateStrategy.type`. In such case, K8s statefulset controller does not update the `status.currentRevision` to the value of `status.updateRevision` when the last pod was successfully deleted and hence updated to the current controllerrevision. This cause stale information to be exposed in the status block, and moreover the `currentReplicas` to be missing:

```
status:
  availableReplicas: 6
  collisionCount: 0
  currentRevision: vmstorage-skr-697c996f7b
  observedGeneration: 38
  readyReplicas: 6
  replicas: 6
  updateRevision: vmstorage-skr-74c4bd7697
  updatedReplicas: 6
```

vmoperator could patch the statefulset/status subresource to have the `currentRevision` equal to the `updateRevision` when the last pod is deleted.
