### ISSUE TITLE
The maxDiskUsagePerURL field in VMAgentSpec does not support array value.

### ISSUE THREAD

**Issue by 0megam** [VictoriaMetrics/operator#1256]
According to the VMagent documentation, the -remoteWrite.maxDiskUsagePerURL flag allows an array to be set as its value:
```
  -remoteWrite.maxDiskUsagePerURL array
     The maximum file-based buffer size in bytes at -remoteWrite.tmpDataPath for each -remoteWrite.url. When buffer size reaches the configured maximum, then old data is dropped when adding new data to the buffer. Buffered data is stored in ~500MB chunks. It is recommended to set the value for this flag to a multiple of the block size 500MB. Disk usage is unlimited if the value is set to 0
     Supports the following optional suffixes for size values: KB, MB, GB, TB, KiB, MiB, GiB, TiB. (default 0)
     Supports array of values separated by comma or specified via multiple flags.
     Empty values are set to default value.
```
However, Victoria-Metrics Operator does not allow an array value to be set for maxDiskUsagePerURL.
```
spec.remoteWriteSettings.maxDiskUsagePerURL in body must be of type integer: "string" (retried 5 times).
```

**Comment by f41gh7** [comment]
Thanks for reporting!  I think, `maxDiskUsagePerURL` should be added as part of `remoteWrite` configuration.

 Current workaround to use the following syntax:
 ```yaml
kind: VMAgent
spec:
 extraArgs:
   # comma separated values for each remoteWrite
    maxDiskUsagePerURL: 5GB,10GB,20GB
```

**Comment by f41gh7** [comment]
Actually, VMAgent supports per remoteWrite configuration with `maxDiskUsage` param and it can be used to overwrite value from remoteWriteSettings.maxDiskUsagePerURL.

 However, currently it has a critical bug. The following configuration:
```yaml
kind: VMAgent
metadata:
  name: sample
spec:
  selectAllByDefault: true
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-dc-1.default.svc:8429/api/v1/write"
      maxDiskUsage: 10GB
    - url: "http://vmsingle-dc-2.default.svc:8429/api/v1/write"
      maxDiskUsage: 15GB
```
 With unconditionally prepend `-remoteWrite.maxDiskUsagePerURL=1073741824` to the container args. As a mitigation, it's possible to define an empty `remoteWriteSettings: {}`


 Upcoming release will introduce the following changes:
* fix bug with incorrectly prepended flag
* allow to use both string and integer values for `remoteWriteSettings.maxDiskUsagePerURL` and `remoteWrite.maxDiskUsage`.
* properly inherit defined value at remoteWriteSettings.maxDiskUsagePerURL, if `remoteWrite.maxDiskUsage` for some of `remoteWrite`s.
