### ISSUE TITLE
additional service: `serviceSpec.metadata.name` is ignored if using as default service

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/operator#1268]
Create a VMAlert object:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example
spec:
  datasource:
    url: http://vmselect-vm-stack-victoria-metrics-k8s-stack.default.svc.cluster.local.:8481/select/0/prometheus
  evaluationInterval: 20s
  externalLabels: {}
  extraArgs:
    notifier.blackhole: "true"
  image:
    tag: v1.112.0
  selectAllByDefault: true
  serviceSpec:
    metadata:
      name: some-name
    spec:
      type: ClusterIP
    useAsDefault: false
```
Note that 2 services are created `vmalert-example` and `some-name`.

Update spec:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example
spec:
  datasource:
    url: http://vmselect-vm-stack-victoria-metrics-k8s-stack.default.svc.cluster.local.:8481/select/0/prometheus
  evaluationInterval: 20s
  externalLabels: {}
  extraArgs:
    notifier.blackhole: "true"
  image:
    tag: v1.112.0
  selectAllByDefault: true
  serviceSpec:
    metadata:
      name: some-name
    spec:
      type: ClusterIP
    useAsDefault: true 
```

Note that `some-name` service was deleted, but `vmalert-example` is still present.
