### ISSUE TITLE
OAuth2 doesn't support TLSConfig

### ISSUE THREAD

**Issue by iriabaka** [VictoriaMetrics/operator#1276]
The operator currently prevents the passing of TLSConfig parameters to vmagent, despite vmagent natively supporting such configurations, which can be set up directly within a container.  

This limitation affects my configuration (shown below), causing it to fail.  
When a request is sent to the token_url, I receive an error indicating that the certificates are not valid.

Relevant code references:

Operator: https://github.com/VictoriaMetrics/operator/blob/c1676777f440abe291e7c89bfc964d9351c61659/api/operator/v1beta1/common_scrapeparams.go#L64-L84

VMAgent: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/ee3ed8ab868c9657dbd9972e78b2333e1b621af1/lib/promauth/config.go#L140-L149

My configuration that doesn’t work:
```yaml
spec:
  jobName: metrics
  targetEndpoints:
    - oauth2:
        client_id:
          secret:
            key: client_id
            name: vm-oauth2
        client_secret:
          key: client_secret
          name: vm-oauth2
        scopes:
          - ovirt-app-api
        token_url: https://service.example.com/api/sso/oauth/token
      path: /api/metrics
      scheme: https
      targets:
        - service.example.com
      tlsConfig:
        insecureSkipVerify: true
```

**Comment by f41gh7** [comment]
Hello, can you please make sure that operator and CRD version is up-to-date. Provided configuration works for me.

 For example, the following config:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: vmstaticscrape-sample
  namespace: default
spec:
  jobName: static
  targetEndpoints:
  - labels:
      env: dev
      project: operator-2
    oauth2:
      client_id:
        secret:
          key: client_id
          name: vm-oauth2
      client_secret:
        key: client_secret
        name: vm-oauth2
      scopes:
      - ovirt-app-api
      token_url: https://service.example.com/api/sso/oauth/token
    targets:
    - 192.168.0.1:9100
    - 196.168.0.50:9100
---
apiVersion: v1
data:
  client_id: c29tZS1pZA==
  client_secret: c29tZS1zZWNyZXQ=
kind: Secret
metadata:
  name: vm-oauth2
  namespace: default
type: Opaque
```

 Produces the following vmagent config, which looks good to me:
```yaml
- job_name: staticScrape/default/vmstaticscrape-sample/0
  static_configs:
  - targets:
    - 192.168.0.1:9100
    - 196.168.0.50:9100
    labels:
      env: dev
      project: operator-2
  honor_labels: false
  relabel_configs:
  - target_label: job
    replacement: static
  oauth2:
    client_id: some-id
    client_secret: some-secret
    scopes:
    - ovirt-app-api
    token_url: https://service.example.com/api/sso/oauth/token
```

 Can you please provide any related vmagent/operator errors?
