### ISSUE TITLE
spec.vmProberSpec.scheme isn't honored in VMProbes

### ISSUE THREAD

**Issue by ptimofee** [VictoriaMetrics/operator#1294]
Hello
Latest operator version v0.54.1 doesn't honor `spec.vmProberSpec.scheme` in `VMProbe`. It's always `http` no matter if it's actually set to `https` in the CR manifest.
I did my research and this breakage happened between v0.46.4 and v0.47.0.

Steps to reproduce:
- deploy operator v0.46.4
- deploy any VMAgent
- deploy VMProbe (note `spec.vmProberSpec.scheme` value)
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: test-vmprobe
spec:
  interval: 30s
  jobName: test-vmprobe
  targets:
    staticConfig:
      targets:
      - https://docs.victoriametrics.com/
  tlsConfig:
    insecureSkipVerify: true
  vmProberSpec:
    scheme: https
    url: some.fqdn.local
```
- go to VMAgent UI and verify `scheme` value was taken into consideration - find the probe in the `targets` list and look at the endpoint url
- update operator to v0.47.0
- go to VMAgent UI and verify `scheme` value was NOT taken into consideration
