### ISSUE TITLE
statefulSet volumeMount name not Found

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1303]
Currently, Kubernetes StatefulSet controller doesn't validate for invalid references at volumes and volumeMounts.

 As an example:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-vmcluster-persistent
spec:
  retentionPeriod: "4"
  vmstorage:
    configMaps:
      - some
    replicaCount: 2
    volumeMounts:
    - name: some
      mountPath: /opt/some
```

 Operator will create StatefulSet, but Pod creation will fail with the following reason at Kubernetes Events:
```
32s         Warning   FailedCreate              statefulset/vmstorage-example-vmcluster-persistent                                create Pod vmstorage-example-vmcluster-persistent-0 in StatefulSet vmstorage-example-vmcluste
r-persistent failed error: Pod "vmstorage-example-vmcluster-persistent-0" is invalid: spec.containers[0].volumeMounts[1].name: Not found: "some"
```

 It'd be great to have validation for this case and write error reason into vmcluster.status field.

 Also, It's required to update documentation and name formatting for `secret` and `configMaps` volume names.
