### ISSUE TITLE
OAuth2 doesn't support headers settings

### ISSUE THREAD

**Issue by IshinMV** [VictoriaMetrics/operator#1317]
The operator does not currently support passing headers parameters to vmagent for token_url in oauth2. And this is required when the mandatory headers for token_url differ from the headers targets

Relevant code links:

```
global:
  scrape_interval: 30s
scrape_configs:
- job_name: metrics
  static_configs:
  - targets:
    - example.com
  metrics_path: /ovirt-engine/services/metrics
  scheme: https
  tls_config:
    insecure_skip_verify: true
  oauth2:
    tls_config:
      insecure_skip_verify: true
    headers:
    - "Accept: application/json"
    client_id: getmetrics@internalsso
    client_secret: fake-password
    scopes:
    - ovirt-app-api
    token_url: http://example.com/ovirt-engine/sso/oauth/token
```
