### ISSUE TITLE
OAuth2 doesn't update bearer token when he has expired (401 error)

### ISSUE THREAD

**Issue by IshinMV** [VictoriaMetrics/operator#1318]
vmagent+vmauth get a bearer token and use it until the session is terminated. After a 401 error occurs, a token re-request does not occur.

Getting a token
![Image](https://github.com/user-attachments/assets/fb6bd201-f4d3-4b45-9d21-41c6e7aa928c)

Using this token
![Image](https://github.com/user-attachments/assets/7fabf664-2a70-43ca-a9cf-437539f63674)

Repeating 401 error without attempting to re-request the bearer token.
![Image](https://github.com/user-attachments/assets/00b1bfdc-f668-4e41-bfff-86caa4a56dd4)

Relevant vmagent code links:

```
global:
  scrape_interval: 30s
scrape_configs:
- job_name: zvirt
  static_configs:
  - targets:
    - example.com
  metrics_path: /ovirt-engine/services/metrics
  scheme: https
  tls_config:
    insecure_skip_verify: true
  oauth2:
    tls_config:
      insecure_skip_verify: true
    client_id: fake-login
    client_secret: fake-password
    scopes:
    - ovirt-app-api
    token_url: http://vmauth:8427/ovirt-engine/sso/oauth/token
```

Relevant vmauth code links:

```
unauthorized_user:
  url_prefix: "https://example.com/"
  headers:
    - "Accept: application/json"
  retry_status_codes: [401, 503, 500]
```

Vmauth supports the retry_status_codes field, but it works on the first request and does not initiate a restart of the authorization after it expires.
