### ISSUE TITLE
VMAgent unable to discover VMScrapeConfig

### ISSUE THREAD

**Issue by IamGroot19** [VictoriaMetrics/operator#1329]
Hello, I deployed VMAgent thru CR and then deployed a separate manifest of VMScrapeConfig + a fake exporter. VMAgent is not able to discover this target (port-forward to localhost and check `localhost:8429/targets`). 

Here are the manifests. I am adding only relevant fields from VMAgent  (since i need to redact lot of ocmpany specific info)
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
spec:
  scrapeConfigNamespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
      values: []
  scrapeConfigSelector:
    matchExpressions:
    - key: obs_scrape
      operator: In
      values:
      - "true"
```

Here is the VMScrapeConfig and fake exporter
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-fake-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-fake-exporter
  template:
    metadata:
      annotations:
        # Automatic prometheus scraping
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        obs_scrape: 'true'
        scope: cluster
        sidecar.istio.io/inject: "false"
      labels:
        app: prometheus-fake-exporter
    spec:
      automountServiceAccountToken: false
      containers:
      - image: 3h4x/prometheus-fake-exporter:latest
        name: prometheus-fake-exporter
        ports:
        - containerPort: 9100
        env:
        - name: LABEL_NAME
          value: deployment
        - name: LABEL_VALUE
          value: prometheus-fake-exporter
        - name: VALUE_HTTP_ENDPOINT
          value: https://gist.githubusercontent.com/3h4x/38ba057db9cbb80c7bf8ad768a90d086/raw/value
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: prometheus-fake-exporter
  labels:
    obs_scrape: 'true'
spec:
  kubernetesSDConfigs:
    - role: pod
  path: /metrics
  relabelConfigs:
    # Keep only pods with the required prometheus scrape annotations
    - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true

    - action: keep
      regex: ([^:]+):(\d+)
      source_labels:
      - __address__

    - action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      source_labels:
      - __address__
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      target_label: __address__

    # Add job labelp
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      action: replace
      targetLabel: job

    # Add namespace as label
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace

    # Add pod name as label
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod

    # Add container name as label
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      action: replace
      targetLabel: container

    # Add node name as label
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      action: replace
      targetLabel: node
```

I am not sure if it's a bug on VMAgent side or if it's a config mistake on my side.  Loglevel for VMAgent is already set at INFO and it didnt print anything related to the above VMScrapeConfig Would appreciate some help here. Thanks!
