### ISSUE TITLE
How to properly configure VMAgent CRD for remote-write with OAuth2

### ISSUE THREAD

**Issue by AlphaStyle** [VictoriaMetrics/operator#1336]
Versions:
- operator: v0.56.0
- vmagent: v1.115.0
- vmauth: v1.115.0

We use VMOperator and we are trying to send metrics from one cluster (VMAgent) to another (VMCluster) through [OAuth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) and VMAuth. We looked into the VMOperator API Docs to see how the [OAuth2 in the RemoteWrite Spec](https://docs.victoriametrics.com/operator/api/#oauth2) could be configured. 

We find the documentation to be somewhat confusing and are wondering how we can properly configure OAuth2 for the VMAgent Remote Write? Our observation and experience so far is that the OAuth2 configuration, if configured through the VMOperator's VMAuth RemoteWriteSpec CRD (**example 1**), will default to authorization code flow rather than client credentials? When we use the `extraArgs` configuration option in the VMAgent CRD (**example 2**) it will use client credentials as we expect, and the remote-write will also work as expected. (*We use [mitmproxy](https://mitmproxy.org/) to inspect the network traffic*).

Example 1 (*we have multiple remote writes but the example only show the configuration for section we are interested in*):

```yaml
# ...
- headers:
  # VMAuth Bearer token
  - custom-header:Bearer $(VMCLUSTER_REMOTE_WRITE)
  oauth2:
    client_id:
      secret:
        key: client-id
        name: secret-name
        optional: false
    client_secret:
      key: client-secret
      name: secret-name
      optional: false
    scopes:
      - <scope>
    token_url: <token_url>
  url: https://example.com/prometheus/api/v1/write
# ...
```

Example 2 (*`extraArgs` can be used together with example 1*):

```yaml
extraArgs:
  remoteWrite.oauth2.clientID: ',,<client_id>'
  remoteWrite.oauth2.clientSecret: ',,<client_secret>'
```

When we inspect the VMAgent container we do find the file `/etc/vmagent/config/RWS_2-SECRET-OAUTH2SECRET` and it has the correct `client_secret` value. It look like the secret file will be incremented depending on how many remote writes that are configured (Eg `RWS_n`). [api/operator/v1beta1/vmagent_types.go](https://github.com/VictoriaMetrics/operator/blob/master/api/operator/v1beta1/vmagent_types.go#L497-L505)

```go
// AsSecretKey key for kubernetes secret data
func (*VMAgentRemoteWriteSpec) AsSecretKey(idx int, suffix string) string {
	return fmt.Sprintf("RWS_%d-SECRET-%s", idx, strings.ToUpper(suffix))
}
```

When we inspect the the VMAgent's CLI Arguments (`kubectl exec -it pods/vmagent -c vmagent -- sh -c 'ps aux | more'`) we see for example `-remoteWrite.basicAuth.passwordFile` but not `-remoteWrite.oauth2.clientSecretFile` nor `-remoteWrite.oauth2.clientSecret`. Not sure if that is related to the issue or not? Maybe the file (or secret) is loaded behind the scene and not as an argument?

```
-remoteWrite.basicAuth.passwordFile=,/etc/vmagent/config/RWS_1-SECRET-BASICAUTHPASSWORD
```

Look like it will only set OAuth2 Client Secret File if you specify it. [internal/controller/operator/factory/vmagent/vmagent.go](https://github.com/VictoriaMetrics/operator/blob/master/internal/controller/operator/factory/vmagent/vmagent.go#L1344-L1347). But you cant specify both `oauth2.client_secret` and `oauth2.client_secret_file`, must choose one.

```go
if len(rws.OAuth2.ClientSecretFile) > 0 {
  oauth2ClientSecretFile.isNotNull = true
  oaSecretKeyFile = rws.OAuth2.ClientSecretFile
}
```

Do you see any obvious mistakes we have made ? Feedback's are most welcome 🙂
