### ISSUE TITLE
VMSingle uses port 8429 where binary default port is 8428

### ISSUE THREAD

**Issue by makasim** [VictoriaMetrics/operator#1343]
This setup could cause confusion for users familiar with binary-based deployments or docs, as they might expect, storage API to be available on port 8428 (e.g., when using port-forwarding or defining remoteWrite.url). However, such requests would fail, leading to unnecessary troubleshooting.

Additionally, port 8429 is the default for vmagent, which can further add to the confusion. For instance, someone might assume they're interacting with vmagent based on the port number, when in fact it's vmstorage. Moreover, using the same port for both components prevents their port-forwarding simultaneously.

An example of VMSingle created by the operator (note that the port is explisitly defined):
```
kubectl -n vm get pod vmsingle-demo-54f8fc5777-sw6xp -o yaml
apiVersion: v1
kind: Pod
metadata:
  name: vmsingle-demo-54f8fc5777-sw6xp
  namespace: vm
spec:
  containers:
  - args:
    - -httpListenAddr=:8429
    - -retentionPeriod=4d
    - -storageDataPath=/victoria-metrics-data
    image: victoriametrics/victoria-metrics:v1.115.0
    imagePullPolicy: IfNotPresent
    name: vmsingle
    ports:
    - containerPort: 8429
      name: http
      protocol: TCP
```

Proposed solution:
Use the default port 8428 within the vmstorage pod, and configure the corresponding Kubernetes service to proxy traffic from both ports 8428 and 8429 to the pod. Additionally, mark port 8429 as deprecated to discourage further use and minimize future confusion. The operator should switch all usages to the default port. 8429 is kept for BC.

**Comment by makasim** [comment]
![Image](https://github.com/user-attachments/assets/2eedcced-d246-495b-b886-132056b03e24)
![Image](https://github.com/user-attachments/assets/193938af-61bb-47f6-ac2f-b4dcdc530e82)

**Comment by makasim** [comment]
Changes related to ports must not trigger pod restarts during the operator upgrade. Existing resources should retain their current behavior and only adopt new configurations when explicitly re-deployed by the user.

fyi @f41gh7

**Comment by makasim** [comment]
An example of confusion in the documentation https://github.com/VictoriaMetrics/operator/issues/1345

**Comment by f41gh7** [comment]
Since the next release, operator will add `8428` port alias to the Service:

```yaml
apiVersion: v1
kind: Service
spec:
  ....
  ports:
  - name: http
    port: 8429
    protocol: TCP
    targetPort: 8429
  - name: http-alias
    port: 8428
    protocol: TCP
    targetPort: 8429
  type: ClusterIP
```
