### ISSUE TITLE
docs: vmagent in daemon set mode guide

### ISSUE THREAD

**Issue by makasim** [VictoriaMetrics/operator#1349]
Each vmagent scrapes only the node it runs on. 

The guide should be a part of [VictoriaMetrics Agent](https://docs.victoriametrics.com/helm/victoriametrics-agent/) page. It should highlight that VMAgent managed by the VictoriaMetrics operator does this feature automaticlly while helm chart require manual configuration.

**Comment by makasim** [comment]
The vmagnet config example for scraping only pods on the same node:

```
# -- VMAgent mode: daemonSet, deployment, statefulSet
mode: daemonSet

# -- [K8s DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) specific variables
daemonSet:
  spec: {}

env:
  - name: KUBE_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
remoteWrite:
  - url: http://vm-insert:8480/insert/0/prometheus #CHANGE TO vmauth or LB destination 

config:
  global:
    scrape_interval: 30s # CHANGE 

  scrape_configs:
    - job_name: "kubernetes-pods"
      kubernetes_sd_configs:
        - role: pod
          selectors:
            - role: pod
              field: spec.nodeName=%{KUBE_NODE_NAME}

      relabel_configs:
        - action: drop
          source_labels: [__meta_kubernetes_pod_container_init]
          regex: true
        - action: keep_if_equal
          source_labels:
            [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: node
```
