### ISSUE TITLE
getting "duplicate scrape target with identical labels" after upgrading vmoperator to v0.57.0

### ISSUE THREAD

**Issue by vvxxvvxx** [VictoriaMetrics/operator#1356]
After upgrading the victoria metrics operator from v0.56.0 to v0.57.0, we got many `"duplicate scrape target with identical labels" ` error like below in vmagent pod logs.
```
2025-05-13T01:49:29.529Z        error   VictoriaMetrics/lib/promscrape/scraper.go:378   skipping duplicate scrape target with identical labels; endpoint=http://10.9.9.15:8429/metrics, labels={container="vmsingle",endpoint="8429",instance="10.9.9.15:8429",job="vmsingle-demo",namespace="monitoring",pod="vmsingle-demo-697455dabc-mb3dd",service="vmsingle-demo"}; make sure service discovery and relabeling is set up properly; see also https://docs.victoriametrics.com/vmagent/#troubleshooting; 
original labels for target1: {__address__="10.9.9.15:8429",__meta_kubernetes_endpoint_address_target_kind="Pod",..., __meta_kubernetes_endpoint_port_name="http-alias",...}; 

original labels for target2: {__address__="10.9.9.15:8429",__meta_kubernetes_endpoint_address_target_kind="Pod",...,__meta_kubernetes_endpoint_port_name="http",...}
```
We could see `__meta_kubernetes_endpoint_port_name` got 2 different value, `"http-alias"` from one target, and `"http"` in another target.

In v0.57.0, there is one new feature added:
FEATURE: [vmsingle](https://docs.victoriametrics.com/operator/resources/vmsingle/): add 8428 port alias to the VMSingle Service. See https://github.com/VictoriaMetrics/operator/issues/1343 for details.

now the vmsingle Service has 2 ports which is causing this duplicate target issue.
```
me$ k get svc -n monitoring vmsingle-demo -oyaml
apiVersion: v1
kind: Service
metadata:
...
  name: vmsingle-demo
  namespace: monitoring
...
spec:
...
  ports:
  - name: http
    port: 8429
    protocol: TCP
    targetPort: 8429
  - name: http-alias
    port: 8428
    protocol: TCP
    targetPort: 8429
...
```

vmoperator version: v0.57.0
vmsingle version: v1.116.0

**Comment by vvxxvvxx** [comment]
https://github.com/VictoriaMetrics/operator/issues/1343#issuecomment-2874930256

**Comment by f41gh7** [comment]
Could you please provide an example of scrape configuration? Operator creates the following `VMServiceScrape` config, which works as expected:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmsingle-vms-victoria-metrics-k8s-stack
  namespace: default
spec:
  endpoints:
  - attach_metadata: {}
    path: /metrics
    port: http
  namespaceSelector: {}
```

 Most probably, it could only take effect, if `prometheus.io/scrape` annotations are used for scraping. 

There are possible workarounds:
1) move `prometheus.io/scrape` from `Service` to `podMetadata.annotations`, which will use pod discovery configuration
2) suppress duplicate error with corresponding vmagent flag - `-promscrape.suppressDuplicateScrapeTargetErrors`
3) change `VMSingle` port to `8428` with `spec.port: "8428". It'll remove aliasing

 Long-term solution will be adding `8428` port to the vmsingle deployment by operator. But it's too intrusive change, that we'd like to avoid.

**Comment by vvxxvvxx** [comment]
Hi @f41gh7 , the VMServiceScrape from our side is like below. it was working good without such duplicate target issue when we were using vmopertor v0.56.0.
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
...
  name: vmsingle-demo
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    scheme: http
    targetPort: 8429
  jobLabel: vmsingle-scrape
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
...
```

> 1. move prometheus.io/scrape from Service to podMetadata.annotations, which will use pod discovery configuration

We don't have `prometheus.io/scrape` in the vmsingle-demo Service..

> suppress duplicate error with corresponding vmagent flag - -promscrape.suppressDuplicateScrapeTargetErrors

But with this flag `- -promscrape.suppressDuplicateScrapeTargetErrors`, the metric will still be scraped twice, it's just the error got suppressed..

> change VMSingle port to 8428 with `spec.port: "8428". It'll remove aliasing

seems this is a good solution. does it have any downside?

**Comment by makasim** [comment]
If you're using a custom VMServiceScrape resource, it's recommended to use `port: http` instead of `targetPort: 8429`. This helps avoid duplicate scrape target issues.

If you're not using a custom scrape resource and rely on the operator to manage scraping, there shouldn't be any problems.

**Comment by makasim** [comment]
>>change VMSingle port to 8428 with `spec.port: "8428". It'll remove aliasing

> seems this is a good solution. does it have any downside?

There shouldn’t be any issues, but I’d still recommend double-checking it in the staging environment first. Just to be safe.

**Comment by f41gh7** [comment]
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
...
  name: vmsingle-demo
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    scheme: http
-   targetPort: 8429
+.  port: http
  jobLabel: vmsingle-scrape
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
```

 Provided example will generate the following relabeling rule for `VMAgent` discovery:

```yaml
relabel_configs:
- action: keep
  source_labels:
  - __meta_kubernetes_endpoint_port_name
  regex: "http"
```

 Which matches an exact endpoint and will not produce any duplicate targets.
