### ISSUE TITLE
Adjust requestsLoadBalancer image when x.xxx.x-enterprise-cluster clusterVersion is used.

### ISSUE THREAD

**Issue by makasim** [VictoriaMetrics/operator#1365]
When setting clusterVersion: "v1.117.1-enterprise-cluster" in a VMCluster spec, the operator tries to use the same tag (v1.117.1-enterprise-cluster) for all components, including vmauth. However, there is no corresponding image tag v1.117.1-enterprise-cluster for the vmauth component. Only v1.117.1-enterprise is available.

Example (Does not work):
```
piVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
spec:
  clusterVersion: "v1.117.1-enterprise-cluster"

  # ...

  requestsLoadBalancer:
    enabled: true
```
This results in an image pull error for vmauth, as the specified tag does not exist.

Workaround (Works):
```

piVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
spec:
  clusterVersion: "v1.117.1-enterprise-cluster"

  # ...

  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        tag: "v1.117.1-enterprise"
```

Suggested Improvement:

The operator should be able to detect when a component (e.g., vmauth) does not have a tag matching clusterVersion and fall back to a valid, compatible tag automatically (e.g., v1.117.1-enterprise). 

Alternatively, it could fail with validation error but I personally dont like it.

**Comment by f41gh7** [comment]
Upcoming release will fix the issue with:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
spec:
  clusterVersion: "v1.117.1-enterprise-cluster"
  # ...
  requestsLoadBalancer:
    enabled: true
```

 When operator implicitly set `requestsLoadBalancer.spec.image.tag` to `v1.117.1-enterprise-cluster`. Now operator ignores value of `spec.clusterVersion` for `requestsLoadBalancer`. 

 The purpose of `clusterVersion` is management of cluster components version - `vmselect`, `vmstorage` and `vminsert`. It shouldn't change version of `vmbackupmanager` and `requestsLoadbalancer`. Since those components are supplemental and should be managed separately. The second reason is `VLCluster`, which also has `clusterVersion` spec and it's not possible to use it as `vmauth` version. So it also keeps behavior consistent.

**Comment by f41gh7** [comment]
To simplify enterprise version management, operator will implicitly add `-enteprise` suffix to the applications, if `license` is provided and `spec.image.tag` is not set.

 For example for vmsingle default value of `VM_VMSINGLEDEFAULT_VERSION` is `v1.120.0`.

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vms-victoria-metrics-k8s-stack
spec:
  license:
    keyRef:
      key: license.txt
      name: vm-license
  storage:
    resources:
      requests:
        storage: 30Gi
```

 And in default setup if `license` is set, vmsingle crashes with error `no such flag licenseKey`.

Upcoming version of operator will change it, but implicitly change the value of `VM_VMSINGLEDEFAULT_VERSION` from `v1.120.0` to `v1.120.0-enterprise`.


 However, changing of default value is based on best effort. If value of `VM_VMSINGLEDEFAULT_VERSION` is changed to `v1.120.0-enterprise` or `some-unknown-version`, operator will keep originally provided value. And will not add `-enterprise` suffix.
