### ISSUE TITLE
rendered crd is different than in docs

### ISSUE THREAD

**Issue by cmergenthaler** [VictoriaMetrics/operator#1396]
Hello,

while configuring our VM setup with CRs and following the [docs](https://docs.victoriametrics.com/operator/api/), we noticed that kubeconform fails even though operator is able to reconcile the deployed resources without problems. We investigated the problem and found out some fields are removed from rendered CRDs, resulting in a deviation between operator capabilities and the actual k8s CRDs. Is there a specific reason why some fields are being removed? 

**Example:**
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
spec:
  extraEnvs:
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
```

Is a valid CR from operator and [docs](https://docs.victoriametrics.com/operator/api/#vmsinglespec-extraenvs) perspective, it is working fine deploying the resource.

Still kubeconform fails validating the resource with the official CRD: `VMSingle is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/extraEnvs/0' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/operator.victoriametrics.com/vmsingle_v1beta1.json#/properties/spec/properties/extraEnvs/items/additionalProperties: additionalProperties 'valueFrom' not allowed`

The `valueFrom` (along with others) is removed from the rendered CRD here:
https://github.com/VictoriaMetrics/operator/blob/690ef8991d3265172b9cc6e6cff0c569f1d5fbc4/config/crd/patches/operator.victoriametrics.com_vmsingles.yaml#L18-L19

These removals block us from shift-left CR validation.
