### ISSUE TITLE
Error when validation webhooks are enabled

### ISSUE THREAD

**Issue by eiximenis** [VictoriaMetrics/operator#1403]
Hi! I am deploying victoria metrics operator in a Azure Kubernetes Service.
Validation webhooks are enabled but cert-manager is disabled (stadard `value.yaml` values)

When I deploy a VMSingle resource, I got following errors in operator:

```
{"level":"error","ts":"2025-06-10T08:28:38Z","logger":"manager","msg":"Reconciler error","controller":"vmsingle","controllerGroup":"operator.victoriametrics.com","controllerKind":"VMSingle","VMSingle":{"name":"victoria","namespace":"vm"},"namespace":"vm","name":"victoria","reconcileID":"dd9c079b-0d89-428c-b3b6-1df98cc5b08f","error":"failed create or update single: cannot  create serviceScrape for vmsingle: Internal error occurred: failed calling webhook \"vmservicescrapes.operator.victoriametrics.com\": failed to call webhook: the server could not find the requested resource"}   
```

As a result of that the VMSingle deployment is not created.

Some insights:

1. The validation webhook config is created:
```
> kubectl get validatingwebhookconfigurations
NAME                                      WEBHOOKS   AGE
vmo-victoria-metrics-operator-admission   17         104m
```
2. The values of the `validatingwebhookconfiguration` seem correct and secret for storing TLS cert is correctly generated
3. Operator is up & running, service has endpoints and webhook ports is mapped
4. No other errors logged in the operator pod

The AKS does  not have connectivity to internet, so all images are internal and published in a Azure Container Registry. The values file for chart was:

```
operator:
  enable_convert_ownership: true  
image:
  repository: mycustomacr.azurecr.io/victoriametrics/operator
  tag: v0.58.0
  pullPolicy: IfNotPresent
env:
  - name: VM_VMAGENTDEFAULT_CONFIGRELOADIMAGE
    value: mycustomacr.azurecr.io/prometheus-operator/prometheus-config-reloader:v0.82.1
```

Disabling the admission webhooks seems to work fine!
