### ISSUE TITLE
A way to replace only docker-hub images?

### ISSUE THREAD

**Issue by motoki317** [VictoriaMetrics/operator#1405]
Currently, using `VM_CONTAINERREGISTRY` replaces *all* image registries, regardless of original registries like docker-hub and quay.io.

My use-case is I want to replace only docker-hub images to a pull-through cache like ECR (since docker-hub rate limit is so low).
So when I set `VM_CONTAINERREGISTRY=<account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub`, where that path is configured for pull-through cache for docker-hub images, I get:
- `victoriametrics/victoria-metrics` replaced to `<account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/victoria-metrics`, which is valid.
- `quay.io/prometheus-operator/prometheus-config-reloader` replaced to `<account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/prometheus-operator/prometheus-config-reloader`, which is invalid (!), since there is no image such as `prometheus-operator/prometheus-config-reloader` on docker-hub. I do NOT want to replace `quay.io` images.

My current workaround is I set the following env values to the operator for every image *except* the config-reloader like this, but this is ugly:
```yaml
  - name: VM_VLOGSDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/victoria-logs
  - name: VM_VMALERTDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/vmalert
  - name: VM_VMAGENTDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/vmagent
  - name: VM_VMSINGLEDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/victoria-metrics
  - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/vmselect
  - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/vmstorage
  - name: VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/vminsert
  - name: VM_VMALERTMANAGER_ALERTMANAGERDEFAULTBASEIMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/prom/alertmanager
  - name: VM_VMBACKUP_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/vmbackupmanager
  - name: VM_VMAUTHDEFAULT_IMAGE
    value: <account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/victoriametrics/vmauth
```

Is there a way to replace only docker-hub images, or is there a better way to configure my ECR pull-through cache?

Possibly related: #654
