### ISSUE TITLE
Scrape objects Status regression after refactoring

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1416]
Regression introduced at 8df334ccab1706d91c2bd1708dfd9096f8c8a568

 Operator now longer reports not found configmap and secret references to the Scrape Object status.

Before: 

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: echo-svc-0
  namespace: default
spec:
  endpoints:
  - basicAuth:
      password:
        key: pass
        name: auth
      username:
        key: user
        name: auth
    port: http
    scheme: http
  selector:
    matchLabels:
      label-1: match-0
      label-2: match-0
status:
  conditions:
  - lastTransitionTime: "2025-06-22T12:57:01Z"
    lastUpdateTime: "2025-06-22T12:57:01Z"
    message: 'cannot load basicAuth secret for=serviceScrape/default/echo-svc-0/0:
      unable to fetch key from secret: "auth" for object: "default/auth" : secrets
      "auth" not found'
    observedGeneration: 1
    reason: ConfigParsedAndApplied
    status: "False"
    type: example-vmagent.default.vmagent.victoriametrics.com/Applied
  observedGeneration: 1
  reason: 'cannot load basicAuth secret for=serviceScrape/default/echo-svc-0/0: unable
    to fetch key from secret: "auth" for object: "default/auth" : secrets "auth" not
    found'
  updateStatus: failed
```

 After:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  annotations:
  name: echo-svc-0
spec:
  endpoints:
  - basicAuth:
      password:
        key: pass
        name: auth
      username:
        key: user
        name: auth
    port: http
    scheme: http
  selector:
    matchLabels:
      label-1: match-0
      label-2: match-0
status:
  conditions:
  observedGeneration: 1
  updateStatus: operational
```
