### ISSUE TITLE
The operator detects differences in generated resources every minute

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#1418]
## Describe the bug

The operator detects differences in Deployments and/or StatefulSets derived from custom resources and probably tries to update them every minute.

As far as seeing `.metadata.generation` of the Deployments and/or StatefulSets, they are *not* actually updated.

## To reproduce

- Deploy the operator
  <details>
  <summary>vm-operator Deployment</summary>

  ```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/instance: default
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: victoria-metrics-operator
      argocd.argoproj.io/instance: monitoring
      control-plane: vm-operator
    name: vm-operator
    namespace: monitoring
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        control-plane: vm-operator
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/default-container: manager
        labels:
          app.kubernetes.io/instance: default
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: victoria-metrics-operator
          control-plane: vm-operator
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - arm64
                  - ppc64le
                  - s390x
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
        containers:
        - args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8080
          - --webhook.enable
          - --webhook.certDir=/tmp/k8s-webhook-server/serving-certs
          env:
          - name: VM_DISABLESELFSERVICESCRAPECREATION
            value: "true"
          - name: VM_ENABLEDPROMETHEUSCONVERTER_PODMONITOR
            value: "false"
          - name: VM_ENABLEDPROMETHEUSCONVERTER_SERVICESCRAPE
            value: "false"
          - name: VM_ENABLEDPROMETHEUSCONVERTER_PROMETHEUSRULE
            value: "false"
          - name: VM_ENABLEDPROMETHEUSCONVERTER_PROBE
            value: "false"
          - name: VM_PSPAUTOCREATEENABLED
            value: "false"
          - name: VM_VMALERTDEFAULT_IMAGE
            value: ghcr.io/cybozu/victoriametrics-vmalert
          - name: VM_VMALERTDEFAULT_VERSION
            value: 1.113.0.1
          - name: VM_VMAGENTDEFAULT_IMAGE
            value: ghcr.io/cybozu/victoriametrics-vmagent
          - name: VM_VMAGENTDEFAULT_VERSION
            value: 1.113.0.1
          - name: VM_VMSINGLEDEFAULT_IMAGE
            value: ghcr.io/cybozu/victoriametrics-vmsingle
          - name: VM_VMSINGLEDEFAULT_VERSION
            value: 1.113.0.1
          - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_IMAGE
            value: ghcr.io/cybozu/victoriametrics-vmselect
          - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_VERSION
            value: 1.113.0.1
          - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_IMAGE
            value: ghcr.io/cybozu/victoriametrics-vmstorage
          - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_VERSION
            value: 1.113.0.1
          - name: VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_IMAGE
            value: ghcr.io/cybozu/victoriametrics-vminsert
          - name: VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_VERSION
            value: 1.113.0.1
          - name: VM_VMALERTMANAGER_ALERTMANAGERDEFAULTBASEIMAGE
            value: ghcr.io/cybozu/alertmanager
          - name: VM_VMALERTMANAGER_ALERTMANAGERVERSION
            value: 0.28.1.1
          - name: VM_USECUSTOMCONFIGRELOADER
            value: "true"
          - name: VM_CUSTOMCONFIGRELOADERIMAGE
            value: ghcr.io/cybozu/victoriametrics-config-reloader:0.59.2.1
          - name: WATCH_NAMESPACE
          image: ghcr.io/cybozu/victoriametrics-operator:0.59.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - containerPort: 8081
            name: probe
            protocol: TCP
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1500m
              memory: 1536Mi
            requests:
              cpu: 80m
              memory: 120Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: webhook-certs
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        serviceAccount: vm-operator
        serviceAccountName: vm-operator
        terminationGracePeriodSeconds: 10
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              control-plane: vm-operator
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        volumes:
        - name: webhook-certs
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
  ```
  </details>
  (Other resources like a `Certificate` are omitted)
- Apply the following manifest
  <details>
  <summary>VMCluster, VMAlertmanager and VMAlert</summary>

  ```yaml
  apiVersion: operator.victoriametrics.com/v1beta1
  kind: VMCluster
  metadata:
    name: vmc-test
    namespace: sandbox
  spec:
    vmstorage:
      replicaCount: 1
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: topolvm-flash1-ext4
            resources:
              requests:
                storage: 1Gi
      containers:
        - name: vmstorage
          startupProbe:
            httpGet:
              path: /health
              port: 8482
            failureThreshold: 30
            periodSeconds: 30
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch

    vmselect:
      replicaCount: 1

    vminsert:
      replicaCount: 1
  ---
  apiVersion: operator.victoriametrics.com/v1beta1
  kind: VMAlertmanager
  metadata:
    name: vmam-test
    namespace: sandbox
  spec:
    replicaCount: 1
    extraArgs:
      cluster.label: VMAlertmanager/sandbox/vmam-test
  ---
  apiVersion: operator.victoriametrics.com/v1beta1
  kind: VMAlert
  metadata:
    name: vma-test
    namespace: sandbox
  spec:
    replicaCount: 1
    datasource:
      url: "http://vmselect-vmc-test.sandbox.svc:8481/select/0/prometheus"
    notifier:
      selector:
        namespaceSelector:
          matchNames:
          - sandbox
    remoteWrite:
      url: "http://vminsert-vmc-test.sandbox.svc:8480/insert/0/prometheus"
    ruleNamespaceSelector:
      matchLabels:
        app.kubernetes.io/name: sandbox
  ```
  </details>
- The operator outputs logs every minute like:
  ```json
  cybozu@gcp0-boot-0:~$ kubectl logs -n monitoring vm-operator-649d6f9d76-7llnf -f --since 1s | grep --line-buffered sandbox
  {"level":"info","ts":"2025-06-23T09:22:08Z","logger":"controller.VMAlert","msg":"additional notifiers count=1 discovered with sd selectors","vmalert":"vma-test","namespace":"sandbox"}
  {"level":"info","ts":"2025-06-23T09:22:08Z","logger":"controller.VMAlert","msg":"updating Deployment vmalert-vma-test configurationis_prev_equal=false,is_current_equal=true,is_prev_nil=false, prev_spec_diff={v1.DeploymentSpec}.Template.Spec.Containers[0].Args[2]:-\"-notifier.url=http://vmalertmanager-vmam-test-0.vmalertmanager-vmam-test.sandbox.svc:9093\" +\"-notifier.url=\"","vmalert":"vma-test","namespace":"sandbox"}

  {"level":"info","ts":"2025-06-23T09:22:30Z","logger":"controller.VMAlertmanager","msg":"check if pod update needed to desiredVersion=vmalertmanager-vmam-test-5695b74977, podMustRecreate=false","vmalertmanager":"vmam-test","namespace":"sandbox"}
  {"level":"info","ts":"2025-06-23T09:22:30Z","logger":"controller.VMAlertmanager","msg":"no pod needs to be updated","vmalertmanager":"vmam-test","namespace":"sandbox"}

  {"level":"info","ts":"2025-06-23T09:22:49Z","logger":"controller.VMCluster","msg":"updating statefulset vmstorage-vmc-test configuration, is_current_equal=false,is_prev_equal=true,is_prev_nil=false, current_spec_diff={v1.StatefulSetSpec}.Template.Spec.Containers[0].StartupProbe.TimeoutSeconds:-\"1\" +\"0\",{v1.StatefulSetSpec}.Template.Spec.Containers[0].StartupProbe.SuccessThreshold:-\"1\" +\"0\"","vmcluster":"vmc-test","namespace":"sandbox"}
  {"level":"info","ts":"2025-06-23T09:22:54Z","logger":"controller.VMCluster","msg":"check if pod update needed to desiredVersion=vmstorage-vmc-test-54cd95dcd, podMustRecreate=false","vmcluster":"vmc-test","namespace":"sandbox"}
  {"level":"info","ts":"2025-06-23T09:22:54Z","logger":"controller.VMCluster","msg":"no pod needs to be updated","vmcluster":"vmc-test","namespace":"sandbox"}
  {"level":"info","ts":"2025-06-23T09:22:59Z","logger":"controller.VMCluster","msg":"check if pod update needed to desiredVersion=vmselect-vmc-test-6cf9488789, podMustRecreate=false","vmcluster":"vmc-test","namespace":"sandbox"}
  {"level":"info","ts":"2025-06-23T09:22:59Z","logger":"controller.VMCluster","msg":"no pod needs to be updated","vmcluster":"vmc-test","namespace":"sandbox"}
  ```

## Version

- VictoriaMetrics operator v0.59.2

## Additional information

- The operator doesn't detect differences if notifier(s) in `VMAlert` are configured with `url` directly instead of specifying `selector`.
- According to the logs above, vmselect and vmstorage are checked, but vminsert doesn't seem checked.
