### ISSUE TITLE
vmanomaly: `reason` field is not cleared after resource status change

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/operator#1426]
Step by step:
1. Create a vmanomaly resource with incorrect configuration.
2. Resource is transitioned to failed state with `reason` containing an error message.
3. Fix the reason and apply new configuration.
4. Resource status changes to `expanding`, but `reason` still contains an error message. For example:
```
  reason: |-
    failed to unmarshal anomaly configuration, name="example": yaml: unmarshal errors:
      line 1: field readers not found in type config.config
  updateStatus: expanding
```

**Comment by f41gh7** [comment]
It'd be great to check observedGeneration and if it differs from status generation, transit status to expanding.

**Comment by zekker6** [comment]
Here is a full status before:
```
status:
  observedGeneration: 1
  reason: 'failed to validate anomaly configuration, name="example": failed to validate
    model="mad_cpu_spikes": decay must be in range [0, 1], got 1.993000'
  shards: 2
  updateStatus: failed
```
And after:
```
status:
  observedGeneration: 2
  reason: 'failed to validate anomaly configuration, name="example": failed to validate
    model="mad_cpu_spikes": decay must be in range [0, 1], got 1.993000'
  shards: 2
  updateStatus: expanding
```
