### ISSUE TITLE
vmalert: notifier's tls assets missing from vmalert-tls-assets

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/operator#1437]
After ugpgrading vmoperator from `v0.59.2` to `v0.60.1`, any notifiers referencing a secret for a tls cert is no longer copied into `tls-assets-vmalert`

Example config:
```
notifiers:
- tlsConfig:
    ca:
      secret:
        key: ca.crt
        name: vmalert-tls
    cert:
      secret:
        key: tls.crt
        name: vmalert-tls
    insecureSkipVerify: true
    keySecret:
      key: tls.key
      name: vmalert-tls
  url: https://alertmanager-0.example.com
```
