### ISSUE TITLE
add writeRelabelConfigs configuration support for vmagent

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#154]
i suggest to add:

```
spec.remoteWrite: 
   - url: some-url
    writeRelabelConfigs:
     - action: keep
       source_labels: [__name__]
     - action: replace
     ```

 It could clash with existing urlRelabelConfig. Allow only one configuration per url.
