### ISSUE TITLE
Option override Kubernetes service type or Kubernetes ingress for VM/select/insert 

### ISSUE THREAD

**Issue by alexandrst88** [VictoriaMetrics/operator#163]
Hi! Ability to override Kubernetes Service Type, like LoadBalancer or NodePort.
```
type: ClusterIP
```

I've checked docs, and wasn't able to find how to override VM/select/insert service type. It's must have to expose vm cluster, if you want to have one dedicated metrics system setup.

https://github.com/VictoriaMetrics/operator/blob/771605e81f9b2a9b04808b8b66ff59b3ffebb980/controllers/factory/vmcluster.go#L726. Seems like it's hardcoded, @f41gh7, I could open PR for this one, if you are ok with?

**Comment by f41gh7** [comment]
Hello, for now, it can be created manually as additional service and type is hardcoded. 

 PR is welcome!  But please keep in mind, that changing value of Type requires service recreation. 

 Probably, its good idea to create separate definition at `spec`, how to expose object to outer world - with additional service, ingress, etc.

**Comment by TinySong** [comment]
any progress ? if not, I will fix this

**Comment by f41gh7** [comment]
Unfortunately, i cannot do it in next few weeks. Feel free to fix:)

**Comment by f41gh7** [comment]
will close it after release.

**Comment by TinySong** [comment]
is there a new bug to be founded for the issue reopened?

**Comment by f41gh7** [comment]
No, everything is ok. We are usually closing issues with features after release.

**Comment by f41gh7** [comment]
Was included to the 0.11.0 release. 

 Example usage:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-vmcluster-persistent
spec:
  retentionPeriod: "4"
  replicationFactor: 2
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
    serviceSpec:
         metadata:
               name: vmselect-vip-access
         spec:
            type: ClusterIP
  vminsert:
    replicaCount: 1
    serviceSpec:
       metadata:
           annotations:
               service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxxx, mySubnet
       spec:
           type: LoadBalancer
```

 This configuration produces two additional services:
- service with name `vmselect-vip-access` and clusterIP
- with with name `vminsert-example-vmcluster-persistent-additional-service`

```bash
vminsert-example-vmcluster-persistent                      ClusterIP      10.217.4.64    <none>                                 8480/TCP                     6s
vminsert-example-vmcluster-persistent-additional-service   LoadBalancer   10.217.5.26    <pending>                              8480:32649/TCP               6s
vmselect-example-vmcluster-persistent                      ClusterIP      None           <none>                                 8481/TCP                     91s
vmselect-vip-access                                        ClusterIP      10.217.5.173   <none>                                 8481/TCP                     91s
vmstorage-example-vmcluster-persistent                     ClusterIP      None           <none>                                 8482/TCP,8400/TCP,8401/TCP   95s
```
