### ISSUE TITLE
vm-operator pod cannot get resource lock

### ISSUE THREAD

**Issue by vterdunov** [VictoriaMetrics/operator#166]
K8s: v1.17.8
Operator: 0.8.0 

After fresh installation there are many logs entries about getting resource lock.
I tried to add permissions to the Role `leader-election-role`, but with no luck.
```yaml
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
 ```

The error messages:
```json
{
  "level": "error",
  "ts": 1613831607.2926767,
  "msg": "error retrieving resource lock monitoring-system/57410f0d.victoriametrics.com: leases.coordination.k8s.io \"57410f0d.victoriametrics.com\" is forbidden: User \"system:serviceaccount:monitoring-system:vm-operator\" cannot get resource \"leases\" in API group \"coordination.k8s.io\" in the namespace \"monitoring-system\"\n",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\nk8s.io/klog/v2.(*loggingT).output\n\tk8s.io/klog/v2@v2.4.0/klog.go:919\nk8s.io/klog/v2.(*loggingT).printf\n\tk8s.io/klog/v2@v2.4.0/klog.go:750\nk8s.io/klog/v2.Errorf\n\tk8s.io/klog/v2@v2.4.0/klog.go:1462\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew\n\tk8s.io/client-go@v12.0.0+incompatible/tools/leaderelection/leaderelection.go:325\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1\n\tk8s.io/client-go@v12.0.0+incompatible/tools/leaderelection/leaderelection.go:245\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire\n\tk8s.io/client-go@v12.0.0+incompatible/tools/leaderelection/leaderelection.go:244\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).Run\n\tk8s.io/client-go@v12.0.0+incompatible/tools/leaderelection/leaderelection.go:202"
}
```

**Comment by f41gh7** [comment]
Hello, i've tested version from helm chart repository and master branch and it seems to be ok. 

 Can you specify your deployment method?

 I hope, new release will be build soon with those fixes.

**Comment by vterdunov** [comment]
I [followed](https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#installing-by-manifest) this instruction.

**Comment by sorend** [comment]
I experience the same issue, installed the operator using the Kustomize approach. It's my impression that the Kustomization is missing the role.

Applying this manually solved the issue:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-operator-leader-election-role-2
  namespace: monitoring-system
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-operator-leader-election-rolebinding-2
  namespace: monitoring-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-operator-leader-election-role-2
subjects:
- kind: ServiceAccount
  name: vm-operator-vm-operator
  namespace: monitoring-system
```
