### ISSUE TITLE
[Question]: Ability to specify global VM version across its components

### ISSUE THREAD

**Issue by alexandrst88** [VictoriaMetrics/operator#176]
Hi! 

I checked the docs, but wasn't able to find global version parameter. 

instead of doing 
```
  vmstorage:
      image:
        repository: victoriametrics/vmstorage
        tag: v1.39.2-cluster
        pullPolicy: Always
  vmselect:
      image:
        repository: victoriametrics/vmselect
        tag: v1.39.2-cluster
        pullPolicy: Always
  vminsert:
      image:
        repository: victoriametrics/vminsert
        tag: v1.39.2-cluster
        pullPolicy: Always
```
To 
```
clusterVersion: v1.39.2-cluster 
```
