### ISSUE TITLE
Allow "not specified" in envvars for CPU and memory resources

### ISSUE THREAD

**Issue by morimoto-cybozu** [VictoriaMetrics/operator#181]
Users can create "burstable" Pods by specifying `.spec.resources.requests` and pruning `.spec.resources.limits` in custom resources, like the following.

```
kind: VMAgent
spec:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    # limits are not specified
```

This cannot be done with the [environment variables for the operator](https://github.com/VictoriaMetrics/operator/blob/master/vars.MD).
They have default values, and users can override the values only with some valid quantity, not with "not specified."
For example, the following configuration with removing `.spec.resources` from `VMAgent` will produce Pods with the limits of `cpu: 200m` and `memory: 500Mi` taken from the default.

```
env:
- name: VM_VMAGENTDEFAULT_RESOURCE_REQUEST_CPU
  value: 100m
- name: VM_VMAGENTDEFAULT_RESOURCE_REQUEST_MEM
  value: 200Mi
# RESOURCE_LIMIT_* are not specified
```

Forcing limits in the cluster-wide configuration is useful for strict resource planning, but it can sometimes be dangerous because violating Pods may be killed immediately.
It would be nice if users could use a special notation for "not specified" in envvars.

**Comment by f41gh7** [comment]
Added env vars into master branch to control this behavior per CRD object. For example, with `VM_VMALERTDEFAULT_USEDEFAULTRESOURCES=false` default resources will no be set for `VMAlert`.

**Comment by morimoto-cybozu** [comment]
@f41gh7 
Thank you for the change!  It's useful when applying the default values selectively.
But I'm afraid this is not what I meant.  What I want to do is to omit the limit specifications from the generated Deployment/StatefulSet while giving the request specifications in env vars.

With the current operator, the limits are supplied from the coded default even when giving the requests only.

```
[Input for operator]
env:
- name: VM_VMAGENTDEFAULT_RESOURCE_REQUEST_CPU
  value: 100m
- name: VM_VMAGENTDEFAULT_RESOURCE_REQUEST_MEM
  value: 200Mi
# RESOURCE_LIMIT_* are not specified

# and there is no ".spec.resources" in VMAgent CR

[Output Deployment of vmagent]
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m  # taken from internal/config/config.go
    memory: 500Mi  # ditto
```

I'd like to remove the limits from the output.  The intention of removal can be specified by introducing a new keyword, "unlimited" for example. 

```
[Input for operator]
env:
- name: VM_VMAGENTDEFAULT_RESOURCE_REQUEST_CPU
  value: 100m
- name: VM_VMAGENTDEFAULT_RESOURCE_REQUEST_MEM
  value: 200Mi
- name: VM_VMAGENTDEFAULT_RESOURCE_LIMIT_CPU
  value: unlimited
- name: VM_VMAGENTDEFAULT_RESOURCE_LIMIT_MEM
  value: unlimited

# and there is no ".spec.resources" in VMAgent CR

[Output Deployment of vmagent]
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  # limits are omitted
```
