### ISSUE TITLE
Add honor labels and honor timestamps to VMStaticScrape

### ISSUE THREAD

**Issue by marchenkov** [VictoriaMetrics/operator#195]
Please add honor_labels and honor_timestamps support in VMStaticScrape (vm-operator).

Now not possible to add honor labels and honor timestamp in static_config and use like this:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: vmstaticscrape-test
spec:
  jobName: test
  targetEndpoints:
    - targets: ["server-1.domain.com", "server-2.domain.com"]
      honorLabels: true
      honorTimestamps: true
      path: "/federate"
      scheme: "https"
      port: "443"
```

In final ```/etc/vmagent/config_out/vmagent.env.yaml``` no honor_labels and no honor_timestamps.

```
- job_name: victoriametrics/vmstaticscrape-test/0
  static_configs:
  - targets:
    - server-1.domain.com
    - server-2.domain.com
  metrics_path: /federate
  scheme: https
  relabel_configs:
  - target_label: job
    replacement: test
```

Is it possible to add this functional in VMStaticScrape?
