### ISSUE TITLE
Does vmalert connected with all alertmanager in HA mode?

### ISSUE THREAD

**Issue by Antknt47** [VictoriaMetrics/operator#214]
Since "Do not load balance traffic between Prometheus and its Alertmanagers" which is found at promethues officail documents, and I notice that, vmalert connecting only one alertmanager's service named with "vmalertmanager-alertmanager...". So, I check this service and found that, ClusterIP services which named with "tcp-mesh" or "udp-mesh". Does these service duplicate message and delivery them to each alertmanager?

**Comment by f41gh7** [comment]
Hello, for now, its needed to define all alertmanager replicas at `VMAlert` `spec.notifiers` section. `VMAlertmanager` must have `clusterIP: None` - headless service. 
   for example, when alertmanager has 3 replicas: 
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert
spec:
  datasource:
    url: "http://vmagent-example-vmsingle.default.svc:8429"
  notifiers:
    - url: "http://alertmanager-example-0.alertmanager-example.default.svc:9093"
    - url: "http://alertmanager-example-1.alertmanager-operated.default.svc:9093"
    - url: "http://alertmanager-example-2.alertmanager-operated.default.svc:9093"
```

 Later it can be simplified with this feature: https://github.com/VictoriaMetrics/operator/issues/114
