### ISSUE TITLE
[vmagent] Updating configmaps or secrets don't trigger a update/reload config

### ISSUE THREAD

**Issue by hamelg** [VictoriaMetrics/operator#222]
We are using the vmagent crd like that :
```
spec:
  remoteWrite:
    - url: http://xxxx/api/v1/write
      urlRelabelConfig:
        key: remotewrite01-labels.yaml
        name: remotewrite01-labels
  additionalScrapeConfigs:
    key: additional-scraps.yaml
    name: additional-scraps
```
Modifying the secret additional-scraps or the configmap remotewrite01-labels doesn't trigger a reload on the vmagent.

Is there any possible workaround ?

**Comment by f41gh7** [comment]
Hello, its a bug, will be fixed at the next release.

 For now, its possible to patch secret `additional-scraps`, you have to modify ownerRefrence:
```
apiVersion: v1
data:
  ....
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: default
  ownerReferences:
  - apiVersion: operator.victoriametrics.com/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: VMAgent
    name: example-vmagent
    uid: 8ab7fd8f-770d-4eba-aa9f-19139f1d3cff
```

 Change `ownerReferences` for  ` kind: VMAgent` for  `controller: true`
