### ISSUE TITLE
OpenShift and VictoriaMetrics Operator

### ISSUE THREAD

**Issue by sergsmirnoff** [VictoriaMetrics/operator#229]
Hi Team,
is there any way to collect all metrics from an OpenShift cluster using VMAgent and VMService Scrape instances managed by a VictoriaMetrics Operator? 
OpenShift monitoring stack uses Cluster Monitoring Operator which controls and manages the Prometheus Operator and all their associated components. 

Does all targets from OpenShift platform monitoring components (_kubelets, kubernetes and openshift apiserver/controller manager, etcd, registry, coredns, scheduler and other_) available for scrapping by VMAgent/VMService Scrape?

**Comment by f41gh7** [comment]
Hello, its possible to  scrape metrics from system components. But it requires some specific config, you have to create additional secrets with certificates and mount it to the `vmagent` crd. I'll try to provide some examples soon.

**Comment by f41gh7** [comment]
Example of vmagent, that reuses openshift default cluster-monitoring config:

 Note, it must be placed into openshift-monitoring namespace to get access to the secret with etcd cert and configmaps with bundle.

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-cluster
  namespace: openshift-monitoring
spec:
  configMaps:
  - serving-certs-ca-bundle
  - kubelet-serving-ca-bundle
  nodeScrapeSelector: {}
  podScrapeSelector: {}
  probeSelector: {}
  remoteWrite:
  - url: http://vmsingle-vmsingle-pvc.openshift-operators.svc:8429/api/v1/write
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 850Mi
    requests:
      cpu: 250m
      memory: 350Mi
  secrets:
  - kube-etcd-client-certs
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  staticScrapeSelector: {}
```

 Also, you have to create additional rbac for metrics access: 
 These permissions will be included to the next release.
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-vmagent-cluster-mon
rules:
- apiGroups:
  - ""
  resources:
  - namespace/metrics
  verbs:
  - get
- nonResourceURLs:
      - "/metrics"
      - "/metrics/resources"
  verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-vmagent-cluster-mon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-vmagent-cluster-mon
subjects:
- kind: ServiceAccount
  name: vmagent-vmagent-cluster
  namespace: openshift-monitoring
```

**Comment by fatowl-github** [comment]
@f41gh7 @sergsmirnoff 

Hi, Nikolay. Thank you a lot! It works well. But is it enough to scrape targets only within openshift-monitoring namespace for full platform monitoring like embedded prometheus does? I'm not sure, but we get messages

  error	VictoriaMetrics/lib/promscrape/scrapework.go:258	error when scraping "https://172.19.21.215:9001/metrics" from job "machine-config-daemon" with labels {endpoint="metrics",instance="172.19.21.215:9001",job="machine-config-daemon",namespace="openshift-machine-config-operator",pod="machine-config-daemon-c8d8h",prometheus="openshift-monitoring/vmagent-cluster",service="machine-config-daemon"}: unexpected status code returned when scraping "https://172.19.21.215:9001/metrics": 403; expecting 200; response body: "\n<!DOCTYPE html>\n<html lang=\"en\" charset=\"utf-8\">\n<head>\n  <title>Log In</title>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\n  <style>\n    @font-face {\n      font-family: \"Open Sans\";\n      src: url(data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAAFeoABMAAAAAlkQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABqAAAABwAAAAcavCZq0dERUYAAAHEAAAAHQAAAB4AJwD1R1BPUwAAAeQAAASjAAAJni1yF0JHU1VCAAA...

"error when scraping" from other namespaces than openshift-monitoring. As it looks for me now, I have to run some vmagents in the appropriate namespaces for a complete replacement of platform prometheus. Am I correct?

**Comment by f41gh7** [comment]
These selectors: 
```
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
```

  Allows to scrape data from all `ServiceMonitors`/ `VMServiceScrapes` at cluster scope.

 The only reason for placing `VMAgent` to the `openshift-monitor` namespace - secrets and configmaps from prometheus. 

  I'm not sure, `machine-config-daemon-c8d8h` - looks like some system service, maybe it requires additional permissions.  

 I suggest to try following cluster role:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-openshift-resources
rules:
- apiGroups:
  - route.openshift.io
  - image.openshift.io
  resources:
  - routers/metrics
  - registry/metrics
  verbs:
  - get
- nonResourceURLs:
      - "/metrics"
      - "/metrics/resources"
  verbs:
      - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

```
