### ISSUE TITLE
how to configure remote white label for all metrics?

### ISSUE THREAD

**Issue by fatowl-github** [VictoriaMetrics/operator#234]
Hello 
We have a configuraton with VMAgent in OpenShift cluster and RemoteWrite to the external  VictoriaMetrics. How can we configure VMAgent in OpenShift for labelling all metrics passed to the external  VictoriaMetrics via RemoteWhite (for example adding new label clusterid=some_cluster)? I think we have to create ConfigMap for -remoteWrite.relabelConfig file . But at the present time it doesn't work . What should we write in this config?
Thank you a lot

**Comment by f41gh7** [comment]
Hello!

  Since `v0.14.1` vmagent supports two options for relabling config (inline and configmap), related doc: https://github.com/VictoriaMetrics/operator/blob/master/docs/relabeling.MD

 In your case, try to define following spec:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: stack
spec:
 # this is global relabeling, applied to all remoteWrite urls.
  inlineRelabelConfig:
  - replacement: some_cluster
    target_label: clusterid
  remoteWrite:
 - url: http://vmsingle-stack-victoria-metrics-k8s-stack.default.svc:8429/api/v1/write
   inlineUrlRelabelConfig:
   # relabeling for specific remoteWrite
   - target_label: dst_rw
     replacement: some_dstid
```

  But probably, you don't need relabeling? 

 Try to use external labels, it will be added to all scraped metrics, but not for pushed metrics to agent.

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: stack
spec:
  externalLabels:
    clusterid: some_cluster
  remoteWrite:
 - url: http://vmsingle-stack-victoria-metrics-k8s-stack.default.svc:8429/api/v1/write

```
