### ISSUE TITLE
About Rule tenant

### ISSUE THREAD

**Issue by ALEX-yinhao** [VictoriaMetrics/operator#237]
Now I want to manage alert rules for every tenant. I find vmalert start with configure `-rule=alert.rules`. so here have some problems:
1. Should every one of tenant have a vmalert with config `-rule=tenant.rules`?
2. The alert rules is not configmap or secret in pod now(or maybe I am not read carefully),so how to add a configmap(or secret) for vmalert, and if I add a new rule how to make vmalert reload?

Here is my questions, please help me ,
Looking forward to your reply, thank you.

**Comment by f41gh7** [comment]
Hello, 
 per tenant alert rules soon will be supported by enterprise version of vmalert. It would be possible to configure it with following syntax: 

```yaml
groups:
  - name: TestGroup-1
    interval: 2s
    tenant:
      account_id: 5
      project_id: 11
    concurrency: 2
    type: graphite
    rules:
      - alert: Conns
        expr: filterSeries(sumSeries(host.receiver.interface.cons),'last','>', 500)
        for: 3m
        annotations:
          summary: Too high connection number for {{$labels.instance}}
          description: "It is {{ $value }} connections for {{$labels.instance}}"
  - name: TestGroup-2
    interval: 2s
    tenant:
      account_id: 5
      project_id: 15
    concurrency: 2
    type: graphite
    rules:
      - alert: Conns
        expr: filterSeries(sumSeries(host.receiver.interface.cons),'last','>', 500)
        for: 3m
        annotations:
          summary: Too high connection number for {{$labels.instance}}
          description: "It is {{ $value }} connections for {{$labels.instance}}"
```
 As soon, as it will be ready at vmalert, support for it will be added to the operator as well. 

 Not sure, when it will be at open-source.
