### ISSUE TITLE
feature request: support using hostpath as VMSingle's storage

### ISSUE THREAD

**Issue by NOBLES5E** [VictoriaMetrics/operator#240]

**Comment by f41gh7** [comment]
Hello, try to use following config:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: demo
spec:
  volumeMounts:
    - name: storage
      mountPath: /hp_data_dir
  volumes:
    - name: storage
      hostPath:
        path: /data
        type: DirectoryOrCreate
  extraArgs:
    storageDataPath: /hp_data_dir
```

**Comment by NOBLES5E** [comment]
Hi @f41gh7 , thanks for your suggestion. It seems that the config doesn't work. I investigated the actual container created, and the args looks like this:

![image](https://user-images.githubusercontent.com/18649508/117562089-1a98e780-b051-11eb-82f4-68bd28bc14f2.png)

There is a `'-storageDataPath=/victoria-metrics-data'` argument appended by default and maybe that overrides the `extraArgs` in the config?

**Comment by NOBLES5E** [comment]
It seems that vmsingle always use a hardcoded path in the arguments here so that `extraArgs` will never be able to override them: https://github.com/VictoriaMetrics/operator/blob/master/controllers/factory/vmsingle.go#L173

**Comment by f41gh7** [comment]
Sorry, my bad, i forgot about args sorting. This one must work:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: demo
spec:
  volumeMounts:
    - name: storage
      mountPath: /zhp_data_dir
  volumes:
    - name: storage
      hostPath:
        path: /data
        type: DirectoryOrCreate
  extraArgs:
    storageDataPath: /zhp_data_dir
```

 Any way, it looks bad. I'm thinking about new param - `spec.storageDataPath`, which will disable PVC creation and define value for arg `storageDataPath`.

**Comment by f41gh7** [comment]
`spec.storageDataPath` was added to the master branch. With it following syntax can be used:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: demo
spec:
  retentionPeriod: "1d"
  volumeMounts:
    - name: storage
      mountPath: /vm-data
  volumes:
    - name: storage
      hostPath:
        path: /data
        type: DirectoryOrCreate
  storageDataPath: /vm-data
```

 It will be included into next release.
