### ISSUE TITLE
VMAuth support as CRD

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#245]
Linked issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1194

 I propose to define following CRDS:

1) `VMUser` - which describes user access ( read/write, forward url? ).
2) `VMAuth` - which handles vmauth and selects needed `VMUsers`

 Any ideas are welcome.

**Comment by jtyr** [comment]
@f41gh7 `vmauth`has support for `/-/reload` in the release v1.6.0. Will the next Operator release have CRD for `vmauth`? :wink:

**Comment by f41gh7** [comment]
Yes, currently working on it. At first look, it will be possible to expos any application with `VMUser`. 

Something like:

``` yaml
kind: VMUser
metadata:
  name: access-cluster
spec:
  # if omitted - metadata.name - username
  # username: some-user
  # if omitted - auto-generated.
  # password: Some-password
  # bearerToken: some-token
  targetRefs:
    # one of - crd or static.
    - crd:
        kind: VMAgent
        namespace: ns-name
        name: vmagent-name
      #static: 
      #  url: http://10.10.233.10:8482
      paths:
      - /targets
      - /api/v1/targets
    - static:
         url: http://vmsingle
      paths:
       - '/'
  # some ingress related config.
  ingress: {}
```

**Comment by f41gh7** [comment]
Basic `VMAuth` and `VMUser` support was merged. Can you check does it work for you? 

 Related documentation:
  quick start: https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#VMAuth
  api docs: https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmauthspec
 how to install from master: 
https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#installing-by-kustomize 
 with `VM_VERSION=master`.

 If any bugs or design problems will be found, feel free to add it to this issue.

**Comment by jtyr** [comment]
I'm wondering how to translate the following `VMAUTH` config into a `VMUser` definition:

```yaml
config:
  users:
    - username: myuser
      password: mypassword
      url_map:
        - src_paths:
            - /api/v1/write
          url_prefix: http://vminsert-vmcluster:8480/insert/123456/prometheus
        - src_paths:
            - /api/v1/query
            - /api/v1/query_range
            - /api/v1/label/[^/]+/values
          url_prefix: http://vmselect-vmcluster:8481/select/123456/prometheus
```

Does [this example](https://github.com/VictoriaMetrics/operator/blob/master/config/examples/vmusers.yaml#L18-L32) accept any password for the username `simple-user-1`? For example if I would authenticate the user via Ingress?

**Comment by f41gh7** [comment]
something like: 
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser-sample-1
spec:
  username: simple-user-1
  targetRefs:
    - static:
        url: http://vminsert-vmcluster:8480/insert/123456/prometheus
      paths:
      - /api/v1/write
    - static:
        url: http://vmselect-vmcluster:8481/select/123456/prometheus
      paths:
       - /api/v1/query
       - /api/v1/query_range
       - /api/v1/label/[^/]+/values
``` 

 It will generate following config:
```yaml
users:
- url_map:
  - url_prefix: http://vminsert-vmcluster:8480/insert/123456/prometheus
    src_paths:
    - /api/v1/write
  - url_prefix: http://vmselect-vmcluster:8481/select/123456/prometheus
    src_paths:
    - /api/v1/query
    - /api/v1/query_range
    - /api/v1/label/[^/]+/values
  username: simple-user-1
```

  At basic auth is possible to have empty password. So If `spec.password` is empty and `spec.generatePassword` is false, `vmauth` authes requests with empty password, like: 
```curl localhost:8427/api/v1/query -u 'simple-user-1:' -v```

 If you also want to terminate basic auth at non-VMAuth ingress, add correct `spec.username` and `spec.password` into `VMUser` definition.


 Its also possible to define `spec.ingress`  at `VMAuth` and operator will create corresponding `ingress` object.

**Comment by f41gh7** [comment]
Also, i just realized, that `targetRef` definition misses ability to specify tenant  route. Probably, `pathPrefix` would be able to solve it. For example:
```yaml
targetRefs:
- crd:
     kind: VMCluster/vminsert
     name: some-name
     namespace: default
  pathPrefix: "/insert/0/prometheus"
  paths: 
  - /api/v1/write
```

 It will produce url_prefix: `http://vminsert-some-name.default.svc:8480/insert/0/prometheus`

**Comment by jtyr** [comment]
Thanks for the example of the `targetRefs`. I wasn't sure if I can use multiple `crd` or `static` statements as the [documentation](https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#targetref) is mentioning *"**one** of crd or static can be configured per targetRef"*. Perhaps fixing the doc and add an example with multiple `crd` and/or `static` statements would be beneficial for users like me.

It would be cool if I could use `Ingress` on the *VMAUTH* level for basic auth (like [multi-tenant Grafana Loki](https://grafana.com/docs/loki/latest/operations/authentication/) does it). Basically the basic auth is done on the `Ingress` level via Ingress annotations and if the auth passes, it automatically adds an extra HTTP header that could then be used on the *VMAUTH* level to produce the desired URL. That could reduce the number of `VMUser` definitions to just one!

Ingress annotations:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  ...
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: mysecret
    ingress.kubernetes.io/auth-header-field: X-Scope-OrgID
...
```

`VMUser` definition:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser-universal
spec:
  authHeaderField: X-Scope-OrgID
  targetRefs:
    - static:
        url: http://vminsert-vmcluster:8480/insert/{{ authHeaderField }}/prometheus
      paths:
      - /api/v1/write
    - static:
        url: http://vmselect-vmcluster:8481/select/{{ authHeaderField }}/prometheus
      paths:
       - /api/v1/query
       - /api/v1/query_range
       - /api/v1/label/[^/]+/values
```

If that's would be too difficult to implement then another option would be to add `password_file` that would allow to load the password from a `Secret` mounted into *VMAUTH*:

`Secret` with username/password pairs:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  myuser1: cGFzc3dvcmQ=
```

`VMUser` definition:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser-universal
spec:
  username: myuser1
  password_file: /path/to/my/mysecret/myuser1
  targetRefs:
    - static:
        url: http://vminsert-vmcluster:8480/insert/123456/prometheus
      paths:
      - /api/v1/write
    - static:
        url: http://vmselect-vmcluster:8481/select/123456/prometheus
      paths:
       - /api/v1/query
       - /api/v1/query_range
       - /api/v1/label/[^/]+/values
```

`VMAuth` definition:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: myvmauth
spec:
  ...
  secrets:
    - mysecret
  ...
```

The benefit of having passwords in a `Secret` is that we can use external secret manager (e.g. [Kubernetes External Secrets](https://github.com/external-secrets/kubernetes-external-secrets)) and keep the password (using `Secret`) separate from the configuration (using `ConfigMap`).

**Comment by f41gh7** [comment]
Sorry for bad docs, i'll update it. 

 
1) For now `vmath` supports only env_var templating for configuration file. Header based templating makes it more complicated and less reliable. Probably, its better to implement it for `vmgateway` as part of enterprise package.

2) `password_file` looks interesting, but it requires changes at vmauth side. One more problem - unpredictable updates for such secrets, its not possible to force configuration changes as soon as secret was changed. 

 As alternative solution, its possible to implement reference for password secret at `VMUser` definition.

```yaml
kind: VMUser
spec:
   passwordRef:
        key: myuser1
        name: mysecret
```

 Secret will be retrieved and stored at vmauth configuration secret. As soon as it will be update, vmauth configuration will be changed as well and reloaded.

**Comment by jtyr** [comment]
If `password_file` would be added, you could [watch for changes](https://github.com/fsnotify/fsnotify) of the secret file and reload the config if the file changes.

Adding `passwordRef` would be also OK.

**Comment by f41gh7** [comment]
> If `password_file` would be added, you could [watch for changes](https://github.com/fsnotify/fsnotify) of the secret file and reload the config if the file changes.
> 
> Adding `passwordRef` would be also OK.

-  For now `password_file` requires additional work at `vmauth` side. I will create feature request for it.

-  `passwordRef` was added.

- `VMAuth` and `VMUser` was included to the 0.15.0 release. Any feedback are welcome.

**Comment by lukasmrtvy** [comment]
@f41gh7 would be possible to add support for `target_path_suffix` to this CRD? With this it would be possible to set `target_path_suffix: "/insert/0/prometheus"` 

Thanks

**Comment by f41gh7** [comment]
> @f41gh7 would be possible to add support for `target_path_suffix` to this CRD? With this it would be possible to set `target_path_suffix: "/insert/0/prometheus"`
> 
> Thanks

Added to the 0.17.1 release

**Comment by lukasmrtvy** [comment]
Hey, here is another feedback:

- VMUser has wrong default version value ( should be 1.63.0 ) https://github.com/VictoriaMetrics/operator/blob/master/internal/config/config.go#L189
- VMAuth CR is not deleted by operator ( some reconciliation bug )
- VMUser/VMAuth should support no authentication ( if username and password, passwordRef, generatePassword, bearerToken  are not sett ). I have use case, where I need to forward authentication for /vmui path ( for users ) to oauth proxy and at the same time use static credentials for /api/v1/write path ( for technical users )

Thanks

**Comment by flokli** [comment]
I'm not sure about the state of this issue, but I'm still unsure about how to use this with a vmcluster, and how to specify the tenant.

Maybe the docs need some updating on how to use it/an example with vmcluster?

**Comment by flokli** [comment]
So I was able to create a VMUser jailing a user into an individual tenant, and restricting to the prometheus remote_write interface with the folllowing `VMUser` config:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: user1
  namespace: default
spec:
  generatePassword: true
  targetRefs:
  - crd:
      kind: VMCluster/vminsert
      name: vmcluster
      namespace: default
    paths:
    - /prometheus/api/v1/write
    target_path_suffix: /insert/0
  username: user1
```

So does this mean once we add something like this to the docs, the issue can be closed?
