### ISSUE TITLE
Add nodeSelector to spec

### ISSUE THREAD

**Issue by stress-t** [VictoriaMetrics/operator#254]
Now vmoperator support nodeAffinity
```
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: vminsert
              operator: In
              values:
              - "true"
```
nodeSelector more simply for associating to nodes with labels
```
  nodeSelector:
    vminsert: true
```
