### ISSUE TITLE
Log level doesn't change when args are passed in

### ISSUE THREAD

**Issue by Blargansmarf** [VictoriaMetrics/operator#281]
Setting `--zap-log-level=error` and `--loggerLevel=ERROR` don't actually change the level of logs. It always defaults to INFO level. Deployment yaml included below, please let me know if i'm just dumb about this.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
      app.kubernetes.io/instance: victoria-metrics-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: victoria-metrics-operator
        app.kubernetes.io/instance: victoria-metrics-operator
    spec:
      nodeSelector: {{ .Values.defaultNodeSelector | toYaml | nindent 8 }}
      serviceAccountName: victoria-metrics-operator
      containers:
        - name: victoria-metrics-operator
          image: {{ .Values.vmoperator.image.repository }}:{{ .Values.vmoperator.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: victoria-metrics-operator
          args:
            - --zap-log-level=error
            - --loggerLevel=ERROR
          command:
            - manager
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 2
              memory: 2Gi
```
