### ISSUE TITLE
Prom rules are being interpreted as templates!

### ISSUE THREAD

**Issue by kaihendry** [VictoriaMetrics/operator#295]
Hi, I have my rules in a separate directory, linted like so:

```
for rules in rules/*.yml
do
	yamllint $rules
	docker run -v $(pwd)/rules:/rules -i --rm --entrypoint=promtool prom/prometheus check rules /rules/$(basename $rules)
done
```

https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD
Now I have trying for a long while to include the rules into my VMrule, like so

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ printf "%s-%s" (include "alert.fullname" $) "awslimits" | trunc 63 | trimSuffix "-" }}
  labels: {{ include "alert.labels" $ | nindent 4 }}
spec:
  {{ .Files.Get "rules/awslimits.yml" | indent 2 }}

```

But it keeps failing like so:

AML parse error on alert/templates/alerts/awslimits.yml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"AWS service: {{ $labels.aws_service }} usage on account:{{ $labels.aws_account }} is....":interface {}(nil)}

This is because my rules contain Grafana templates. Now if escape using ` around the string, I get:

Error: UPGRADE FAILED: YAML parse error on alert/templates/alerts/awslimits.yml: error converting YAML to JSON: yaml: line 22: found character that cannot start any token

So I am really unsure how to proceed. When converting it into a string I get the error:

    spec in body must be of type object: "string"
