### ISSUE TITLE
Operator OOM on startup

### ISSUE THREAD

**Issue by FRosner** [VictoriaMetrics/operator#297]
# Problem Summary

Operator getting stuck on startup, leaking memory until getting OOM killed.

# Details

I tried installing the operator through the helm chart like so:

```bash
helm upgrade --install victoria-metrics-operator vm/victoria-metrics-operator --version 0.1.17 -f victoria-metrics-operator/values.yaml
```

```yaml
image:
  # -- Image repository
  repository: victoriametrics/operator
  # -- Image tag
  tag: v0.16.0
  # -- Image pull policy
  pullPolicy: IfNotPresent

# -- enables CRD creation and management.
# -- with this option, if you remove this chart, all crd resources will be deleted with it.
createCRD: true

replicaCount: 1

# -- Secret to pull images
imagePullSecrets: []

# -- VM operatror deployment name override
nameOverride: ""

# -- Overrides the full name of server component
fullnameOverride: ""

# -- VM operator log level
# -- possible values: info and error.
logLevel: "info"

rbac:
  # -- Specifies whether the RBAC resources should be created
  create: true
  pspEnabled: true

# -- Labels to be added to the all resources
extraLabels: {}
# -- Annotations to be added to the all resources
annotations: {}

securityContext:
  {}
operator:
  # -- We're running alongside prometheus operator so let's be safe rather than sorry
  disable_prometheus_converter: true
  # -- By default, operator creates psp for its objects.
  psp_auto_creation_enabled: true
  # -- Enables ownership reference for converted prometheus-operator objects,
  # it will remove corresponding victoria-metrics objects in case of deletion prometheus one.
  enable_converter_ownership: false
  # -- Enables custom config-reloader, bundled with operator.
  # It should reduce  vmagent and vmauth config sync-time and make it predictable.
  useCustomConfigReloader: false


serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 2000m
    memory: 4Gi

# -- Pod's node selector. Ref: [https://kubernetes.io/docs/user-guide/node-selection/](https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector:
  worker-group: monitor

# -- Array of tolerations object. Ref: [https://kubernetes.io/docs/concepts/configuration/assign-pod-node/](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/)
tolerations: []

# -- Pod affinity
affinity: {}

# -- extra settings for the operator deployment. full list Ref: [https://github.com/VictoriaMetrics/operator/blob/master/vars.MD](https://github.com/VictoriaMetrics/operator/blob/master/vars.MD)
env: []
  # - name: VM_VMSINGLEDEFAULT_VERSION
  #   value: v1.43.0

# -- Additional hostPath mounts
extraHostPathMounts:
  []
  # - name: certs-dir
  #   mountPath: /etc/kubernetes/certs
  #   subPath: ""
  #   hostPath: /etc/kubernetes/certs
#   readOnly: true

# -- Extra Volumes for the pod
extraVolumes:
  []
  # - name: example
  #   configMap:
  #     name: example

# -- Extra Volume Mounts for the container
extraVolumeMounts:
  []
  # - name: example
  #   mountPath: /example

extraContainers:
  []
  # - name: config-reloader
  #   image: reloader-image

# -- Configures resource validation
admissionWebhooks:
  # -- Enables validation webhook.
  enabled: false
  # -- What to do in case, when operator not available to validate request.
  policy: Fail
  # -- Enables custom ca bundle, if you are not using cert-manager.
  # -- in case of custom ca, you have to create secret - {{chart-name}}-validation
  # -- with keys: tls.key, tls.crt, ca.crt
  caBundle: ""
  certManager:
    # -- Enables cert creation and injection by cert-manager.
    enabled: false
    # --If needed, provide own issuerName. Operator will create self-signed if empty.
    issuerName: ""
```

It starts and logs the following:

```
{"level":"info","ts":1627557351.7818878,"logger":"setup","msg":"Registering Components."}
{"level":"info","ts":1627557352.7398546,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1627557353.8666544,"logger":"setup","msg":"starting vmconverter clients"}
{"level":"info","ts":1627557353.8668861,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1627557353.8670187,"msg":"attempting to acquire leader lease monitor/57410f0d.victoriametrics.com...\n"}
2021-07-29T11:15:53.867Z    info    VictoriaMetrics@v1.60.0/lib/httpserver/httpserver.go:82    starting http server at http://:8435/
2021-07-29T11:15:53.867Z    info    VictoriaMetrics@v1.60.0/lib/httpserver/httpserver.go:83    pprof handlers are exposed at http://:8435/debug/pprof/
{"level":"info","ts":1627557353.8671117,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1627557371.3978498,"msg":"successfully acquired lease monitor/57410f0d.victoriametrics.com\n"}
{"level":"info","ts":1627557371.3980455,"logger":"controller_vmcluster","msg":"starting prometheus converter"}
{"level":"info","ts":1627557371.3980982,"logger":"controller_vmcluster","msg":"waiting for prometheus converter to stop"}
{"level":"info","ts":1627557371.3981555,"logger":"controller-runtime.manager.controller.vmnodescrape","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMNodeScrape","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3982255,"logger":"controller-runtime.manager.controller.vmnodescrape","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMNodeScrape"}
{"level":"info","ts":1627557371.3982031,"logger":"controller-runtime.manager.controller.vmuser","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMUser","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3982372,"logger":"controller-runtime.manager.controller.vmuser","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMUser","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3982453,"logger":"controller-runtime.manager.controller.vmuser","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMUser"}
{"level":"info","ts":1627557371.3983133,"logger":"controller-runtime.manager.controller.vmpodscrape","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMPodScrape","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3983665,"logger":"controller-runtime.manager.controller.vmpodscrape","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMPodScrape"}
{"level":"info","ts":1627557371.3983824,"logger":"controller-runtime.manager.controller.vmsingle","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3984737,"logger":"controller-runtime.manager.controller.vmsingle","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3984401,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3984978,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985193,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398501,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398526,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985302,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985517,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985603,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398569,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985777,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985848,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398534,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985915,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3985918,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3984866,"logger":"controller-runtime.manager.controller.vmsingle","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3986382,"logger":"controller-runtime.manager.controller.vmalert","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlert"}
{"level":"info","ts":1627557371.39865,"logger":"controller-runtime.manager.controller.vmsingle","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3986614,"logger":"controller-runtime.manager.controller.vmsingle","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3986077,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398688,"logger":"controller-runtime.manager.controller.vmsingle","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398642,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3986638,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987126,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987212,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987281,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987367,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398742,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987226,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987496,"logger":"controller-runtime.manager.controller.vmalertmanager","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAlertmanager"}
{"level":"info","ts":1627557371.3987544,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398757,"logger":"controller-runtime.manager.controller.vmsingle","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle"}
{"level":"info","ts":1627557371.3987403,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987513,"logger":"controller-runtime.manager.controller.vmrule","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMRule","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987825,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3987865,"logger":"controller-runtime.manager.controller.vmrule","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMRule"}
{"level":"info","ts":1627557371.39879,"logger":"controller-runtime.manager.controller.vmagent","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent"}
{"level":"info","ts":1627557371.3987627,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398816,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398834,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3988404,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3988464,"logger":"controller-runtime.manager.controller.vmcluster","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster"}
{"level":"info","ts":1627557371.3988132,"logger":"controller-runtime.manager.controller.vmservicescrape","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMServiceScrape","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3988664,"logger":"controller-runtime.manager.controller.vmservicescrape","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMServiceScrape"}
{"level":"info","ts":1627557371.3988621,"logger":"controller-runtime.manager.controller.vmstaticscrape","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMStaticScrape","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3988883,"logger":"controller-runtime.manager.controller.vmstaticscrape","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMStaticScrape"}
{"level":"info","ts":1627557371.3989315,"logger":"controller-runtime.manager.controller.vmprobe","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMProbe","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.398961,"logger":"controller-runtime.manager.controller.vmprobe","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMProbe"}
{"level":"info","ts":1627557371.3990445,"logger":"controller-runtime.manager.controller.vmauth","msg":"Starting EventSource","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAuth","source":"kind source: /, Kind="}
{"level":"info","ts":1627557371.3990774,"logger":"controller-runtime.manager.controller.vmauth","msg":"Starting Controller","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAuth"}
```

Then it gets stuck and starts using more and more memory very quickly until it gets OOM killed. I deployed the same config on AKS and it worked. This one is on GKE. Not sure if this is relevant.

The Kubernetes node reports the following:

```
Warning  SystemOOM         59s                  kubelet         System OOM encountered, victim process: manager, pid: 3078033
Warning  OOMKilling        59s                  kernel-monitor  Memory cgroup out of memory: Killed process 3078033 (manager) total-vm:5218744kB, anon-rss:4180628kB, file-rss:27268kB, shmem-rss:0kB, UID:1001 pgtables:8356kB oom_score_adj:-998 
```
