### ISSUE TITLE
Operator fails to init because it can't list CRDs

### ISSUE THREAD

**Issue by Blargansmarf** [VictoriaMetrics/operator#301]
Operator version: v0.17.2
Kube version: 1.11

Logs:
```
{"level":"error","ts":1628548352.583489,"logger":"setup","msg":"unable to init crd data","error":"cannot list CRDs during init: no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1\"","stacktrace":"github.com/VictoriaMetrics/operator/internal/manager.RunManager\n\tgithub.com/VictoriaMetrics/operator/internal/manager/manager.go:101\nmain.main\n\tcommand-line-arguments/main.go:41\nruntime.main\n\truntime/proc.go:225"}
{"level":"error","ts":1628548352.5836086,"logger":"setup","msg":"cannot setup manager","error":"cannot list CRDs during init: no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1\"","stacktrace":"main.main\n\tcommand-line-arguments/main.go:43\nruntime.main\n\truntime/proc.go:225"}
```

clusterrole config:
```
...

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io/v1
  resources:
  - CustomResourceDefinition
  verbs:
  - '*'
```

I'm suspecting that my Kube version is too out of date for this or that I'm not configuring permissions in my clusterrole appropriately.
