### ISSUE TITLE
per job scrape_intervals/align/offset

### ISSUE THREAD

**Issue by ThomasADavis** [VictoriaMetrics/operator#303]
You can set a global scrape interval for a VMagent, but you can't set a scrape interval for pods, services, and other types in the operator.  VMagent does support a per-job scrape_interval, scrape_align_interval, and scrape_offset.

I have several pods/services that need to be scraped at different intervals due to API limits, and this can not be currently configured in the VMServiceScrape/VMPodscrape/VMNodescrape/VMProbescrapes CRD's.

This is desired to keep from running multiple VMAgents.

**Comment by f41gh7** [comment]
Hello, scrape internal can be configured with `interval` param at https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#endpoint, for instance:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: example-scrape
spec:
  endpoints:
    - port: http
      targetPort: http
      path: /metrics
      scheme: http
      interval: 10s
      scrapeTimeout: 2s
  namespaceSelector:
    any: false
    matchNames: ["kube-system"]
  selector:
    matchLabels:
      app.kubernetes.io/name: example-application
```

 Scrape offset and scrape aling interval will be added, thanks for pointing! Also, i would like to add scrape_interval to make it more consistent with scrape configuration.

 To be honest, i dislike prometheus-operator decision to use camel case for its apis, while prometheus uses snake case.  Its really confusing.

**Comment by ThomasADavis** [comment]
Didn't think about looking in the endpoint.

And yes, the case case stuff just sucks..

**Comment by f41gh7** [comment]
Now, all scrape components `VMServiceScrape`, `VMPodScrape`, `VMNodeScrape`, `VMProbes` and `VMStaticScrape` supports additional params: `vm_scrape_params` https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmscrapeparams.

  Example of usage: 
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: vmauth-sample
    app.kubernetes.io/name: vmauth
  name: vmauth-vmauth-sample
  namespace: default
spec:
  endpoints:
  - path: /metrics
    port: http
    vm_scrape_params:
      scrape_offset: 1s
      stream_parse: true
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmauth-sample
      app.kubernetes.io/name: vmauth
```

 Need to update documentation for it and add more examples.
