### ISSUE TITLE
vm cr apply failed

### ISSUE THREAD

**Issue by Cosrider** [VictoriaMetrics/operator#316]
#### error:  
        VMAgent.operator.victoriametrics.com "vmagent" is invalid: [spec.containers.name: Required value, spec.volumes.name: Required value

#### vm-operator version: 
      v0.18.0 ,  crd version has just upgraded  from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1 

#### cr configs
cannot apply cr, when  cr containers  is configed; for example:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  containers:
    - args:
        - -httpListenAddr=:8429
        - -promscrape.config=/etc/vm/configs/prometheus.yaml.gz
        - -remoteWrite.maxDiskUsagePerURL=1073741824
        - -remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data
        - -promscrape.suppressDuplicateScrapeTargetErrors=true
        - -remoteWrite.url=http://vminsert-vmcluster.monitoring.svc:8480/insert/0/prometheus/api/v1/write
      name: vmagent
      volumeMounts:
        - mountPath: /etc/vm/configs
          name: configmap-prometheus-config
          readOnly: true
  volumes:
    - configMap:
        defaultMode: 420
        name: prometheus-config
      name: configmap-prometheus-config
```

**Comment by Cosrider** [comment]
https://github.com/VictoriaMetrics/operator/pull/317

**Comment by Cosrider** [comment]
crd need support unknown field

**Comment by f41gh7** [comment]
Hello, thanks for reporting, its an issue with CRD generation. To make CRD definition lightweight, some fields are removed from validation, such as `volumes` properties. For instance, `name` is required, but there is no `name` definition at `items` properties.

```yaml
              volumes:
                description: Volumes allows configuration of additional volumes on
                  the output deploy definition. Volumes specified will be appended
                  to other volumes that are generated as a result of StorageSpec objects.
                items:
                  description: Volume represents a named volume in a pod that may
                    be accessed by any container in the pod.
                  required:
                  - name
                  type: object
                type: array
```

 Possible fixes: remove `required` section or add `required` properties.

 I will fix it soon.
