### ISSUE TITLE
VMCluster embedded hpa fields are dropped

### ISSUE THREAD

**Issue by ebensom** [VictoriaMetrics/operator#321]
Hi @f41gh7 ,

The vmselect/vminsert subcomponents' embedded `hpa` field is dropped. 
Maybe it's related to https://github.com/VictoriaMetrics/operator/issues/316 so the [definitions](https://github.com/VictoriaMetrics/operator/blob/master/config/crd/bases/operator.victoriametrics.com_vmclusters.yaml#L151-L154) seems to miss the `x-kubernetes-preserve-unknown-fields: true` attribute?

Example CR:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: foo
  namespace: bar
spec:
  clusterVersion: v1.64.1-cluster
  replicationFactor: 2
  retentionPeriod: 60d
  vminsert:
    hpa:
      behaviour:
        scaleDown:
          policies:
          - periodSeconds: 60
            type: Percent
            value: 50
          stabilizationWindowSeconds: 300
        scaleUp:
          policies:
          - periodSeconds: 60
            type: Percent
            value: 50
          stabilizationWindowSeconds: 60
      maxReplicas: 6
      metrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 125
            type: Utilization
        type: Resource
      minReplicas: 2
    nodeSelector:
      pool-type: mgmt
    podDisruptionBudget:
      maxUnavailable: 1
    podMetadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels: {}
    replicaCount: 2
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 256Mi
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: foo
          app.kubernetes.io/name: vminsert
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    updateStrategy: RollingUpdate
  vmselect:
    cacheMountPath: /select-cache
    extraArgs:
      [...]
    hpa:
      behaviour:
        scaleDown:
          policies:
          - periodSeconds: 60
            type: Pods
            value: 2
          stabilizationWindowSeconds: 300
        scaleUp:
          policies:
          - periodSeconds: 60
            type: Pods
            value: 1
          stabilizationWindowSeconds: 180
      maxReplicas: 6
      metrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 100
            type: Utilization
        type: Resource
      minReplicas: 2
    nodeSelector:
      pool-type: mgmt
    podDisruptionBudget:
      maxUnavailable: 1
    podMetadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels: {}
    replicaCount: 2
    resources:
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi
    serviceSpec:
      metadata:
        name: vmselect-skr-ilb
      spec:
        type: ClusterIP
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: premium-rwo
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: foo
          app.kubernetes.io/name: vmselect
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  vmstorage:
    nodeSelector:
      pool-type: mgmt
    podDisruptionBudget:
      maxUnavailable: 1
    podMetadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels: {}
    replicaCount: 6
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 150m
        memory: 512Mi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Ti
          storageClassName: standard-rwo
    storageDataPath: /vm-data
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: foo
          app.kubernetes.io/name: vmstorage
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
```

CR obtained after apply with `kubectl get`:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: foo
  namespace: bar
spec:
  clusterVersion: v1.64.1-cluster
  replicationFactor: 2
  retentionPeriod: 60d
  vminsert:
    hpa: {}
    image: {}
    nodeSelector:
      pool-type: mgmt
    podDisruptionBudget:
      maxUnavailable: 1
    podMetadata:
      annotations:
        sidecar.istio.io/inject: "false"
    replicaCount: 2
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 256Mi
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: foo
          app.kubernetes.io/name: vminsert
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    updateStrategy: RollingUpdate
  vmselect:
    cacheMountPath: /select-cache
    extraArgs:
      search.maxQueryDuration: 60s
      search.maxQueueDuration: 30s
    hpa: {}
    image: {}
    nodeSelector:
      pool-type: mgmt
    podDisruptionBudget:
      maxUnavailable: 1
    podMetadata:
      annotations:
        sidecar.istio.io/inject: "false"
    replicaCount: 2
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi
    serviceSpec:
      metadata:
        name: vmselect-skr-ilb
      spec: {}
    storage:
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: premium-rwo
        status: {}
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: foo
          app.kubernetes.io/name: vmselect
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  vmstorage:
    image: {}
    nodeSelector:
      pool-type: mgmt
    podDisruptionBudget:
      maxUnavailable: 1
    podMetadata:
      annotations:
        sidecar.istio.io/inject: "false"
    replicaCount: 6
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 150m
        memory: 512Mi
    storage:
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: 1Ti
          storageClassName: standard-rwo
        status: {}
    storageDataPath: /vm-data
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: foo
          app.kubernetes.io/name: vmstorage
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
```
