### ISSUE TITLE
missing `honorLabels` for VMServiceScrape

### ISSUE THREAD

**Issue by schmurfy** [VictoriaMetrics/operator#324]
`honorLabels` is present for almost every scraper config except this one.

**Comment by f41gh7** [comment]
Hello, it must  present at `Endpoint` which is part of `VMServiceScrape` https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#endpoint

 for instance:

```

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: example-scrape
spec:
  discoveryRole: "endpoints"
  jobLabel: job
  targetLabels: []
  podTargetLabels: []
  endpoints:
    - port: http
      targetPort: http
      path: /metrics
     honorLabels: true
      scheme: http
      scrapeTimeout: 2s
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app.kubernetes.io/name: example-application
      monitored-by: vm-operator
```

 If its not, it may be some bug.
