### ISSUE TITLE
VMAgent config is regenerated continuously when a scrape selector includes multiple labels

### ISSUE THREAD

**Issue by silverlyra** [VictoriaMetrics/operator#325]
I’m running the latest-released operator (0.18.2), and I noticed that the operator is updating the `Secret` holding my `VMAgent` configuration constantly – multiple times per second. It thinks there are new configuration changes to apply every time.

```json
{"level":"info","ts":1631727177.0357869,"logger":"factory","msg":"current VMAgent configuration has changed"}
{"level":"info","ts":1631727177.234963,"logger":"factory","msg":"current VMAgent configuration has changed"}
{"level":"info","ts":1631727177.4474885,"logger":"factory","msg":"current VMAgent configuration has changed"}
{"level":"info","ts":1631727177.6393523,"logger":"factory","msg":"current VMAgent configuration has changed"}
{"level":"info","ts":1631727177.857756,"logger":"factory","msg":"current VMAgent configuration has changed"}
```

The cause is a `VMPodScrape` that selects on multiple labels:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
spec:
  # ...
  selector:
    matchLabels:
      app.kubernetes.io/name: x
      app.kubernetes.io/component: y
```

Running a `diff` between two states of the generated `vmagent.yaml` in the `Secret` reveals that the configuration differences are due to inconsistent order of those labels in the generated selector:

```diff
@@ -780,7 +780,7 @@
       - app-namespace
     selectors:
     - role: pod
-      label: app.kubernetes.io/name=x,app.kubernetes.io/component=y
+      label: app.kubernetes.io/component=y,app.kubernetes.io/name=x
   metrics_path: /metrics
   relabel_configs:
   - action: keep
```

Sorting the labels as part of generating the selector should fix the issue.
