### ISSUE TITLE
Scrape errors during high node churn

### ISSUE THREAD

**Issue by patstrom** [VictoriaMetrics/operator#327]
We are running a cluster with a somewhat high node churns and I've noticed that vm-operator and vm-agent (launched via vm-operator) are very slow to respond to targets that are removed due to the node being removed. I.e. the node is removed and vm-agent still tries to scrape the pods that were on it.

**Comment by f41gh7** [comment]
Hello, it seems like, you have to decrease value for vmagent's flag `-promscrape.kubernetesSDCheckInterval`

 It can be done with `extraArgs` passed to vmagent. Something like:

```
kind: VMAgent
spec:
  extraArgs:
     promscrape.kubernetesSDCheckInterval: 5s
```

 By default, it checks for targets changes every 30s.
