### ISSUE TITLE
VMPodScrape is missing targetPort after conversion from PodMonitor

### ISSUE THREAD

**Issue by aleem-99** [VictoriaMetrics/operator#335]
`targetPort` is missing in `VMPodScrape` after converted by operator.

PodMonitor Spec:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
  labels:
    app: mongo-writer
  name: mongo-writer
  namespace: data
spec:
  jobLabel: app
  podMetricsEndpoints:
  - path: /metrics
    targetPort: 9000
  selector:
    matchLabels:
      app: mongo-writer
```

Converted VMPodScrape Spec by operator:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  labels:
    app: mongo-writer
  name: mongo-writer
  namespace: data
spec:
  jobLabel: app
  namespaceSelector: {}
  podMetricsEndpoints:
  - bearerTokenSecret:
      key: ""
    path: /metrics
  selector:
    matchLabels:
      app: mongo-writer
```

This is causing the VMAgent to scrape incorrect port for the `podMetricsEndpoints`.
