### ISSUE TITLE
VMStaticScrape is missing basicAuth starting from operator version 1.18.0

### ISSUE THREAD

**Issue by marchenkov** [VictoriaMetrics/operator#337]
Problems with basicAuth insertion in vmagent config.

First step - install victoria-metrics-operator 1.17.2.

Used next static config:
```
---
apiVersion: v1
data:
  password: XXXXXXX
  username: XXXXXXX
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: test-secret
    app.kubernetes.io/name: test-secret
  name: test-secret
type: Opaque
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoria-metrics-stack
spec:
  vmAgentExternalLabelName: vmagent-docker
  image:
    pullPolicy: IfNotPresent
    repository: victoriametrics/vmagent
    tag: v1.66.2
  logFormat: json
  logLevel: INFO
  nodeScrapeNamespaceSelector: {}
  nodeScrapeSelector: {}
  podDisruptionBudget:
    maxUnavailable: 1
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  remoteWrite:
    - url: 'XXXXXXXX'
  replicaCount: 1
  scrapeInterval: 60s
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: test-static-servers
spec:
  jobName: test-static-servers
  targetEndpoints:
    - targets:
        - "server-1"
      honorLabels: true
      honorTimestamps: true
      interval: 60s
      scrapeTimeout: 5s
      path: "/federate"
      scheme: "https"
      port: "443"
      params:
        "match[]":
          - '{job=~".*"}'
      basicAuth:
        password:
          name: test-secret
          key: password
        username:
          name: test-secret
          key: username
```
So prepared victoria-metrics-operator, secret, vmagent and vmstaticscrape.

After entering in pod vmagent and `cat /etc/vmagent/config_out/vmagent.env.yaml` we can see basic_auth with username and password.
```
- job_name: default/test-static-servers/0
  honor_labels: true
  honor_timestamps: true
  static_configs:
  - targets:
    - server-1
  scrape_interval: 60s
  scrape_timeout: 5s
  metrics_path: /federate
  params:
    match[]:
    - '{job=~".*"}'
  scheme: https
  basic_auth:
    username: XXXXXXX
    password: XXXXXXX
  relabel_configs:
  - target_label: job
    replacement: test-static-servers
```

After upgrade to victoria-metrics-operator to 1.18.0 - we can't see basic_auth at all.
```
- job_name: default/test-static-servers/0
  honor_labels: true
  honor_timestamps: true
  static_configs:
  - targets:
    - server-1
  scrape_interval: 60s
  scrape_timeout: 5s
  metrics_path: /federate
  params:
    match[]:
    - '{job=~".*"}'
  scheme: https
  relabel_configs:
  - target_label: job
    replacement: test-static-servers
```

So we can't use basicAuth in VMStaticScrape since 1.18.0 (also not working in latest version - 1.19.0).
Is it possible to fix or we need to switch to vmauth?

Thank you
