### ISSUE TITLE
name of volumeMount in vmstorage StatefulSet does not follow name of volumeClaimTemplate

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#344]
For example, when I give a VMCluster like:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-cluster
  namespace: monitoring
spec:
  vmstorage:
    storage:
      volumeClaimTemplate:
        metadata:
          name: foo-db    # THIS!!
        spec:
          storageClassName: ceph-hdd-block
          resources:
            requests:
              storage: 3Gi

  vmselect:
    replicaCount: 1

  vminsert:
    replicaCount: 1
```

... the resulting StatefulSet for vmstorage becomes:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmstorage-example-cluster
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - args:
          (snip)
          volumeMounts:
            - mountPath: vmstorage-data
              name: vmstorage-db    # XXX
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: foo-db    # The name given in VMCluster.spec.vmstorage.storage.volumeClaimTemplate.metadata.name
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: ceph-hdd-block
        volumeMode: Filesystem
      status:
        phase: Pending
```

... and StatefulSet controller cannot create Pods due to volume name mismatch.

According to https://github.com/VictoriaMetrics/operator/blob/v0.19.1/controllers/factory/alertmanager.go#L571 , it seems that the operator allows renaming volumeClaimTemplate. However, `.spec.template.spec.containers[0].volumeMounts[0].name` of the resulting StatefulSet does not follow the volumeClaimTemplate's name. I think it is a problem.

VMSelect and VMAlertmanager, which also create StatefulSets, may have the same problem but I don't have checked them.

**Comment by f41gh7** [comment]
Thanks for reporting! There was incorrect logic for this field, it was fixed at commit 3f89ec83f6c1dc2138d9adf515997864d91407cb. related PR attached to the issue.

 Problem occured only with `vmstorage` and `vmselect`.

 Fix will be included into the next release.

**Comment by umezawatakeshi** [comment]
I tested dd71fec8e18c52a4a5d3fe43472dbd8a3825aa28. (I tested only vmstorage). The resulting StatefulSet looked fine.

However, after I modified VMCluster to change volumeClaimTemplate's name and the StatefulSet was updated, Pod recreation sometimes worked fine and sometimes didn't work: in the latter case, vmstorage Pods repeated starting and terminating.

**Comment by umezawatakeshi** [comment]
I tested a couple of times again, and each time the behavior was different, although I made the same changes. So, I cannot show a reproducible procedure.

I made a change like:
```
  apiVersion: operator.victoriametrics.com/v1beta1
  kind: VMCluster
  metadata:
    name: vmcluster-largeset
    namespace: monitoring
  spec:
    vmstorage:
      storage:
        volumeClaimTemplate:
+         metadata:
+           name: vmstorage-ssd
          spec:
            resources:
              requests:
                storage: 3Gi
-           storageClassName: ceph-hdd-block
+           storageClassName: ceph-ssd-block
          status: {}
```

and in failure cases, `kubectl get pod -w` shows like:

```
cybozu@gcp0-boot-0:~$ kubectl get pod -n monitoring -w --watch-only | (while read i; do echo -n `date`" : "; echo "$i"; done)
Mon Oct 11 04:20:21 UTC 2021 : NAME                                           READY   STATUS      RESTARTS   AGE
Mon Oct 11 04:20:24 UTC 2021 : vmstorage-vmcluster-largeset-0                 1/1     Running     0          39m
Mon Oct 11 04:20:24 UTC 2021 : vmstorage-vmcluster-largeset-2                 1/1     Running     0          39m
Mon Oct 11 04:20:24 UTC 2021 : vmstorage-vmcluster-largeset-1                 1/1     Running     0          39m
Mon Oct 11 04:20:26 UTC 2021 : vmstorage-vmcluster-largeset-0                 1/1     Terminating   0          39m
Mon Oct 11 04:21:10 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          39m
Mon Oct 11 04:21:11 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          40m
Mon Oct 11 04:21:11 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          40m
Mon Oct 11 04:21:12 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          1s
Mon Oct 11 04:21:12 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          1s
Mon Oct 11 04:21:12 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     ContainerCreating   0          1s
Mon Oct 11 04:21:28 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Running             0          17s
Mon Oct 11 04:22:01 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Running             0          50s
Mon Oct 11 04:22:03 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          52s
Mon Oct 11 04:22:03 UTC 2021 : vmstorage-vmcluster-largeset-0                 1/1     Terminating         0          52s
Mon Oct 11 04:22:53 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          102s
Mon Oct 11 04:23:06 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          115s
Mon Oct 11 04:23:12 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          2m1s
Mon Oct 11 04:23:12 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          2m1s
Mon Oct 11 04:23:13 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          0s
Mon Oct 11 04:23:13 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          0s
Mon Oct 11 04:23:13 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     ContainerCreating   0          0s
Mon Oct 11 04:23:37 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Running             0          24s
Mon Oct 11 04:23:38 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          25s
Mon Oct 11 04:24:11 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          58s
Mon Oct 11 04:24:22 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          69s
Mon Oct 11 04:24:23 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          70s
Mon Oct 11 04:24:23 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          0s
Mon Oct 11 04:24:23 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          0s
Mon Oct 11 04:24:23 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     ContainerCreating   0          0s
Mon Oct 11 04:24:47 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Running             0          24s
Mon Oct 11 04:24:55 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Running             0          32s
Mon Oct 11 04:24:57 UTC 2021 : vmstorage-vmcluster-largeset-0                 1/1     Running             0          34s
Mon Oct 11 04:25:01 UTC 2021 : vmstorage-vmcluster-largeset-1                 1/1     Terminating         0          43m
Mon Oct 11 04:25:47 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Terminating         0          44m
Mon Oct 11 04:25:53 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Terminating         0          44m
Mon Oct 11 04:25:53 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Terminating         0          44m
Mon Oct 11 04:25:54 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Pending             0          1s
Mon Oct 11 04:25:54 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Pending             0          1s
Mon Oct 11 04:25:55 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     ContainerCreating   0          2s
Mon Oct 11 04:26:19 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Running             0          26s
Mon Oct 11 04:26:36 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Terminating         0          43s
Mon Oct 11 04:27:17 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Terminating         0          84s
Mon Oct 11 04:27:23 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Terminating         0          89s
Mon Oct 11 04:27:23 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Terminating         0          90s
Mon Oct 11 04:27:23 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Pending             0          0s
Mon Oct 11 04:27:23 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Pending             0          0s
Mon Oct 11 04:27:24 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     ContainerCreating   0          1s
Mon Oct 11 04:27:32 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Running             0          9s
Mon Oct 11 04:27:54 UTC 2021 : vmstorage-vmcluster-largeset-1                 0/1     Running             0          31s
Mon Oct 11 04:27:57 UTC 2021 : vmstorage-vmcluster-largeset-1                 1/1     Running             0          34s
Mon Oct 11 04:28:04 UTC 2021 : vmstorage-vmcluster-largeset-0                 1/1     Terminating         0          3m41s
Mon Oct 11 04:28:52 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          4m29s
Mon Oct 11 04:28:54 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          4m31s
Mon Oct 11 04:29:03 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          4m40s
Mon Oct 11 04:29:04 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          4m41s
Mon Oct 11 04:29:04 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          0s
Mon Oct 11 04:29:04 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Pending             0          0s
Mon Oct 11 04:29:05 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     ContainerCreating   0          1s
Mon Oct 11 04:29:18 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Running             0          14s
Mon Oct 11 04:29:41 UTC 2021 : vmstorage-vmcluster-largeset-0                 0/1     Terminating         0          37s
```

`kubectl describe sts -n monitoring vmstorage-vmcluster-largeset` shows failure events like:

```
Events:
  Type     Reason            Age                    From                    Message
  ----     ------            ----                   ----                    -------
  Normal   SuccessfulCreate  9m11s                  statefulset-controller  create Claim vmstorage-ssd-vmstorage-vmcluster-largeset-0 Pod vmstorage-vmcluster-largeset-0 in StatefulSet vmstorage-vmcluster-largeset success
  Warning  FailedUpdate      8m6s (x16 over 9m10s)  statefulset-controller  update Pod vmstorage-vmcluster-largeset-0 in StatefulSet vmstorage-vmcluster-largeset failed error: Pod "vmstorage-vmcluster-largeset-0" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
    Volumes: []core.Volume{
-     {
-       Name: "vmstorage-ssd",
-       VolumeSource: core.VolumeSource{
-         PersistentVolumeClaim: &core.PersistentVolumeClaimVolumeSource{ClaimName: "vmstorage-ssd-vmstorage-vmcluste"...},
-       },
-     },
      {Name: "vmstorage-db", VolumeSource: {PersistentVolumeClaim: &{ClaimName: "vmstorage-db-vmstorage-vmcluster-largeset-0"}}},
      {Name: "vmcluster-vmcluster-largeset-token-rxrr5", VolumeSource: {Secret: &{SecretName: "vmcluster-vmcluster-largeset-token-rxrr5", DefaultMode: &420}}},
    },
    InitContainers: nil,
    Containers:     {{Name: "vmstorage", Image: "quay.io/cybozu/victoriametrics-vmstorage:1.65.0.1", Args: {"-dedup.minScrapeInterval=30s", "-httpListenAddr=:8482", "-retentionPeriod=400d", "-storageDataPath=vmstorage-data", ...}, Ports: {{Name: "http", ContainerPort: 8482, Protocol: "TCP"}, {Name: "vminsert", ContainerPort: 8400, Protocol: "TCP"}, {Name: "vmselect", ContainerPort: 8401, Protocol: "TCP"}}, ...}},
    ... // 27 identical fields
  }
  Normal   SuccessfulCreate  8m4s                   statefulset-controller  create Pod vmstorage-vmcluster-largeset-0 in StatefulSet vmstorage-vmcluster-largeset successful
  Normal   SuccessfulCreate  8m4s                   statefulset-controller  create Claim vmstorage-ssd-vmstorage-vmcluster-largeset-1 Pod vmstorage-vmcluster-largeset-1 in StatefulSet vmstorage-vmcluster-largeset success
  Warning  FailedUpdate      4m11s (x22 over 8m3s)  statefulset-controller  update Pod vmstorage-vmcluster-largeset-1 in StatefulSet vmstorage-vmcluster-largeset failed error: Pod "vmstorage-vmcluster-largeset-1" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
    Volumes: []core.Volume{
-     {
-       Name: "vmstorage-ssd",
-       VolumeSource: core.VolumeSource{
-         PersistentVolumeClaim: &core.PersistentVolumeClaimVolumeSource{ClaimName: "vmstorage-ssd-vmstorage-vmcluste"...},
-       },
-     },
      {Name: "vmstorage-db", VolumeSource: {PersistentVolumeClaim: &{ClaimName: "vmstorage-db-vmstorage-vmcluster-largeset-1"}}},
      {Name: "vmcluster-vmcluster-largeset-token-rxrr5", VolumeSource: {Secret: &{SecretName: "vmcluster-vmcluster-largeset-token-rxrr5", DefaultMode: &420}}},
    },
    InitContainers: nil,
    Containers:     {{Name: "vmstorage", Image: "quay.io/cybozu/victoriametrics-vmstorage:1.65.0.1", Args: {"-dedup.minScrapeInterval=30s", "-httpListenAddr=:8482", "-retentionPeriod=400d", "-storageDataPath=vmstorage-data", ...}, Ports: {{Name: "http", ContainerPort: 8482, Protocol: "TCP"}, {Name: "vminsert", ContainerPort: 8400, Protocol: "TCP"}, {Name: "vmselect", ContainerPort: 8401, Protocol: "TCP"}}, ...}},
    ... // 27 identical fields
  }
```


environment:
k8s: v1.20.7

**Comment by umezawatakeshi** [comment]
I haven't been able to find enough time, so it will take a while longer...

**Comment by umezawatakeshi** [comment]
I have tested v0.20.1 . Unfortunately, the behavior is not improved: Pod update was stuck and `kubectl describe sts` showed warning logs like before.

environment:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"archive", BuildDate:"2021-09-28T09:01:15Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by f41gh7** [comment]
May i ask you for archieved operator logs during update, probably it helps to investigate whats went wrong?

 And another question, does first pod become available? env param - `VM_PODWAITREADYTIMEOUT` controls how  long wait until pod is ready.

**Comment by umezawatakeshi** [comment]
I tested with v0.20.3 and got the following log: https://gist.github.com/umezawatakeshi/e057d7e8b63794e5cb1404d1e2c48e40

the VMCluster first applied is:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: storage-rename-test
  namespace: monitoring
spec:
  retentionPeriod: 1d
  vmstorage:
    replicaCount: 3
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-ssd-block
          resources:
            requests:
              storage: 1Gi
  vmselect:
    replicaCount: 1
  vminsert:
    replicaCount: 1
```

This time, I noticed that the first pod (`vmstorage-storage-rename-test-0`) became `Terminating` state soon after the operator output error log "cannot update or create vmcluster". I'm not sure which was the cause and which was the result.

> And another question, does first pod become available?

As far as I did `kubectl get pod -w`, the first pod became `Ready` and `READY` column became `1/1`.

> env param - VM_PODWAITREADYTIMEOUT controls how long wait until pod is ready.

I set `VM_PODWAITREADYTIMEOUT` "1h", which is much longer than the default, but the behavior was same.
