### ISSUE TITLE
vmBackup storage mount path not consistent with vmstorage

### ISSUE THREAD

**Issue by wu0407** [VictoriaMetrics/operator#349]
vmstorage-db is mount in /vm-data with vmstorage container, but that is mount in /victoria-metrics-data with  vmbackup container.
operator version: v0.19.1
vmcluster configure:
```
 vmstorage:
    extraArgs:
      search.maxUniqueTimeseries: "600000"
    image:
      tag: v1.66.2-cluster
    replicaCount: 2
    resources:
      limits:
        cpu: "4"
        memory: 16Gi
      requests:
        cpu: 50m
        memory: 1Gi
    storage:
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: 100Gi
          storageClassName: cbs-ssd
        status: {}
    storageDataPath: /vm-data
    vmBackup:
      acceptEULA: true
      credentialsSecret:
        key: credentials-backup.yaml
        name: credentials-backup
      destination: s3://test/$(NODENAME)
      disableMonthly: true
      disableWeekly: true
      extraArgs:
        customS3Endpoint: https://cos.ap-shanghai.myqcloud.com
        keepLastDaily: "30"
        keepLastHourly: "72"
        runOnStart: "true"
        storageDataPath: /victoria-metrics-data
      extraEnvs:
      - name: AWS_DEFAULT_REGION
        value: ap-shanghai
      - name: NODENAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
```
result statefulset:
```
 spec:
      containers:
      - args:
        - -dedup.minScrapeInterval=1ms
        - -httpListenAddr=:8482
        - -retentionPeriod=14
        - -search.maxUniqueTimeseries=600000
        - -storageDataPath=/vm-data
        - -vminsertAddr=:8400
        - -vmselectAddr=:8401
        image: victoriametrics/vmstorage:v1.66.2-cluster
        imagePullPolicy: IfNotPresent
        name: vmstorage
         ...........
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /vm-data
          name: vmstorage-db
      - args:
        - -credsFilePath=/etc/vm/creds/credentials-backup.yaml
        - -customS3Endpoint=https://cos.ap-shanghai.myqcloud.com
        - -disableMonthly
        - -disableWeekly
        - -dst=s3://test-thanos-1252328573/$(NODENAME)
        - -envflag.enable=true
        - -eula
        - -keepLastDaily=30
        - -keepLastHourly=72
        - -runOnStart=true
        - -snapshot.createURL=http://localhost:8482/snapshot/create
        - -snapshot.deleteURL=http://localhost:8482/snapshot/delete
        - -storageDataPath=/vm-data
        env:
        - name: AWS_DEFAULT_REGION
          value: ap-shanghai
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: victoriametrics/vmbackupmanager:v1.66.2-enterprise
        imagePullPolicy: IfNotPresent
        name: vmbackuper
    .  ...............
        volumeMounts:
        - mountPath: /victoria-metrics-data
          name: vmstorage-db
          readOnly: true
        - mountPath: /etc/vm/creds
          name: secret-credentials-backup
          readOnly: true
```

if set `storageDataPath` in `extraArgs`, then duplication  options of `storageDataPath`
```
   extraArgs:
        customS3Endpoint: https://cos.ap-shanghai.myqcloud.com
        keepLastDaily: "30"
        keepLastHourly: "72"
        runOnStart: "true"
        storageDataPath: /victoria-metrics-data
```
result statefulset:
```
  - args:
        - -credsFilePath=/etc/vm/creds/credentials-backup.yaml
        - -customS3Endpoint=https://cos.ap-shanghai.myqcloud.com
        - -disableMonthly
        - -disableWeekly
        - -dst=s3://test/$(NODENAME)
        - -envflag.enable=true
        - -eula
        - -keepLastDaily=30
        - -keepLastHourly=72
        - -runOnStart=true
        - -snapshot.createURL=http://localhost:8482/snapshot/create
        - -snapshot.deleteURL=http://localhost:8482/snapshot/delete
        - -storageDataPath=/victoria-metrics-data
        - -storageDataPath=/vm-data
```
