### ISSUE TITLE
Alertmanager CRD overlaps with the Prometheus Operator one

### ISSUE THREAD

**Issue by clmssz** [VictoriaMetrics/operator#35]
Hi there,

Not sure if the files in master are the most up to date ones, since you mention an `install` directory in the docs and it's not there yet, but in the `deploy/crds` for vmalertmanagers, singular and plural terms mismatch - If the goal is to use the coreos CRD for alertmanager, better remove it from CRDs here as it will conflict with an already deployed prometheus operator

```
  names:
    kind: Alertmanager
    listKind: AlertmanagerList
    plural: vmalertmanagers
    shortNames:
    - vma
    singular: alertmanager
```
