### ISSUE TITLE
Highly available vmalert setup skips some recording evaluations at restart

### ISSUE THREAD

**Issue by g7r** [VictoriaMetrics/operator#353]
I'm currently setting up a HA vmalert cluster. The relevant part of its definition is:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert-cluster

spec:
  replicaCount: 2
```

I have a group of recording rules with 30s period. When I do `kubectl rollout restart deployment ...` I observe missing points in recording rules results.

AFAICT, the problem is that `vmalert`s are being restarted too quick and that `vmalert`s rule evaluation starts after (not so) random delay: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmalert/group.go#L226-L231

I propose that liveness check should become true only after all rule evaluations has been started.
