### ISSUE TITLE
feat: VMUser headers support

### ISSUE THREAD

**Issue by zimbatm** [VictoriaMetrics/operator#360]
Now that VMAuth can forward arbitrary headers ( https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1736  ), is it possible to also support it in the operator?

I think it would work well if the VMUser TargetRefs was extended with a headers field like that:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: prod-writer
  namespace: default
spec:
  generatePassword: true
  targetRefs:
  - static: 
      url: "http://loki:3100/"
    paths:
    - /loki/api/v1/write
    headers: ["X-Scope-OrgID: abc"]
  username: prod-writer
```

/cc @valyala
