### ISSUE TITLE
How to create vmalertmanager config with multiple routes

### ISSUE THREAD

**Issue by symmetriac** [VictoriaMetrics/operator#374]
I use the following VMAlertmanagerConfig configuration

```apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vmalertmanager-config
  namespace: monitoring
spec:
  route:
    receiver: slack
  receivers:
  - name: slack
    slack_configs:
    ##slack configuration##
```
and this gives the result
```
route:
  routes:
  - matchers:
    - namespace = "monitoring"
    receiver: monitoring-vmalertmanager-config-slack
receivers:
- name: monitoring-vmalertmanager-config-slack
  slack_configs:   
```

After adding the next route like described in [docs](https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#vmalertmanagerconfig)
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vmalertmanager-config
  namespace: monitoring
spec:
  route:
    receiver: slack
    routes:
      - receiver: webhook
        continue: false
  receivers:
  - name: slack
  - name: webhook
```
the final config becomes
```
route:
  receiver: monitoring-vmalertmanager-config-slack
  group_by:
  - alertname
  routes:
  - routes:
    - continue: false
     matchers:
     - namespace = "monitoring"
     receiver: monitoring-vmalertmanager-config-slack
     continue: true
```

So the new route with webhook receiver was not added to routes and the receiver was not added to receivers with the log message
`level=info ts=2021-11-10T06:56:52.640Z caller=main.go:414 component=configuration msg="skipping creation of receiver not referenced by any route" receiver=monitoring-vmalertmanager-config-webhook`

What am I doing wrong and how I can create multiple routes properly?

**Comment by f41gh7** [comment]
Hello, 
 
Hm, i cannot reproduce, can you share kubernetes version? Do you use CRD from release 0.20+ ?

 My files:
```yaml
# config.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vmalertmanager-config
spec:
  route:
    receiver: slack
    routes:
      - receiver: webhook
        continue: false
  receivers:
  - name: slack
    webhook_configs:
      - url: http://some-2.example.net
  - name: webhook
    webhook_configs:
      - url: http://some-1.example.net
---
# alertmanager.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: vmalertmanager-example-alertmanager
  labels:
    app: vm-operator
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'webhook'
    receivers:
      - name: 'webhook'
        webhook_configs:
          - url: 'http://alertmanagerwh:30500/'

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: example-alertmanager
spec:
  replicaCount: 1
  configSecret: vmalertmanager-example-alertmanager
  configSelector: {}
```

 Produced config:
```yaml
global:
  resolve_timeout: 5m
route:
  receiver: webhook
  group_by:
  - job
  routes:
  - routes:
    - receiver: default-vmalertmanager-config-webhook
      continue: false
    matchers:
    - namespace = "default"
    receiver: default-vmalertmanager-config-slack
    continue: true
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: webhook
  webhook_configs:
  - url: http://alertmanagerwh:30500/
- name: default-vmalertmanager-config-slack
  webhook_configs:
  - url: http://some-2.example.net
- name: default-vmalertmanager-config-webhook
  webhook_configs:
  - url: http://some-1.example.net
```

 It seems to be desired configuration. Correct me, if i miss something.

**Comment by symmetriac** [comment]
Yes, your configuration seems right.
my k8s version is 1.21 and vm operator version is v0.20.0
Also I don't use separate secret for initial config, I added it in configRawYaml:
```
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      repeat_interval: 1h
      receiver: 'slack'
    receivers:
      - name: 'slack'
```
And in the vmalertmanagerconfigs resource i see:
```  route:
    receiver: slack
    routes:
    - {}
```
