### ISSUE TITLE
is there a CRD that can set ec2_sd_config?

### ISSUE THREAD

**Issue by alexandrst88** [VictoriaMetrics/operator#376]

**Comment by f41gh7** [comment]
No, there is no such CRD. It's possible to define it with inline raw configuration at the `VMAgent` section:

```yaml
kind: VMAgent
spec:
  inlineScrapeConfig: |
   - job_name: ec2-monitoring
     ec2_sd_configs:
     - region: eu-west-1
       port: 9100
```
  Hm, maybe it's possible to create some generic CRD for all other service discovery types. Need to think about it.

**Comment by Vladyslav-Miletskyi** [comment]
@lacer-utkarsh 

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-PrometheusEC2.html

> The IAM role for the EC2 instance where the CloudWatch agent runs must include the ec2:DescribeInstance permission. For example, you could attach the managed policy AmazonEC2ReadOnlyAccess to the instance running the CloudWatch agent.

make sure, that all k8s nodes have IAM role with `ec2:DescribeInstance` policy allowed

**Comment by Vladyslav-Miletskyi** [comment]
Scrape EC2s, which are tagged with `prometheus.io/scrape=true`

```yaml
  inlineScrapeConfig: |
   - job_name: ec2
      honor_labels: true
      ec2_sd_configs:
        - region: us-west-1
          filters:
          - name: tag:prometheus.io/scrape
            values:
              - "true"
      relabel_configs:
        - source_labels: [__meta_ec2_tag_prometheus_io_path]
          target_label: __metrics_path__
        - source_labels: [__address__, __meta_ec2_tag_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels: [__meta_ec2_tag_prometheus_io_job]
          target_label: job
        - regex: __meta_ec2_(instance_id|availability_zone|instance_type)
          action: labelmap
        - regex: __meta_ec2_tag_prometheus_io(.+)
          action: labeldrop
        - action: labelmap
          regex: __meta_ec2_tag_(.+)
```
