### ISSUE TITLE
Config Reloader resources

### ISSUE THREAD

**Issue by artmakh** [VictoriaMetrics/operator#384]
I've encountered a problem when VMAgent restarts due to Config Reloader been throttled by k8s.
I found no way to change default limits for Config Reloader in VMAgent manifest. Is it possible to add some parts of configuration of Config Reloader to VMAgent (and presumably to VMAuth)?

**Comment by f41gh7** [comment]
There are two ways to change it:
1) patch config-reloader image at CRD spec:
```yaml

kind: VMAgent
spec:
  containers:
  - name: config-reloader
    resources:
       limits:
         cpu: "5"

```

2) change operator default values with env vars:
```yaml
- name: VM_VMALERTDEFAULT_CONFIGRELOADERCPU
  value: 100m
```
 Each reloader  has own env var. Full list of it https://github.com/VictoriaMetrics/operator/blob/master/vars.MD
