### ISSUE TITLE
VMSingle with storageDataPath and external PVC doesn't create any Pod

### ISSUE THREAD

**Issue by kernel164** [VictoriaMetrics/operator#403]
if I use following VMSingle CR. it doesn't create any VMSingle pod.

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
spec:
  storageDataPath: /data
  volumeMounts:
    - mountPath: /data
      name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-vmsingle-data
```

**Comment by kernel164** [comment]
```
{"level":"error","ts":1640666777.92905,"logger":"controller.vmsingle","msg":"Reconciler error","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMSingle","name":"demo","namespace":"gravity-observability-system","error":"cannot create new vmsingle deploy: Deployment.apps \"vmsingle-demo\" is invalid: spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: \"/data\": must be unique","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}
```

**Comment by f41gh7** [comment]
It's really uneven, need to fix it and make it more simple.

 Can you try this one example:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
spec:
  storage: {}
  storageDataPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-vmsingle-data
```
