### ISSUE TITLE
TLS Support for VMInsert

### ISSUE THREAD

**Issue by pavan541cs** [VictoriaMetrics/operator#404]
VictoriaMetrics provides TLS configuration for all of its components. Here is the doc link https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#list-of-command-line-flags-for-vminsert. We are using VMCluster CRD.

Issues in Operator
1) There is no Object provided by the operator for the same. The current solution is to provide the TLS arguments in the extraVars provided by the operator.
2) Even if the pods are started in TLS mode, the liveness and readiness probes are hardcoded to HTTP scheme (https://github.com/VictoriaMetrics/operator/blob/master/controllers/factory/builders.go#L291). And hence the pod is restarting due to the failure of the readiness probe.

Possible Solutions
1) Add support for TLS to VMCLuster using the existing TLSConfig object.
2) Provide support for dynamic schemes (HTTP, HTTPS etc)

**Comment by pavan541cs** [comment]
@f41gh7 Please help me if this will be a feature to be contributed to or if there is already a well-known workaround that can be used. If the approach is the right one, I will be more than happy to contribute.

**Comment by f41gh7** [comment]
I think, that it's very specific configuration, not sure, that it should have direct CRD option.

Current work-around - use extraEnv, mount tls keys and overwrite exist liveness/readiness settings.

 Something like:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-vmcluster-persistent
spec:
  retentionPeriod: "4"
  replicationFactor: 2
  vmstorage:
    replicaCount: 1
  vminsert:
    replicaCount: 1
    extraEnv:
         tls: "true"
         tlsCertFile: /etc/vm/secrets/insert-tls/cert.pem
         tlsKeyFile: /etc/vm/secrets/insert-tls/key.pem
    secrets:
         # secret name: insert-tls with data cert.pem and key.pem at the same namespace as vmcluster
         - insert-tls
    livenessProbe:
       httpGet:
            scheme: HTTPS
    readinessProbe:
       httpGet:
            scheme: HTTPS
```
