### ISSUE TITLE
VMagents doesn't scrap metrics after rolling update

### ISSUE THREAD

**Issue by alexandrst88** [VictoriaMetrics/operator#407]
Hi! we have current setups of vmagents

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-ha
spec:
  image:
    tag: v1.66.0
  vmAgentExternalLabelName: vmagent_ha_prod
  additionalScrapeConfigs:
    name: additional-scrape-config
    key: additional-config.yaml
  replicaCount: 2
  shardCount: 3
  extraArgs:
    promscrape.maxScrapeSize: 48MB
  podMetadata:
    labels:
      env: prod
  resources:
    requests:
      cpu: 4
      memory: 8Gi
    limits:
      cpu: 4
      memory: 8Gi
  readinessProbe:
    httpGet:
      path: /health
      port: 8429
    successThreshold: 1
    failureThreshold: 10
    periodSeconds: 5
    timeoutSeconds: 5
    initialDelaySeconds: 180
```

But after rolling update(for example bumping vmagent version) we have 30-60s gaps on the graphs.
![Screenshot 2022-01-12 at 16 42 23](https://user-images.githubusercontent.com/8613199/149161980-2570a764-d79a-4d9b-a95a-83ecc0e4fd40.png)
