### ISSUE TITLE
Operator adds opentsdb-http port to endpoints in VMServiceScrape

### ISSUE THREAD

**Issue by skibadmitriy** [VictoriaMetrics/operator#420]
Hello

I've run into a problem with unexpected behavior of VMOperator when I've enabled insertPorts.openTSDBHTTPPort: "4242 in VMCluster spec. VMOperator has added this port (opentsdb-http) to VMServiceScrape of VMInsert
```
spec:
  endpoints:
  - path: /metrics
    port: http
  - path: /metrics
    port: opentsdb-http
```
But this port isn't suitable for getting metrics and doesn't have /metrics path. So I have a lot of error messages in VMAgent log
