### ISSUE TITLE
Operator won't process bearerTokenSecret on RemoteWriteSpec if basicAuth isn't set

### ISSUE THREAD

**Issue by artifactori** [VictoriaMetrics/operator#422]
I've configured `VMAgent` that uses bearer token secret but the secret isn't being processed at all.

Resource definition:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: agent
spec:
  remoteWrite:
    - url: https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server=datasource
      bearerTokenSecret:
        key: token
        name: new-relic-token
```

Resulting in these pods being deployed without any configured remote write secret:
```
Port:          8429/TCP
Host Port:     0/TCP
Args:
  -httpListenAddr=:8429
  -promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml
  -remoteWrite.maxDiskUsagePerURL=1073741824
  -remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data
  -remoteWrite.url=https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server=datasource
State:          Running
```
