### ISSUE TITLE
Operator fails to update VMInsert after scaling up VMStorage

### ISSUE THREAD

**Issue by PabloL007** [VictoriaMetrics/operator#426]
When modifying the number of VMStorage replicas through the victoria-metrics-k8s-stack Helm chart’s `vmcluster.spec.vmstorage.replicaCount` attribute from 2 to 3 and applying these new values with a Helm upgrade, the operator:

1. Spins up a new VMStorage instance:
```json
{"level":"info","ts":1644488270.5641422,"logger":"controller_vmcluster","msg":"Reconciling VMCluster","Request.Namespace":"victoriametrics","Request.Name":"victoria-metrics-k8s-stack"}
{"level":"info","ts":1644488270.5702302,"logger":"factory","msg":"creating psp for vmcluster"}
{"level":"info","ts":1644488270.6492476,"logger":"factory","msg":"create or update vmstorage for cluster","controller":"vmstorage","cluster":"victoria-metrics-k8s-stack"}
{"level":"info","ts":1644488270.6543372,"logger":"factory","msg":"vmstorage was found, updating it","controller":"vmstorage","cluster":"victoria-metrics-k8s-stack"}
{"level":"info","ts":1644488272.6701486,"logger":"client_utils","msg":"checking if update needed","controller":"sts.rollingupdate","desiredVersion":"vmstorage-victoria-metrics-k8s-stack-fd6bf4779","wasRecreated":false}
{"level":"info","ts":1644488272.679214,"logger":"client_utils","msg":"starting pods update, checking updated, by not ready pods","controller":"sts.rollingupdate","desiredVersion":"vmstorage-victoria-metrics-k8s-stack-fd6bf4779","wasRecreated":false,"updated pods count":1,"desired version":"vmstorage-victoria-metrics-k8s-stack-fd6bf4779"}
{"level":"info","ts":1644488272.6792815,"logger":"client_utils","msg":"checking ready status for already updated pod to desired version","controller":"sts.rollingupdate","desiredVersion":"vmstorage-victoria-metrics-k8s-stack-fd6bf4779","wasRecreated":false,"pod":"vmstorage-victoria-metrics-k8s-stack-2"}
{"level":"info","ts":1644488307.687704,"logger":"client_utils","msg":"pod update finished with revision","pod":"vmstorage-victoria-metrics-k8s-stack-2","revision":"vmstorage-victoria-metrics-k8s-stack-fd6bf4779"}
{"level":"info","ts":1644488307.696484,"logger":"factory","msg":"check pods availability"}
{"level":"info","ts":1644488307.7048855,"logger":"factory","msg":"pods available","count":3,"spec-count":3}
```

2. Updates the VMSelect configuration through a rolling restart:
```json
{"level":"info","ts":1644488307.7113948,"logger":"factory","msg":"create or update vmselect for cluster","controller":"vmselect","cluster":"victoria-metrics-k8s-stack"}
{"level":"info","ts":1644488307.7149222,"logger":"factory","msg":"built args with vmstorage nodes for vmselect","vmstorage args":"-storageNode=vmstorage-victoria-metrics-k8s-stack-0.vmstorage-victoria-metrics-k8s-stack.victoriametrics:8401,vmstorage-victoria-metrics-k8s-stack-1.vmstorage-victoria-metrics-k8s-stack.victoriametrics:8401,vmstorage-victoria-metrics-k8s-stack-2.vmstorage-victoria-metrics-k8s-stack.victoriametrics:8401"}
{"level":"info","ts":1644488307.7149985,"logger":"factory","msg":"args for vmselect ","args":"-selectNode=vmselect-victoria-metrics-k8s-stack-0.vmselect-victoria-metrics-k8s-stack.victoriametrics:8481,vmselect-victoria-metrics-k8s-stack-1.vmselect-victoria-metrics-k8s-stack.victoriametrics:8481,vmselect-victoria-metrics-k8s-stack-2.vmselect-victoria-metrics-k8s-stack.victoriametrics:8481,vmselect-victoria-metrics-k8s-stack-3.vmselect-victoria-metrics-k8s-stack.victoriametrics:8481,vmselect-victoria-metrics-k8s-stack-4.vmselect-victoria-metrics-k8s-stack.victoriametrics:8481"}
{"level":"info","ts":1644488309.7334452,"logger":"client_utils","msg":"sts update is needed","sts":"vmselect-victoria-metrics-k8s-stack","currentVersion":"vmselect-victoria-metrics-k8s-stack-5fc8bb86df","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6"}
{"level":"info","ts":1644488309.733496,"logger":"client_utils","msg":"checking if update needed","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false}
{"level":"info","ts":1644488309.7424188,"logger":"client_utils","msg":"starting pods update, checking updated, by not ready pods","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"updated pods count":0,"desired version":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6"}
{"level":"info","ts":1644488309.7424512,"logger":"client_utils","msg":"updating pod","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-0"}
{"level":"info","ts":1644488324.769647,"logger":"client_utils","msg":"pod update finished with revision","pod":"vmselect-victoria-metrics-k8s-stack-0","revision":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6"}
{"level":"info","ts":1644488324.7696884,"logger":"client_utils","msg":"pod was updated","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-0"}
{"level":"info","ts":1644488325.770272,"logger":"client_utils","msg":"updating pod","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-1"}
{"level":"info","ts":1644488340.7890842,"logger":"client_utils","msg":"pod update finished with revision","pod":"vmselect-victoria-metrics-k8s-stack-1","revision":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6"}
{"level":"info","ts":1644488340.7891269,"logger":"client_utils","msg":"pod was updated","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-1"}
{"level":"info","ts":1644488341.7894244,"logger":"client_utils","msg":"updating pod","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-2"}
{"level":"info","ts":1644488356.8069322,"logger":"client_utils","msg":"pod update finished with revision","pod":"vmselect-victoria-metrics-k8s-stack-2","revision":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6"}
{"level":"info","ts":1644488356.8069704,"logger":"client_utils","msg":"pod was updated","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-2"}
{"level":"info","ts":1644488357.8073165,"logger":"client_utils","msg":"updating pod","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-3"}
{"level":"info","ts":1644488372.828026,"logger":"client_utils","msg":"pod update finished with revision","pod":"vmselect-victoria-metrics-k8s-stack-3","revision":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6"}
{"level":"info","ts":1644488372.8280683,"logger":"client_utils","msg":"pod was updated","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-3"}
{"level":"info","ts":1644488373.8289704,"logger":"client_utils","msg":"updating pod","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-4"}
{"level":"info","ts":1644488393.846497,"logger":"client_utils","msg":"pod update finished with revision","pod":"vmselect-victoria-metrics-k8s-stack-4","revision":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6"}
{"level":"info","ts":1644488393.8465393,"logger":"client_utils","msg":"pod was updated","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-7d58b4bff6","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-4"}
{"level":"info","ts":1644488394.8730726,"logger":"factory","msg":"check pods availability"}
{"level":"info","ts":1644488394.8847225,"logger":"factory","msg":"pods available","count":5,"spec-count":2}
```

3. Then fails to update VMInsert

This can lead to running a non-optimal setup if the issue isn't noticed. If the operator handles the change for VMSelect I would expect it to also handle it for VMInsert.

For context, I am running version 0.22.1 of the victoriametrics/operator image through the aforementioned Helm chart.

**Comment by f41gh7** [comment]
Hello, can you clarify why VMInsert fails? Or it's a hypothetical situation?

 According to the given log, updating is still in progress.

**Comment by PabloL007** [comment]
VMInsert doesn't fail, the issue is that it never gets updated by the operator to include the new node in the arguments, even hours after VMSelect has been updated for the same thing.

**Comment by PabloL007** [comment]
To expand a bit here is the relevant part of my Helm chart values:
```yaml
vmcluster:
  enabled: true
  # https://docs.victoriametrics.com/operator/api.html#vmclusterspec
  spec:
    retentionPeriod: "5h"
    replicationFactor: 2
    vmstorage:
      extraArgs:
        dedup.minScrapeInterval: 15s # https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication
      replicaCount: 3
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 1
          memory: 4Gi
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ebs-st1
            resources:
              requests:
                storage: 125Gi
      storageDataPath: "/vm-data"

    vmselect:
      cacheMountPath: "/select-cache"
      extraArgs:
        dedup.minScrapeInterval: 15s # https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication
      hpa:
        maxReplicas: 8
        minReplicas: 2
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                averageUtilization: 75
                type: Utilization
          - type: Resource
            resource:
              name: memory
              target:
                averageUtilization: 75
                type: Utilization
      podDisruptionBudget:
        maxUnavailable: 1
      replicaCount: 2
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
      storage:
        emptyDir:
          sizeLimit: 2Gi

    vminsert:
      hpa:
        maxReplicas: 8
        minReplicas: 2
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                averageUtilization: 75
                type: Utilization
          - type: Resource
            resource:
              name: memory
              target:
                averageUtilization: 75
                type: Utilization
      podDisruptionBudget:
        maxUnavailable: 1
      replicaCount: 2
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi

vmagent:
  enabled: true
  # https://docs.victoriametrics.com/operator/api.html#vmagentspec
  spec:
    extraArgs:
      promscrape.streamParse: "true"
    podScrapeNamespaceSelector: {}
    podScrapeSelector:
      matchExpressions:
        - key: prometheusDedicated
          operator: DoesNotExist
    probeNamespaceSelector: {}
    probeSelector:
      matchExpressions:
        - key: prometheusDedicated
          operator: DoesNotExist
    remoteWrite:
      - url: http://vminsert-victoria-metrics-k8s-stack:8480/insert/0/prometheus/api/v1/write
    replicaCount: 2
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 1
        memory: 4Gi
    scrapeInterval: 15s
    selectAllByDefault: true
    serviceScrapeNamespaceSelector: {}
    serviceScrapeSelector:
      matchExpressions:
        - key: prometheusDedicated
          operator: DoesNotExist
    shardCount: 2
    tolerations:
      - key: "observability"
        operator: "Exists"
        effect: ""
  ingress:
    enabled: false
```
I'm currently testing scaling VMStorage on an EKS cluster and what I'm seeing is that after deploying it with vmcluster.spec.vmstorage.replicaCount set to 2 with a helm install, I see the message saying that vmcluster has been reconciled but then when I change that attribute to 3 and do a helm upgrade I observe the behavior described above and the cluster never seems to reconcile after that.

**Comment by PabloL007** [comment]
I recently spotted this which might be related:
```
{"level":"dpanic","ts":1644840679.8661501,"logger":"client_utils","msg":"non-string key argument passed to logging, ignoring all later arguments","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-84857766bc","wasRecreated":false,"invalid key":4,"stacktrace":"github.com/VictoriaMetrics/operator/controllers/factory/k8stools.HandleSTSUpdate\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/k8stools/sts.go:48\ngithub.com/VictoriaMetrics/operator/controllers/factory.createOrUpdateVMSelect\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:268\ngithub.com/VictoriaMetrics/operator/controllers/factory.CreateOrUpdateVMCluster\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:132\ngithub.com/VictoriaMetrics/operator/controllers.(*VMClusterReconciler).Reconcile\n\tgithub.com/VictoriaMetrics/operator/controllers/vmcluster_controller.go:68\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1644840679.8661458,"logger":"client_utils","msg":"unexpected count of pods for sts: %s, want: %d, got: %d, seems like configuration of stateful wasn't correct and kubernetes cannot create pod, check kubectl events for namespace: %s, to find out source of problem","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-84857766bc","wasRecreated":false,"vmselect-victoria-metrics-k8s-stack":3}
{"level":"info","ts":1644840679.866221,"logger":"client_utils","msg":"starting pods update, checking updated, by not ready pods","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-84857766bc","wasRecreated":false,"updated pods count":0,"desired version":"vmselect-victoria-metrics-k8s-stack-84857766bc"}
{"level":"info","ts":1644840679.86623,"logger":"client_utils","msg":"updating pod","controller":"sts.rollingupdate","desiredVersion":"vmselect-victoria-metrics-k8s-stack-84857766bc","wasRecreated":false,"pod":"vmselect-victoria-metrics-k8s-stack-3"}
{"level":"info","ts":1644840769.8817024,"logger":"factory","msg":"no need for resync"}
{"level":"error","ts":1644840769.8817399,"logger":"controller_vmcluster","msg":"cannot update or create vmcluster","Request.Namespace":"victoriametrics","Request.Name":"victoria-metrics-k8s-stack","error":"cannot update statefulset for vmalertmanager: timed out waiting for the condition","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1644840769.8818007,"logger":"controller.vmcluster","msg":"Reconciler error","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMCluster","name":"victoria-metrics-k8s-stack","namespace":"victoriametrics","error":"cannot update statefulset for vmalertmanager: timed out waiting for the condition","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```

**Comment by f41gh7** [comment]
Sorry for delay, it looks like, operator cannot update vmselect statefulset for some reason, pods of given statefulset doesn't become `ready`. Can you check events for given pods and it's status, probably something wrong with cluster? it doesn't have enough resource capacity for example?


 Also, it's possible to disable default rolling update mechanism and delegate it to the kubernetes controller with setting:
```
kind: VMCluster
spec:
  vmselect:
    rollingUpdateStrategy: RollingUpdate
```

 In this case, no error will be reported by operator.

**Comment by PabloL007** [comment]
No worries, thanks for looking into this at all. That's the weird thing, that they do get updated and become ready without any errors, I think the issue is that panic when the operator passes a "non-string key argument" to logging causes that check to fail so even through everything is fine it thinks that it didn't manage to update it. I'll try making that change to see if I have the same issue when using the kubernetes controller instead and update.

**Comment by PabloL007** [comment]
Tried using the rollingUpdateStrategy attribute with the Helm chart like so (note that I did notice that your snippet was for the CRD but I'm using helm so I adapted it following the spec [here](https://docs.victoriametrics.com/operator/api.html#vmselect)):
```yaml
    vmselect:
      cacheMountPath: "/select-cache"
      extraArgs:
        dedup.minScrapeInterval: 15s # https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication
      hpa:
        maxReplicas: 8
        minReplicas: 2
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                averageUtilization: 75
                type: Utilization
          - type: Resource
            resource:
              name: memory
              target:
                averageUtilization: 75
                type: Utilization
      podDisruptionBudget:
        maxUnavailable: 1
      replicaCount: 2
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
      rollingUpdateStrategy:
        type: RollingUpdate
      storage:
        emptyDir:
          sizeLimit: 2Gi
```
And got the following error (both with version 0.6.8 and 0.6.9 of the chart):
```bash
 ~ helm upgrade victoria-metrics-k8s-stack vm/victoria-metrics-k8s-stack -f temp/vmpoc.yaml -n victoriametrics
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(VMCluster.spec.vmselect): unknown field "rollingUpdateStrategy" in com.victoriametrics.operator.v1beta1.VMCluster.spec.vmselect
```
