### ISSUE TITLE
Feature: Option to add clusterName for VMAgent

### ISSUE THREAD

**Issue by micw** [VictoriaMetrics/operator#427]
I'm running VMAgent on all of my clusters and send to a central monitoring. Currently I need to add the cluster name to every agent as extra label. It would be great if the agent could do this automatically (so that I do not need to specify the cluster name for each cluster manually).

**Comment by f41gh7** [comment]
There is special setting - `vmAgentExternalLabelName`, it adds given label name (prometheus by default), to each series scrapped by vmagent with name of `VMAgent` `CR`. It's possible to define it as:

```yaml
kind: VMAgent
metadata:
   name: east-prod-dc
spec:
  vmAgentExternalLabelName: cluster
```

 in this case, all metrics scrapped by agent get label - `cluster: east-prod-dc`.

 It looks like, this setting must be also added to the ingested metrics to vmagent by push clients, but it's not implemented yet.
