### ISSUE TITLE
VMSingle labels are copied to PVC

### ISSUE THREAD

**Issue by amkartashov** [VictoriaMetrics/operator#432]
See https://github.com/VictoriaMetrics/operator/issues/90 - I can't reopen it.

Details: https://github.com/VictoriaMetrics/operator/issues/90#issuecomment-1045888479

**Comment by amkartashov** [comment]
Similar issues in other operator: https://github.com/strimzi/strimzi-kafka-operator/issues/2107

**Comment by f41gh7** [comment]
WDYT, could it be fixed by automatically adding additional annotations to the generated PVC:

```yaml

metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
```

 I'm not so familiar with ArgoCD, but label and annotation propagation is very useful for me.
