### ISSUE TITLE
VMPodScrape default relabel_config

### ISSUE THREAD

**Issue by bdronneau** [VictoriaMetrics/operator#441]
Hello,

Thank to provide this operator.
I try to scrape `kube-state-metrics` deployment on the 8081 port (in order to have `kube_state_metrics_*`).
But since it's not declare in the deployment it's seems I can not scrape it.

Here the configuration of my VMPodScrape:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: "main-kube-state-metrics"
spec:
  podMetricsEndpoints:
    - port: "8081"
      scheme: http
      relabelConfigs: []
  selector:
    matchLabels:
      app.kubernetes.io/name: "kube-state-metrics"
      app.kubernetes.io/instance: "main"
```

Generate configuration in VMAgent:
```yaml
- job_name: podScrape/monitoring/main-kube-state-metrics/0
  scheme: http
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
    regex: main
    action: keep
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
    regex: kube-state-metrics
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    regex: "8081"
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_pod_container_name]
    target_label: container
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
  - target_label: job
    replacement: monitoring/main-kube-state-metrics
  - target_label: endpoint
    replacement: "8081"
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      own_namespace: false
      names:
      - monitoring
    selectors:
    - role: pod
      label: app.kubernetes.io/instance=main,app.kubernetes.io/name=kube-state-metrics
      field: ""
```

The problèm come from

```yaml
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    regex: "8081"
    action: keep
```

I try to add `relabelConfigs` but it's merging with this "default" behavior.

Any clues ?

Best

Bastien
