### ISSUE TITLE
Dropping / Overwriting existing labels in Prometheus Operator's objects

### ISSUE THREAD

**Issue by Vladyslav-Miletskyi** [VictoriaMetrics/operator#444]
Hi,
We are using Argocd for deployments of our apps.
Some apps are creating Prometheus ServiceMonitors.

When the VM operator is deployed, it's creating VM-specific files, based on existing Prom Operator objects.

Problem:
* VM objects have labels, which identify them as part of ArgoCD Apps deployment.
* VM objects are not defined within ArgoCD Apps, so marked as `OutOfSync (requires pruning)` 
* At the end, as automated sync is `on`, those objects are deleted and then recreated by the operator, which leads to higher resources usage (ArgoCD + VM Operator)  as process is in a closed-loop

Example labels:

```yaml
labels:
  app.kubernetes.io/component: application-controller
  app.kubernetes.io/instance: argo
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/name: argocd-application-controller
  app.kubernetes.io/part-of: argocd
  helm.sh/chart: argo-cd-3.29.5
```

I've tried to set in operator's deployment

```yaml
env:
    - name: VM_LABELS
      value: app.kubernetes.io/instance=-
```
but it didn't give any effect.

How should one proceed in such a case?

**Comment by f41gh7** [comment]
I think, that it possible to implement filter logic for labels deny list.

 Something like: `VM_PROMETHEUSCONVERTERLABELPREFIXES=app.kubernetes.io/,helm.sh/`

**Comment by f41gh7** [comment]
New env variables for operator:
```
VM_FILTERPROMETHEUSCONVERTERLABELPREFIXES=filter-1,filter-2
VM_FILTERPROMETHEUSCONVERTERANNOTATIONPREFIXES=filter-1,filter-2
```

 Allows to drop matched prefixes for labels and annotations, when object is converted by operator.

**Comment by Vladyslav-Miletskyi** [comment]
@f41gh7 
using next helm chart values:

```yaml
image:
  tag: 446-merge

env:
  - name: VM_FILTERPROMETHEUSCONVERTERLABELPREFIXES
    value: app.kubernetes.io/
  - name: VM_FILTERPROMETHEUSCONVERTERANNOTATIONPREFIXES
    value: meta.helm.sh/
```

## VMRule object before :

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
    prometheus-operator-validated: "true"
  labels:
    app: monitoring
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: 16.6.0
    chart: monitoring-16.6.0
    heritage: Helm
    release: monitoring
  name: monitoring-alertmanager.rules
  namespace: monitoring
```

## After :

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  annotations:
    prometheus-operator-validated: "true"
  labels:
    app: monitoring
    chart: monitoring-16.6.0
    heritage: Helm
    release: monitoring
  name: monitoring-alertmanager.rules
  namespace: monitoring
```

Closing issue and thanks for quick solution.
