### ISSUE TITLE
allowed override vmagent volume

### ISSUE THREAD

**Issue by wenerme** [VictoriaMetrics/operator#450]
want to prevent vmagent data lost by mount

```yaml
  volumes:
  - name: persistent-queue-data
    hostPath:
      path: /data/var/vmagent/persistent-queue-data
```

operator should merge volume by name.

https://github.com/VictoriaMetrics/operator/blob/10a53e58c8dcb388e7dda62db836513fb0618e90/controllers/factory/vmagent.go#L246-L251
