### ISSUE TITLE
Operator does not generate opsgenie_config with api_key from VMAlertmanagerConfig

### ISSUE THREAD

**Issue by iyuroch** [VictoriaMetrics/operator#463]
The operator does not generate api_key from secret with kind VMAlertmanagerConfig
VMAlertmanagerConfig:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: test
  namespace: infra
  labels:
    alertmanager: yes
spec:
  receivers:
  - name: opsgenie
    opsgenie_configs:
    - api_key:
        key: opsgenieApiKey
        name: alertmanager
      send_resolved: true
```

Resulted config in alertmanager:
```
- name: infra-test-opsgenie
  opsgenie_configs:
  - send_resolved: true
```
