### ISSUE TITLE
Operator does not generate responders in opsgenie_config

### ISSUE THREAD

**Issue by iyuroch** [VictoriaMetrics/operator#465]
VMAlertmanagerConfig with following section
```
  receivers:
    - name: "opsgenie"
      opsgenie_configs:
        - send_resolved: true
          apiURL: "https://api.opsgenie.com/"
          api_key:
            name: <test>
            key: <test-key>
          responders:
            - name: <test>
              type: team
```
Will not generate responders in the output
