### ISSUE TITLE
Basic auth field incorrectly generated for alertmanager

### ISSUE THREAD

**Issue by iyuroch** [VictoriaMetrics/operator#468]
Given this spec in VMAlertmanagerConfig:
```
 - name: opsgenie_heartbeat
    webhook_configs:
    - http_config:
        basic_auth:
          password:
            key: <test>
            name: <test>
          # optional not implemented
          username:
            key: blank
            name: <test>
        url: test.com
```
Alertmanager config is 
```
  webhook_configs:
  - http_config:
      username: ':'
      password: <test>
    send_resolved: false
    url: test.com
```
