### ISSUE TITLE
VMProbe not respecting basicAuth

### ISSUE THREAD

**Issue by Bakrog** [VictoriaMetrics/operator#486]
Hi, I have a service with an endpoint behind basic authentication but when setting up a **VMProbe** with following spec I still receive 401:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  ...
  namespace: actuator-service
spec:
  basicAuth:
    password:
      key: actuator-password
      name: secret-environment
      optional: false
    username:
      key: actuator-user
      name: secret-environment
      optional: false
  interval: 30s
  jobName: basic-auth-probe
  targets:
    staticConfig:
      targets:
      - actuator.actuator-service.svc/actuator/health/liveness
  vmProberSpec:
    url: prometheus-blackbox-exporter.metrics.svc:9115
```

I do have the secret `secret-environment` with the keys `actuator-password` and `actuator-user` and he is at the same namespace as this CRD. If I use this secret to curl my application I can successfully do it but VMProbe is ignoring this configuration it seems.
I **don't** have the same problem with **VMPodScrape** definition.

**Comment by f41gh7** [comment]
Hello, sry for delay.

 Which version of `VMAgent` you're using? There was a bug, at 1.77.0-1.77.1 versions. It was fixed at 1.77.2 version of vmagent. 

 Probably, you faced this issue.

**Comment by Bakrog** [comment]
Hello @f41gh7 , I tried what you suggested and I'm still have the same problem. At blackbox exporter configuration is the following and I still get 401 because of missing `basic_auth` username and password.

```yaml
Module configuration:
prober: http
timeout: 5s
http:
    valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
    preferred_ip_protocol: ip4
    ip_protocol_fallback: true
    basic_auth:
        username: ""
    follow_redirects: true
    enable_http2: true
tcp:
    ip_protocol_fallback: true
icmp:
    ip_protocol_fallback: true
dns:
    ip_protocol_fallback: true
    recursion_desired: true
```

**Comment by f41gh7** [comment]
Hm, can you check configuration generated by operator:
 It can be done via port-forwarding for vmagent 8429 and access web-ui with configuration file.

 Also, make sure, that you're running latest operator version and if there any error messages at operator log.

 I've added more tests and for me it works.

**Comment by Bakrog** [comment]
The VMAgent shows the probe as `UP`.
<img width="2555" alt="image" src="https://user-images.githubusercontent.com/3700397/171335648-9b4c95e5-39e0-4fab-b731-51c1427530c8.png">

But as you can see it was returned 401 from the probe:

```shell
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 401
```

Is the `basicAuth` field found at `VMProbe.spec.basicAuth` related to the prober application or the endpoint that you want to probe?

Or maybe the way that I'm deploying blackbox exporter is wrongly configured.

**Comment by f41gh7** [comment]
It's related to the endpoint for probing, blackbox exporter usually. I think, that it's confusing, needed to update description for it.

 In your case, you have to create additional probe configuration section at `blackbox` configuration file with needed login and password:

https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#http_probe

example:
```yaml
modules:
... default modules
 acuator_with_auth:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      no_follow_redirects: false
      tls_config:
        insecure_skip_verify: false
     basic_auth:
       username: actuator-user
       password: actuator-password
```

 And specify probe name at `VMProbe` spec:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  ...
  namespace: actuator-service
spec:
  # instructs blackbox to use correct module with basic auth
  module: acuator_with_auth
  interval: 30s
  jobName: basic-auth-probe
  targets:
    staticConfig:
      targets:
      - actuator.actuator-service.svc/actuator/health/liveness
  vmProberSpec:
    url: prometheus-blackbox-exporter.metrics.svc:9115
```
