### ISSUE TITLE
[VMAgent] Deployment will not start if the remote write secret is created some seconds after vmagent 

### ISSUE THREAD

**Issue by sdomme** [VictoriaMetrics/operator#500]
Hello, we are facing the following issue and don't know if we maybe misunderstand the creation process for vmagent. Let me quickly summarize our process. 
We deploy a VMAgent like this
```
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
  scrapeInterval: "1m"
  serviceScrapeSelector: {}
  securityContext:
    seccompProfile:
      type: "RuntimeDefault"
    runAsNonRoot: true
    runAsUser: 1000
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: vmagent-additional.yaml
```
We also have Kyverno ClusterPolicy in place which creates a secret to use within RemoteWrite and mutate the object from above to setup RemoteWrite properly. It also looks right after that, but the deployment will not start and we see the following errors in operators log

```
[victoria-stack-victoria-metrics-operator-94dcf6d6c-pssxv] {"level":"error","ts":1657180293.9378974,"logger":"controller.vmagent","msg":"Reconciler error","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","name":"vmagent","namespace":"default","error":"cannot get remote write secrets for vmagent: cannot load scrapeSecrets for remoteWriteSpec: could not generate basicAuth for remote write spec https://vmingest.idealo.systems/api/v1/write config. basic auth username and password secret not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```

The error comes 5-7 times in a row within 1 second and stops. The operator doesn't try to start the deployment never again, even if the secret is in place.

To compare the creation time:

vmagent: creationTimestamp: "2022-07-07T07:51:32Z"
secret:     creationTimestamp: "2022-07-07T07:51:34Z"

What do you think?

**Comment by f41gh7** [comment]
Hello, according to error log message, you configured remote write basic authorization, but secret with username and password is not found at `VMAgent`'s namespace.

 ```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rw-secret
  namespace: my-ns
stringData:
   user-value: alice
   password-value: bob
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: my-ns
spec:
  remoteWrite:
 - url: https://https://vmingest.idealo.systems/api/v1/write
   basicAuth:
      username:
          key: user-value
          name: rw-secret
      password:
           key: password-value
           name: rw-secret
  scrapeInterval: "1m"
  serviceScrapeSelector: {}
  securityContext:
    seccompProfile:
      type: "RuntimeDefault"
    runAsNonRoot: true
    runAsUser: 1000
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: vmagent-additional.yaml
```
