### ISSUE TITLE
Create alerting rules for operator

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#526]
Currently it's not even how to monitor operator properly and which metrics should be tracked.

 Alerting rules should cover:
1) latency between operator and API server.
2) converter errors by object types.
3) building config errors (vmauth, vmalertmanager, vmagent, vmalert).
4) validation webhook errors.
5) runtime issues with statefulset updates. 

 Alerts should be actionable for user.

 If there is not enough metrics, add needed.

**Comment by f41gh7** [comment]
an example of alerts
```yaml

    - name: operator
      rules:
        - alert: logErrors
          expr: rate(operator_log_messages_total{level="error"}) > 0
          for: 15m
          labels:
            severity: high
          annotations:
            description: "operator has too many errors at logs: {{ $value}} check it logs"
            dashboard: "{{ $externalURL }}/d/1H179hunk/victoriametrics-operator?ds={{ $labels.dc }}&orgId=1"
        - alert: reconcileErrors
          expr: rate(controller_runtime_reconcile_errors_total{job="vm-operator-victoria-metrics-operator"}) > 0
          for: 10m
          labels:
            severity: high
          annotations:
            description: "operator cannot parse response from k8s api server, possible bug: {{ $value}}, check it logs"
            dashboard: "{{ $externalURL }}/d/1H179hunk/victoriametrics-operator?ds={{ $labels.dc }}&orgId=1"
        - alert: highQueueDepth
          expr: workqueue_depth{job="vm-operator-victoria-metrics-operator"} > 10
          for: 15m
          labels:
            severity: high
          annotations:
            description: "operator cannot handle reconciliation load for controller: {{ $labels.name }} current depth: {{ $value }}"
            dashboard: "{{ $externalURL }}/d/1H179hunk/victoriametrics-operator?ds={{ $labels.dc }}&orgId=1&viewPanel=20"
```
