### ISSUE TITLE
VMAlertSpec needs externalLabels key for multiple external labels

### ISSUE THREAD

**Issue by brokenjacobs** [VictoriaMetrics/operator#538]
Currently using extraArgs you can define only one external label:

```yaml
spec:
  extraArgs:
    external.label: mylabel=myvalue
```

But vmalert supports multiple `-external.label` arguments. And they cannot be passed in this way because it would create a duplicate field in the extraArgs map. I would like this to mirror what vmagent does like this:
```yaml
spec:
  externalLabels:
    mylabel: myvalue
    mylabel2: myvalue2
```

I haven't been able to find a workaround for this using the operator.

**Comment by zekker6** [comment]
Hello @brokenjacobs 
As far as I can see you are looking for `VMAlertSpec` (but not `VMAlertManager` as it doesn't support `external.label` flag). 
If this is correct in order to apply multiple labels you can use the following syntax:
```yaml
spec:
  extraArgs:
    external.label: "mylabel=myvalue,mylabel2=myvalue2"
```


You can find description for VMAlert cli flags here: https://docs.victoriametrics.com/vmalert.html#flags
```
  -external.label array
     Optional label in the form 'Name=value' to add to all generated recording rules and alerts. Pass multiple -label flags in order to add multiple label sets.
     Supports an array of values separated by comma or specified via multiple flags.
```
