### ISSUE TITLE
Add ability to define job kubernetes_sd_configs attach_metadata

### ISSUE THREAD

**Issue by hellorill** [VictoriaMetrics/operator#545]
We want to add specific node labels to each pod metric, but service discovery doesn't add them to targets before processing. So vmagent gets targets without node labels. I didn't find an option for the section to add attach_metadata.node: true
```
scrape_configs:
- job_name: podScrape/default/annotation-scrape/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    selectors:
    - role: pod
      label: app.kubernetes.io/managed-by=example
```

Example of required labels:
- topology.example.team/cluster=cluster1
- topology.example.team/dc=dc1
- topology.example.team/region=region1
- topology.example.team/env=dev

Possible duplication: https://github.com/VictoriaMetrics/operator/issues/534
