### ISSUE TITLE
Remove unnecessary namespaceMatch in inhibitRule

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/operator#558]
When configurate AlertManager inhibit rules, vm-operator always adds namespace to inhibit rules.
```
- source_matchers:
  - alertname="KubePodStartLooping"
  - namespace="monitoring"
  - severity="warning"
  target_matchers:
  - alertname="KubePodNotReady"
  - namespace="monitoring"
  - severity="warning"
  equal:
  - job
  - namespace
  - k8s_cluster
  - region
  - app
  - workload
  ```
The action has a limitation that the alert inhibition only affects in the specific namespace. But I want the inhibit action takes effect on all namespaces. If I need namespace limitation, I could add the namespaceMatch to `source_matchers` and `target_matchers`  by myself.
So Could we remove the unnecessary namespaceMatch in inhibitRule? Or provide a variable to enable/disable the behaviour?
