### ISSUE TITLE
Unabel to expose vminsert and vmselect endpoints in VMCluster in GCP env.

### ISSUE THREAD

**Issue by hrbapna** [VictoriaMetrics/operator#563]
We are setting up central [VM cluster ](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)in GCP to monitor and ingest metrics from many VMsingle instances. I will need to expose few private endpoints for write, read, alertmanager, grafana etc.

According to GCP documentation, the following needs to be done to expose endpoints for services running in GKE.
1. service(vminsert, vmselect) annotations
2. service(vminsert, vmselect) ingress annotations such as https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L281

I am able to achieve pt2 i.e. set annotations to ingress for vminsert, vmselect but unable to apply the service annotations for vminsert, vmselect (i.e. pt1 above)

The service manifest for the above services are generated by the VM Operator. If I apply the below config in the values.yaml then it creates a new vminsert instance **vminsert-vm-additional-service** because of https://docs.victoriametrics.com/operator/api.html#servicespec

```
vmcluster:
  spec:
    vminsert:
      serviceSpec:
         metadata:
          annotations:
            cloud.google.com/neg: '{"ingress": true}'
```

Please suggest a path forward.
