### ISSUE TITLE
Use the VMAlertManager definition to define VMAlert notify.url

### ISSUE THREAD

**Issue by qeqar** [VictoriaMetrics/operator#564]
Hello,

today we were hit by a strange problem. 
We use the operator to host a local installation, of vmsingle,vmalert, vmalertmanager and etc...

In our fist version we put the vmalertmanager endpoint in our vmalert notify.url field.

that broke glorious as we were using the alertmanger with replica 2, and the we need to define both endpoints as comma-separated url.

But as the operator has both information, it should be possible for him to set the notify.url for local alertmanager always to all local instances. 
This way it will remove this error class.

Any opinions on that? Did i miss some obvious, why it is not implemented that way?

**Comment by f41gh7** [comment]
Hello, for now there are few ways to achieve that:
1) use notifiers discovery by operator:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert
spec:
  datasource:
    url: "http://vmagent-example-vmsingle.default.svc:8429"
  notifiers:
    - selector:
        namespaceSelector:
          any: false
          matchNames:
            - default
        labelSelector:
          matchLabels:
            usage: dev
```

2) use vmalert notifier discovery with configuration file:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429"
  notifierConfigRef:
    key: notifier.yaml
    name: vmalert-notifier
  selectAllByDefault: false
---
apiVersion: v1
kind: Secret
metadata:
  name: vmalert-notifier
stringData:
  notifier.yaml: |
        dns_sd_configs:
        - names:
           - vmalertmanager-example.default.svc
                type: 'A'
                port: 9093
```

 more info for discovery at docs: https://docs.victoriametrics.com/vmalert.html#notifier-configuration-file
