### ISSUE TITLE
How to configure cpu & memory requests for config reloader 

### ISSUE THREAD

**Issue by monotek** [VictoriaMetrics/operator#602]
Currently it seems only the the cpu & memory limits for config reloader are configurable via operateor env vars.

For example via: `VM_VMALERTDEFAULT_CONFIGRELOADERMEMORY` & `VM_VMALERTDEFAULT_CONFIGRELOADERCPU`.
https://github.com/VictoriaMetrics/operator/blob/master/vars.MD#auto-generated-vars-for-package-config

Imho requests for cpu and memory are also very important as otherwise this container is always an eviction candidate.

Therefore also the requests schould be configurable as for other containers too, like vmalert which has the following settings available:
```
VM_VMALERTDEFAULT_RESOURCE_LIMIT_MEM
VM_VMALERTDEFAULT_RESOURCE_LIMIT_CPU
VM_VMALERTDEFAULT_RESOURCE_REQUEST_MEM
VM_VMALERTDEFAULT_RESOURCE_REQUEST_CPU
```

securityContext, liveness and readinessprobes should be configurable too. 
Otherwise it might be hard to fulfill policys in some clusters.

**Comment by f41gh7** [comment]
Hello, current it's possible to redefine it via containers:

```yaml
kind: VMAgent
spec:
  containers:
  # container spec will be patched with merge
  - name: config-reloader
     requests:
        cpu: 1.0
     limits:
         cpu: 2.0
```

 I'm not quite sure should be defined directly at CRD spec or containers is flexible enough.
