### ISSUE TITLE
VMAgent keepInput option not working - original metrics are dropped

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/operator#617]
### Describe the bug

I have this in my VMAgent config using the latest chart and vmagent 1.89.1.

```yaml
  remoteWrite:
    - url: "http://my-cluster"
      streamAggrConfig:
        keepInput: true
        rules:
          - match: '{__name__=~"my_metrics_.+"}'
            interval: "30s"
            outputs: ["total","increase"]
            without: ["pod", "instance"]
```

And not the aggregated metrics show up. The problem all the original metrics are gone even though `keepInput: true` is set.

### To Reproduce

Setup vmagent using the operator with a similar config as provided

### Version

1.89.1

### Screenshots

Datapoint ingest tanked once aggregation was enabled:

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/8493275/227698064-cb48d5f8-7a49-46ad-b882-04f747c131d9.png">
