### ISSUE TITLE
download configuration with init containers

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#619]
For vmauth/vmagent we have to init configuration before service start. It could be done with initContainers:

```yaml
kind: VMAgent
spec:
 initContainers:
  - args:
    - -c
    - gunzip -c /etc/vmagent/config/vmagent.yaml.gz > /etc/vmagent/config_out/vmagent.env.yaml
    command:
    - /bin/sh
    image: quay.io/prometheus-operator/prometheus-config-reloader:v0.58.0
    name: config-init
    volumeMounts:
    - mountPath: /etc/vmagent/config
      name: config
    - mountPath: /etc/vmagent/config_out
      name: config-out
```
 But it wouldn't work for custom config reloader, since it download configuration directly from secret/configmap.

 Add oneshot config download mode for config-reloader and automatically add init container with gunzip command for `prometheus-config-reloader`.
