### ISSUE TITLE
VMAlertmanger HA mode supports every node to receive alerts

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/operator#635]
From my understanding, when Alertmanager is in cluster mode, the nodes synchronize configuration and node status information with each other but not alerts. Therefore, we need to send alerts to each node. To achieve it, we usually configure multiple Alertmanager addresses on vmalert. However, this does not guarantee that every Alertmanager node will receive the alert. It also depends on the load balancing algorithm. And we often use Alertmanager across Kubernetes clusters.
Since the vmalertmanager service corresponds to multiple nodes, it is impossible to specify which node should receive an alert explicitly. If this issue is not resolved, it may cause problems such as alerts being mysteriously resolved without notification or inhibit rules not working as expected. Is there any way to solve this problem?

**Comment by f41gh7** [comment]
Hello, it's recommended to set all exist alertmanager pod endpoints as arguments for `VMAlert`'s `notifiers`. Or enable service discovery for `notifiers`.

 This behavior described at docs https://docs.victoriametrics.com/operator/high-availability.html#vmalert

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-ha
  namespace: default
spec:
  datasource:
    url: http://vmsingle-example.default.svc:8429
  notifiers:
    - url: http://vmalertmanager-example-0.vmalertmanager-example.default.svc:9093
    - url: http://vmalertmanager-example-1.vmalertmanager-example.default.svc:9093
 ```
sd
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-ha
  namespace: default
spec:
  datasource:
   url: http://vmsingle-example.default.svc:8429
  notifiers:
    - selector:
        namespaceSelector:
          matchNames: 
            - default
        labelSelector:
          matchLabels:
              usage: dedicated
```
