### ISSUE TITLE
VMAgent reconcile error

### ISSUE THREAD

**Issue by konstantin-921** [VictoriaMetrics/operator#652]
The issue appeared when I tried to upgrade Victoria Metrics operator from v0.24.0 to v0.32.1. Operator was deployed via Helm chart. For some reason VMAgent custom resource cant be upgraded or deleted. I have the following logs from operator pod:

`{"level":"error","ts":1684838761.514712,"logger":"controller.vmagent","msg":"Reconciler error","reconciler group":"operator.victoriametrics.com","reconciler kind":"VMAgent","name":"vmagent","namespace":"victoriametrics","error":"VMAgent.operator.victoriametrics.com \"vmagent\" is invalid: [status.selector: Required value, status.shards: Required value]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}`

The current error is preventing me from setting up a VMAgent new setup.

Here's what I tried to do (but nothing worked):
- deleting the CRD vmagents.operator.victoriametrics.com (this doesn't seem to remove the CR itself)
- complete removal of VM Operator, all CRDs and namespace itself, installation old v0.24.0 
- direct deletion of VMAgent CR doesn't work, trying to remove the finalizers of VMAgent CR itself didn't work either:

```
kubectl patch -f vmagent.yml --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'     
The VMAgent "vmagent" is invalid: 
* status.selector: Required value
* status.shards: Required value
```
- I also tried manually applying the patch to add the required fields, but it still does not work:
```
kubectl patch -f vmagent.yml --type json --patch='[ { "op": "add", "path": "/status/shards", "value": "0"}, { "op": "add", "path": "/status/selector", "value": ""} ]'  
The VMAgent "vmagent" is invalid: 
* status.selector: Required value
* status.shards: Required value
```

This is my vmagent.yml:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: victoriametrics
spec:
  serviceScrapeNamespaceSelector: 
    matchLabels:
      name: victoriametrics
  serviceScrapeSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  probeSelector: {}
  probeNamespaceSelector: {}
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1500Mi
    requests:
      cpu: 50m
      memory: 500Mi
  extraArgs:
    promscrape.suppressScrapeErrors: "true"
    memory.allowedPercent: "60"
  remoteWrite:
    - url: "http://vminsert-vmcluster-persistent.victoriametrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
```

I would be grateful for any help!
