### ISSUE TITLE
vmagent Role no permissions to read "secrets"

### ISSUE THREAD

**Issue by RaSerge** [VictoriaMetrics/operator#653]
operator Chart version: 0.22.0
operator version: v0.34.0
We install operator without clusterwide permissions (WATCH_NAMESPACE: "monitoring")
When i create VmAgent in "monitoring" namespace with
```
serviceScrapeNamespaceSelector: 
    matchLabels:
      name: monitoring
```
vmagent pod goes to CrashLoopBackOff status because of error
`User "system:serviceaccount:monitoring:vmagent-test-vmagent" cannot get resource "secrets" in API group "" in the namespace "monitoring"`

Corresponding serviceaccount, role and rolebinding are created by vm-operator, but role don't have permissions to read "secrets"
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: test-vmagent
    app.kubernetes.io/name: vmagent
    managed-by: vm-operator
  name: monitoring:vmagent-cluster-access-test-vmagent
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
```
