### ISSUE TITLE
vmalertmanager config: validation for slack receiver URL

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/operator#661]
Currently, in case receiver is configured via VMAlertmanagerConfig it uses reference to secret to pull slack URL:
```
- name: "slack-notifications"
  slack_configs:
    - channel: alerts
      api_url:
        key: slack_url
        name: slack-conf
```

In case secret contains some invalid URL it will lead to alertmanager being unable to start and enter `CrashLoopBackoff` quite easily.

It would be great if operator would validate that content of `key` in secret is valid URL and would not apply this change to alertmanager, but write an error in log/status field for created resource.
