### ISSUE TITLE
VMUser introduce an option for backend authorization.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#669]
It would be great to have an option to define Bearer token or Basic Auth configuration for targets.

 For instance:
```yaml
kind: VMUser
  spec
    targetRefs:
     paths:
     - static:
       - ursl: [http://host1:8429,http://host2:8429,http://host3:8429]
       basicAuth:
        password:
          key: password
          name: secretname
        username:
          key: username
         name: secretname
```

 Must produce following `vmauth` config with Authorization header:
```yaml
users:
- username: "user"
  password: "***"
  headers:
  - Authorization: Basic BASE64_ENCODED_VALUE
  url_prefix:
  - "http://host1:8429/"
  - "http://host2:8429/"
  - "http://host3:8429/"
```

 It's safe to store headers at configuration file, since it uses secure kubernetes secret.

 For multiple, url_map headers should be used.

 Related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4361
