### ISSUE TITLE
How to set vmalert.proxyURL?

### ISSUE THREAD

**Issue by strowi** [VictoriaMetrics/operator#676]
Hi,

i just started testing the operator and couldn't find a way to proxy vmalert through vmui (or vmauth), not sure yet where i need to add the route/proxy?
How can make the vmalert ui reachable?

regards,
strowi

**Comment by Haleygo** [comment]
Hello, vmalert has it's own service and can be access directly by it's endpoints, see https://docs.victoriametrics.com/vmalert.html#web. 
Also you can access vmalert in vmui by configuring `-vmalert.proxyURL command-line flag` in a [single-node](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#vmalert) or [cluster version](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#vmalert) of VictoriaMetrics.

**Comment by f41gh7** [comment]
Hello, it could be configured via extraArgs as Haleygo mentioned. 

 For instance:
```yaml
kind: VMAlert
metadata:
  name: test
  namespace: default
---
kind: VMSingle
spec:
 extraArgs:
   vmalert.proxyURL: http://vmalert-test.default.svc:8080
```
