### ISSUE TITLE
VMAgent doesn't work with VPA

### ISSUE THREAD

**Issue by sdomme** [VictoriaMetrics/operator#693]
Hello, we are trying to setup a VPA on top of a VMAgent. Unfortunately we get the following error from the VPA

`E0718 13:54:51.559558       1 cluster_feeder.go:570] Cannot get target selector from VPA's targetRef. Reason: Unhandled targetRef operator.victoriametrics.com/v1beta1 / VMAgent / application, last error Resource victoria/application has an empty selector for scale sub-resource`

Here the manifest of the VPA:
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmagent-application-vpa
  namespace: victoria
spec:
  targetRef:
    apiVersion: operator.victoriametrics.com/v1beta1
    kind: VMAgent
    name: application
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: vmagent
        maxAllowed:
          cpu: 1
```

Looking at the CRD of the VMAgent I would expect it to work since
```
 subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.shardCount
        statusReplicasPath: .status.shards
      status: {}
```

is configured. 

Adding another piece to the CRD
```
- additionalPrinterColumns:
    - description: current selector
      jsonPath: .status.selector
      name: Selector
      type: string
```
shows an empty string.

```
k get vmagent application -n victoria
NAME          SHARDS COUNT   REPLICA COUNT   SELECTOR
application   0              1
```

Any help is appreciated. Maybe we just do something wrong?
