### ISSUE TITLE
VMuser: generatePassword didnt generate any secret

### ISSUE THREAD

**Issue by iamps5** [VictoriaMetrics/operator#696]
I created VMuser as below:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: test-user
  namespace: monitoring-system
spec:
  username: test-user
  generatePassword: true
  targetRefs:
    paths:
    - /api/v1/query
    - /api/v1/query_range
    static:
      url: http://vmselect-new.monitoring-system.svc:8481/select/0/prometheus
```

After deploying above VMuser,  I should have a secret with `vmuser-test-user` in `monitoring-system` namespace. But no secret got created.

Reference: https://github.com/VictoriaMetrics/operator/blob/622cf84b164584525289cc5c1f180511852c73cb/controllers/factory/vmuser.go#L618

**Comment by Haleygo** [comment]
Is there vmauth in your cluster?
Secret for vmuser will be created when they got matched with vmauth
https://github.com/VictoriaMetrics/operator/blob/622cf84b164584525289cc5c1f180511852c73cb/controllers/factory/vmuser.go#L53-L54

**Comment by iamps5** [comment]
Yes, vmauth is already been deployed.

**Comment by iamps5** [comment]
Below is the config for `vmauth`
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  finalizers:
  - apps.victoriametrics.com/finalizer
  generation: 28
  labels:
    argocd.argoproj.io/instance: victoria-metrics
  name: test-vmauth
  namespace: monitoring-system
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: managed-by
            operator: In
            values:
            - vm-operator
        topologyKey: topology.kubernetes.io/zone
  extraArgs:
    logInvalidAuthTokens: "true"
  image:
    tag: v1.91.3
  nodeSelector:
    foo: bar
  podDisruptionBudget:
    maxUnavailable: 1
  podMetadata:
    annotations:
      sidecar.istio.io/inject: "true"
  replicaCount: 4
  resources:
    limits:
      cpu: 600m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: foo
        app.kubernetes.io/name: vmauth
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
  userSelector:
    matchLabels:
      foo: bar

```
