### ISSUE TITLE
Using meta labels in VMServiceScrape's label selector

### ISSUE THREAD

**Issue by kyu-clover** [VictoriaMetrics/operator#705]
It would be nice for [VMServiceScrape](https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec)'s selector, if it can use meta labels defined in [kubernetes_sd_configs](https://docs.victoriametrics.com/sd_configs.html#kubernetes_sd_configs), i.e. `__meta_kubernetes_service_annotation_<annotationname>`.
So we can have something like
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: stackdriver-scrape
spec:
  selector:
    matchLabels:
      __meta_kubernetes_service_annotation_prometheus_io_scrape: stackdriver-exporter
  discoveryRole: service
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
  ```

**Comment by AndrewChubatiuk** [comment]
hey @kyu-clover 
it can be done by relabelling (see example below), not sure it's reasonable to mix meta labels and service labels in matchLabels. what are you trying to achieve with this feature?

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: stackdriver-scrape
spec:
  discoveryRole: service
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      relabelingConfigs:
       - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
         action: keep
         regex: "stackdriver-exporter"
```
