### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by elmariofredo** [VictoriaMetrics/operator#71]
I understand that it's early and not priority just want to raise my hand that my raspberry pi 4 64bit cluster is forced to use prometheus-operator. So please if it's not that big of a issue let's make it happen 🙏

**Comment by f41gh7** [comment]
Hello, 

  Wow, pi cluster, it  sounds interesting)

  I guess, its very simple and i will add cross compilation into next release.

**Comment by elmariofredo** [comment]
That would be fantastic 😍 let me know if you will need any testing or other support. Thanks!

**Comment by f41gh7** [comment]
i've added cross compilation, you can test operator with docker image: `victoriametrics/operator:cross-compilation-arm64`.
 I've tested it at aws arm, it was able to start.

 Also, you have to have change values for it, apply patch: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: vm-operator
  name: vm-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: VM_VMALERTDEFAULT_VERSION
          value: v1.40.0-arm64
        - name: VM_VMAGENTDEFAULT_VERSION
          value: v1.40.0-arm64
        - name: VM_VMSINGLEDEFAULT_VERSION
          value: v1.40.0-arm64
        - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_VERSION
          value: v1.40.0-cluster-arm64
        - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_VERSION
          value: v1.40.0-cluster-arm64
        - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_VERSION
          value: v1.40.0-cluster-arm64
        - name: VM_VMALERTMANAGER_ALERTMANAGERVERSION
          value: v0.20.0-arm64
        - name: VM_VMALERTMANAGER_CONFIGRELOADERIMAGE
          value: jimmidyson/configmap-reload:v0.4.0-arm64
        - name: VM_VMALERTDEFAULT_CONFIGRELOADIMAGE
          value: jimmidyson/configmap-reload:v0.4.0-arm64
        - name: VM_VMAGENTDEFAULT_CONFIGRELOADIMAGE
          value: quay.io/coreos/prometheus-config-reloader:v0.41.1-arm64
 
```

 Let me know, if something go wrong.

**Comment by elmariofredo** [comment]
Great! Operator is up and running I will test it over weekend and will let you know. 

p.s. Have you considered multi arch docker image https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ ? It's under experimental flag for building stage, but it works without any intervention for users. Then we don't need to do image tag patching.

**Comment by f41gh7** [comment]
Thanks, docker buildx  looks interesting. Need to check, is it working with other container-runtime systems, like podman.

**Comment by elmariofredo** [comment]
For podman building it doesn't seems to work there is ongoing work under buildah https://github.com/containers/buildah/issues/1590, but run should work just fine as it's part of OCI since 2017 https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#manifest-list-field-descriptions

**Comment by elmariofredo** [comment]
I had to fix slightly patch file as follows:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: vm-operator
  name: vm-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: VM_VMALERTDEFAULT_VERSION
          value: v1.40.0-arm64
        - name: VM_VMAGENTDEFAULT_VERSION
          value: v1.40.0-arm64
        - name: VM_VMSINGLEDEFAULT_VERSION
          value: v1.40.0-arm64
        - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_VERSION
          value: v1.40.0-cluster-arm64
        - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_VERSION
          value: v1.40.0-cluster-arm64
        - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_VERSION
          value: v1.40.0-cluster-arm64
        - name: VM_VMALERTMANAGER_ALERTMANAGERVERSION
          value: v0.20.0
        - name: VM_VMALERTMANAGER_CONFIGRELOADERIMAGE
          value: jimmidyson/configmap-reload:v0.4.0
        - name: VM_VMALERTDEFAULT_CONFIGRELOADIMAGE
          value: jimmidyson/configmap-reload:v0.4.0
        - name: VM_VMAGENTDEFAULT_CONFIGRELOADIMAGE
          value: quay.io/coreos/prometheus-config-reloader:v0.41.1-arm64
```

as `jimmidyson/configmap-reload` and `quay.io/prometheus/alertmanager` are multiarch images 😉

I have also run into small issue with alertmanager, but that was simple typo in examples alertmanager config and I have created fixing MR here https://github.com/VictoriaMetrics/operator/pull/79.

Let me know if you want to for now focus on other priorities than figuring multiarch images and I can add ARM patch file to docs examples so other ARM fanatics can start operator easily.
