### ISSUE TITLE
failed edit vmagent deployment

### ISSUE THREAD

**Issue by Nello-Angelo** [VictoriaMetrics/operator#718]
![Screenshot_8](https://github.com/VictoriaMetrics/operator/assets/82488489/a4567db1-a2dd-4727-9d71-dcfdbe5b27a6)

this happend with existing deployment resource

**Comment by Haleygo** [comment]
Hello!
Can you elaborate the problem here? 
Just from this error message, looks like there is a connection error to apiserver.

**Comment by Nello-Angelo** [comment]
can you test this moment in your cluster but not in minikube
if in your cluster it will work correct - i will clouse the issue

**Comment by Haleygo** [comment]
> can you test this moment in your cluster but not in minikube if in your cluster it will work correct - i will close the issue i have cluster version

I don't really understand what's the connection between "deployment not found" and "running on cluster instead of minikube".
If you are getting that error from editing vmagent deployment, how about edit other deployments, do they have the same error or not?
Can you get the vmagent deployment successfully first, if there is still error, can you check the log in apiserver?

**Comment by Nello-Angelo** [comment]
i will close issue because i could edit via kubectl but i dont understand why i could edit via lens

**Comment by Nello-Angelo** [comment]
unfortunately, even through edit, I could not change the deployment, although I am with admin rights

**Comment by f41gh7** [comment]
Hello, instead of editing deployment, you have to edit `vmagent` CRD  object. All changes applied to the deployments managed by operator will be overwritten on the next reconcile loop.

**Comment by Haleygo** [comment]
> i want to add resources because it`s always throttling and i get alerts because of that

Sure, you can modify the default config-reloader's resources by changing corresponding [env](https://docs.victoriametrics.com/operator/vars.html?highlight=VM_VMAGENTDEFAULT_RESOURCE_REQUEST_CPU) in vm-operator's deployment, in this case are `VM_VMAGENTDEFAULT_RESOURCE_REQUEST_CPU` and `VM_VMAGENTDEFAULT_RESOURCE_REQUEST_MEM`.

**Comment by Nello-Angelo** [comment]
``` 
 env:
    - name: VM_VMAGENTDEFAULT_CONFIGRELOADERCPU
      value: 300m
    - name: VM_VMAGENTDEFAULT_CONFIGRELOADERMEMORY	
      value: 100Mi
    - name: VM_VMALERTMANAGER_CONFIGRELOADERCPU
      value: 300m
    - name: VM_VMALERTMANAGER_CONFIGRELOADERMEMORY	
      value: 100Mi
    - name: VM_VMALERTDEFAULT_CONFIGRELOADERCPU
      value: 300m
    - name: VM_VMALERTDEFAULT_CONFIGRELOADERMEMORY	
      value: 100Mi
```
