### ISSUE TITLE
VMProbe is not following the scheme

### ISSUE THREAD

**Issue by nidhirpatil** [VictoriaMetrics/operator#721]
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  labels:
    app.kubernetes.io/instance: <>
  name: blackbox-prober
  namespace: istio-system
spec:
  interval: 30s
  module: http_2xx
  targets:
    ingress:
      selector:
        matchLabels:
          monitoring: blackbox_exporter
  vmProberSpec:
    scheme: https
    url: <url>
```
This is my vmprobe definition, however the endpoints are still being probed with http. The resulting endpoint is of format: https://blackbox-exporter/probe?module=http_2xx&target=http://ingress-url. 
Is there any other way to specify to scrape endpoints over https?
