### ISSUE TITLE
Cannot pass multiple retentionFilter flags

### ISSUE THREAD

**Issue by farcaller** [VictoriaMetrics/operator#727]
VMCluster.spec.vmstorage.extraArgs is a map of string to string, and [retention filters](https://docs.victoriametrics.com/#retention-filters) uses a repeated flag. What is the expected mechanism to pass several retention filters to vmstorage if it's deployed via the operator?

**Comment by Haleygo** [comment]
Hello!
You can put them in the ExtraArgs like
```
    vmstorage:
      extraArgs:
        dedup.minScrapeInterval: 60s
        retentionFilter: "{env="dev"}:3d,{env="poc"}:4d"
```
