### ISSUE TITLE
Statefulset OnDelete Limitation and Enhancement

### ISSUE THREAD

**Issue by mohammadkhavari** [VictoriaMetrics/operator#744]
While using vmcluster, rolling and updating vmstorage and vmselect we can't actually use OnDelete policy, cause when updateStrategy is OnDelete, victoriametrics operator will delete sts pods accordingly, this feature was added due to this issue. #344 
the problem here is when we apply a minor change in vmstorage configurations operator will delete vmstorage pods in order and vminserts will start rerouting, all storage nodes will face pending indexdb items as soon as new timeseries arrive, and this leads to metrics loss in the pipeline, our vmcluster can tolerate one storage node downtime without metric loss, but multiple storage node downtime is troublesome.
Is there any way that we can actually use OnDelete Strategy on vmstorage statefulsets, or even a parameter like stsPodsRollingDelay can be save us from downtime, a time that operator waits between recreating each vmstorage pod.
In fact we can turn off the operator and update statefulset and vmcluster objects and delete pods accordingly, but if we make a mistake in consistency between our manually edited sts and the sts that vmcluster will generate (that cause different revisions), by activating operator pods may recreated again.

**Comment by Haleygo** [comment]
Hello! That's a very good case to consider!
>Is there any way that we can actually use OnDelete Strategy on vmstorage statefulsets

From the [commit](https://github.com/VictoriaMetrics/operator/commit/53b34c6dfe35efbd158e0844afe2b6cdd1d98de6), operator will take over the rolling update process if `rollingUpdateStrategy=OnDelete`, that should cover some corner cases, so I don't think it's recommended to use the real OnDelete Strategy.

>or even a parameter like stsPodsRollingDelay can be save us from downtime, a time that operator waits between recreating each vmstorage pod.

Since both `OnDelete` and `RollingUpdate` wait pod to be ready to delete the next one, I'm thinking you can increase `successThreshold` or `periodSeconds` under vmstorage's readinessProbe, that should prolong the pod ready duration and let vmstorage cluster to be more stable. For example
```
   readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /health
        port: 8482
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 6 // under this setting, vmstorage pod will wait at least 60s to become ready, but it will start working before that 
      timeoutSeconds: 5
```

**Comment by f41gh7** [comment]
I think, it's a global vmcluster issue. Changing rolling update strategy or increasing delays between component updates don't help much in this case.

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4922

**Comment by Haleygo** [comment]
Hey @mohammadkhavari,
Starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html), you can set `-storage.vminsertConnsShutdownDuration` command-line flag at vmstorage to gradual close vminsert connections during vmstorage graceful shutdown, see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#improving-re-routing-performance-during-restart) for more details.

**Comment by dctrwatson** [comment]
`storage.vminsertConnsShutdownDuration` has no effect when using `OnDelete` strategy because the operator has a hard-coded 30s timeout:
https://github.com/VictoriaMetrics/operator/blob/e261c37dc973154ff71073d7213000421416bd4e/controllers/factory/k8stools/sts.go#L194

Instead, the deletion grace period should probably use `TerminationGracePeriodSeconds` instead. Since a user will need to properly set that too.

**Comment by just1900** [comment]
@Haleygo @f41gh7 
Hello, I would like to follow up on this. Do you guys still consider the implementation of a feature like `stsPodsRollingDelay` or a mechanism to better control the interval between pod restarts during an update.

While I have tried configuring `-storage.vminsertConnsShutdownDuration` as suggested, we are still facing significant challenges:

**Rerouting Jitter:** Even with vminsertConnsShutdownDuration configured, we still face performance drop due to the rerouting mechanism during the rolling update, especially that we're wrting data with replicationFactor =2 https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8044. The current graceful shutdown isn't fully preventing the impact on the ingestion pipeline, or maybe we need to increase the duration?

**Configuration Catch-22:** It is difficult to set a "perfect" vminsertConnsShutdownDuration once and for all. As the cluster scale grows, this parameter often needs tuning. However, modifying this parameter requires a rolling update of the vmstorage StatefulSet, which triggers the exact instability and potential metric loss we are trying to avoid.

Having a controllable delay (e.g., stsPodsRollingDelay) at vm operator level between the operator's recreation of pods would give the cluster enough time to stabilize, making operations much safer at scale.

**Comment by f41gh7** [comment]
Pod upgrade delay is already controlled by `minReadySeconds` param. It's a delay between Pod transited into `ready` state and next Pod upgrade start:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: main-2
spec:
  retentionPeriod: "4"
  replicationFactor: 1
  clusterVersion: v1.130.0-cluster
  vminsert:
    replicaCount: 1
  vmselect:
    replicaCount: 2
  vmstorage:
    minReadySeconds: 40
    terminationGracePeriodSeconds: 60
```


 Also, you may consider to adjust `terminationGracePeriodSeconds` param as well.
