### ISSUE TITLE
VMOperator drops Ingress created without using it

### ISSUE THREAD

**Issue by thunderbird86** [VictoriaMetrics/operator#758]
### Describe the bug

VMOperator drops Ingress created without using it if it has the same name as an operator-managed resource. Probably it can be related not only to Ingress but to other resources too

### To Reproduce

Deploy resource using VMOperater e.g. vmauth
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vmauth-sample
spec:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 850Mi
    requests:
      cpu: 250m
      memory: 350Mi
  selectAllByDefault: true
```
Deploy Ingress using kubectl
```
---
apiVersion: v1
kind: Service
metadata:
  name: vmauth-sample
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 8427
      protocol: TCP
      targetPort: 8427
  selector:
    app.kubernetes.io/name: vmauth
```
### Expectation

Both resources work fine

### Actual Result

VMOperator drops ingress
