### ISSUE TITLE
VMAlertmanager permission problems with persistent storage configuration

### ISSUE THREAD

**Issue by Munsio** [VictoriaMetrics/operator#762]
### Describe the bug

In the Operator way when creating a `VMAlertmanager` CRD Object it is possible to define a `spec.storage.volumeClaimTemplate` for persistent storage of logs and silence rules from Alertmanager.

Unfortunately the user with witch the directory is mounted is the `root` user and the pod runs as `nobody` with such a configuration the alertmanager is not able to persist the data.

I know this is only applicable when not using multiple replicas of Alertmanager .

I was able to use an `initContainer` to chown the mounted directory before. Maybe this could be added in the Documentation?

### To Reproduce

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: example-alertmanager
spec:
  replicaCount: 1
  selectAllByDefault: true
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        storageClassName: ceph-rbd-sc
  extraArgs:
    data.maintenance-interval: 5m
  initContainers:
    - name: volume-mount-hack
      image: busybox
      command: ['sh', '-c', 'chown -R 65534:65534 /alertmanager']
      volumeMounts:
        - name: vmalertmanager-example-alertmanager-db
          mountPath: /alertmanager
```

### Version

victoria-metrics-operator-0.27.0 chart with version 0.38.0
