### ISSUE TITLE
default resources missing for config-init container

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#767]
It caused following errors when creating VMAgent/VMauth components:

```bash
Warning  FailedCreate  19s                replicaset-controller  Error creating: pods "vmagent-vm-victoria-metrics-k8s-stack-64d6f94466-r58xk" is forbidden: failed quota: stag-hoothoot: must specify │
│  limits.cpu for: config-init; limits.memory for: config-init; requests.cpu for: config-init; requests.memory for: config-init    
```

 Regression after https://github.com/VictoriaMetrics/operator/issues/619

 Current workaround, patch container manually:

```
kind: VMAgent
spec:
  initContainers:
    - name: config-init
       resources:
         limits:
            cpu: 10m
            memory: 52Mi
         requests:
            cpu: 10m
            memory: 52Mi
```
