### ISSUE TITLE
VMAgent deployment is broken in 0.39.0 (helm chart)

### ISSUE THREAD

**Issue by romancin** [VictoriaMetrics/operator#782]
Hi! I have just updated operator to 0.39.0 to fix endpointslices problem, but currently, I think the operator is broken. When creating VMAgent, the operator gives this error:
```
{"level":"error","ts":1696585730.0939028,"msg":"Reconciler error","controller":"vmagent","controllerGroup":"operator.victoriametrics.com","controllerKind":"VMAgent","VMAgent":{"name":"vmagent","namespace":"victoriametrics"},"namespace":"victoriametrics","name":"vmagent","reconcileID":"06d0976d-6018-4677-a711-b8174e3d3b35","error":"cannot create vmagent role and binding for it, err: cannot ensure state of vmagent's cluster role: clusterroles.rbac.authorization.k8s.io \"monitoring:vmagent-cluster-access-vmagent\" is forbidden: user \"system:serviceaccount:victoriametrics:vmagent-victoria-metrics-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:victoriametrics\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"discovery.k8s.io\"], Resources:[\"endpointslices\"], Verbs:[\"get\" \"list\" \"watch\"]}","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
```
It seems the problem is in the Helm Chart, correct permissions are given for the SA created by the operator for the agent, but the clusterrole for the operator still includes endpointslices in "" api group, so maybe it is failing because of this?:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  creationTimestamp: '2023-10-06T09:16:10Z'
  labels:
    app.kubernetes.io/instance: vmagent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-operator
    helm.sh/chart: victoria-metrics-operator-0.27.2
  name: vmagent-victoria-metrics-operator
rules:
....
  - apiGroups:
      - ''
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - endpointslices
      - configmaps
      - nodes/metrics
      - namespaces
    verbs:
      - get
      - list
      - watch
```      
https://github.com/VictoriaMetrics/helm-charts/blob/251c6febb323059c79a71667e528c18717267444/charts/victoria-metrics-operator/templates/role.yaml#L57
