### ISSUE TITLE
How to disable using of /cache pvc in the vmselect operator api ? 

### ISSUE THREAD

**Issue by sergeyignatov** [VictoriaMetrics/operator#810]
It used to be a  way to do that by setting `cacheMountPath: ""` , but that workaround was removed in the commit https://github.com/VictoriaMetrics/operator/commit/e00fe2151b71be569010840dc01947cb2747f4c1#diff-b32857448a43b22bdf1f1c14d83d7526819040c9b84d703b1a8564463707b939R344
What's the other way to stop mount pvc and  disable vmselect cache ?

**Comment by f41gh7** [comment]
> It used to be a way to do that by setting `cacheMountPath: ""` , but that workaround was removed in the commit [e00fe21#diff-b32857448a43b22bdf1f1c14d83d7526819040c9b84d703b1a8564463707b939R344](https://github.com/VictoriaMetrics/operator/commit/e00fe2151b71be569010840dc01947cb2747f4c1#diff-b32857448a43b22bdf1f1c14d83d7526819040c9b84d703b1a8564463707b939R344) What's the other way to stop mount pvc and disable vmselect cache ?

 Actually, it's not possible to disable cache completely for vmselect. Even with empty value, vmselect still uses tmp folder for data processing. When vmselect receives big number of blocks from vmstorage, it saves it into disk folder and processes it later.

 Those change was added to correctly apply security policy.

 Can you elaborate more why you want to disable those cache?

**Comment by sergeyignatov** [comment]
Our k8s boot disk is already big enough to fit /tmp/searchResults and no need to pay extra for pvc. 
So would be good to have such an option again to disable using pvc in favor of boot disk.

**Comment by AndrewChubatiuk** [comment]
starting release 0.69.0 it's possible to mount host path. for vmstorage volume name should be `vmstorage-db`, for vmselect - `vmselect-cachedir`
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
spec:
  vmstorage:
    volumes:
      - name: vmstorage-volume
        hostPath:
          path: /data/victoria/storage
  vmselect:
    volumes:
      - name: vmselect-cachedir
        hostPath:
          path: /data/victoria/select
```
