### ISSUE TITLE
[VMAlert] cr.spec.Notifier, cr.spec.notifierConfigRef and discovered alertmanager are empty prevent using flag notifier.blackhole

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/operator#811]
I am currently using the VictoriaMetrics Operator version: victoria-metrics-k8s-stack-0.18.6.
I want to deploy VMAlert `just for using recording rule` so I don't need to configure the spec.notifier and I used spec.extraArgs to enable flag `notifier.blackhole: "true"`.
The configuration file looks like this:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert-vm-k8s
  namespace: monitoring
spec:
  datasource:
    url: "http://vmselect-vm-k8s-victoria-metrics-k8s-stack.monitoring:8481/select/0/prometheus"
  remoteWrite:
    url: "http://vminsert-vm-k8s-victoria-metrics-k8s-stack.monitoring:8480/insert/0/prometheus"
  remoteRead:
    url: "http://vmselect-vm-k8s-victoria-metrics-k8s-stack.monitoring:8481/select/0/prometheus"
  evaluationInterval: "30s"
  ruleSelector:
    matchLabels:
     metric: "true"
  ruleNamespaceSelector: 
    matchLabels:
      kubernetes.io/metadata.name: monitoring
  # for accessing to vmalert via vmauth with path prefix
  extraArgs:
    http.pathPrefix: /vmalert
    notifier.blackhole: "true"
```

It seems like we have a bug here.
We can not left the cr.spec.Notifier, cr.spec.notifierConfigRef empty If we do the operator can not create VMAlert pod.
But when you enter a random URL just like in the configuration file above, the VMAlert pod shows error:
```
2023-11-22T08:42:55.943Z	fatal	VictoriaMetrics/app/vmalert/main.go:170	failed to init: failed to init notifier: only one of -notifier.blackhole, -notifier.url and -notifier.config flags must be specified
```

**Comment by Haleygo** [comment]
We should allow `notifier` and `notifiers` both to be empty at the first space, since vmalert only needs `-notifier.url ` when there is alerting rules and operator can't check that.

**Comment by Haleygo** [comment]
Should be fixed since [0.39.4](https://github.com/VictoriaMetrics/operator/releases/tag/v0.39.4), close as completed.

**Comment by tantm3** [comment]
Thank @Haleygo for your support!

**Comment by iPapanya** [comment]
I have the same problem. After updating to chart version 0.19.4 with app version v1.99.0 get error message on vmalert 
`2024-03-08T05:32:06.703Z fatal VictoriaMetrics/app/vmalert/main.go:162 failed to init: failed to init notifier: only one of -notifier.blackhole, -notifier.url and -notifier.config flags must be specified`
and I see in pods args
```
-datasource.url=http://vmsingle-vm-victoria-metrics-k8s-stack.vm.svc:8429/
-evaluationInterval=30s
-external.label=cloud=npe
-external.label=cluster=k8s-pcidss-dev
-httpListenAddr=:8080
-notifier.blackhole=true
-notifier.url=
-remoteRead.url=http://vmsingle-vm-victoria-metrics-k8s-stack.vm.svc:8429/
-remoteWrite.disablePathAppend=true
-remoteWrite.url=http://vmagent-vm-victoria-metrics-k8s-stack.vm.svc:8429/api/v1/write
-rule="/etc/vmalert/config/vm-vm-victoria-metrics-k8s-stack-rulefiles-0/*.yaml"
```

but in chart I don't write notifier.url arg

my values

```
vmalert:
  annotations: {}
  enabled: true

  # Controls whether VMAlert should use VMAgent or VMInsert as a target for remotewrite
  remoteWriteVMAgent: true
  # spec for VMAlert crd
  # https://docs.victoriametrics.com/operator/api.html#vmalertspec
  spec:
    selectAllByDefault: true
    image:
      tag: v1.99.0
    evaluationInterval: 30s
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "600m"
    nodeSelector:
      node-role: victoria-metrics
    tolerations:
      - key: "node-role"
        operator: "Equal"
        value: "victoria-metrics"
        effect: "NoSchedule"
    extraArgs:
      notifier.blackhole: "true"
```
