### ISSUE TITLE
How can scrape support consul through operator

### ISSUE THREAD

**Issue by leogoing** [VictoriaMetrics/operator#847]
hellow guys,  consul configuration is not found in scrape crd.  Can anyone help me

**Comment by Haleygo** [comment]
Hi,
I'm afraid it's not available now, should be added in https://github.com/VictoriaMetrics/operator/issues/803

**Comment by leogoing** [comment]
ok, thank u very much

**Comment by f41gh7** [comment]
Must be fixed at [v0.43.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.43.0) release 

 Operator now supports scrape config,  it's possible to configure consul discovery via it. See full docs at https://docs.victoriametrics.com/operator/api/#vmscrapeconfigspec

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: example-scrape-consul
  labels:
    some-label: new 
  annotations:
    scrape: annotation
spec:
  staticConfigs: []
  fileSDConfigs: []
  httpSDConfigs: []
  kubernetesSDConfigs: []
  consulSDConfigs:
    - server: http://consul.consul.svc:8081
  dnsSDConfigs: []
  ec2SDConfigs: []
  azureSDConfigs: []
  gceSDConfigs: []
  openstackSDConfigs: []
  digitalOceanSDConfigs: []
  relabelConfigs: []
  metricRelabelConfigs: []
  metricsPath: null
  scrapeInterval: "10s"
  scrapeTimeout: "30s"
  seriesLimit: 0
  sampleLimit: 0
  tlsConfig: null
  oauth2: null
  authorization: null
  basicAuth: null
  proxyURL: null
  follow_redirects: null
  vm_scrape_params: null
```
