### ISSUE TITLE
support: when deleting vmcluster, the related pvc was not deleted

### ISSUE THREAD

**Issue by hansedong** [VictoriaMetrics/operator#848]
I encountered a problem when deploying vmcluster: the PVCs automatically created by the operator were not deleted when the vmcluster was deleted. 

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-nfs
  namespace: monitor
spec:
  replicationFactor: 2
  retentionPeriod: 30d
  vmstorage:
    replicaCount: 5
    image:
      repository: victoriametrics/vmstorage
      tag: v1.96.0-cluster
      pullPolicy: Always
    storageDataPath: "/vm-data"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vmstorage"
          topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 500Gi
    resources:
      limits:
        cpu: "20"
        memory: 10240Mi
  vmselect:
    replicaCount: 3
    image:
      repository: victoriametrics/vmselect
      tag: v1.96.0-cluster
      pullPolicy: Always
    cacheMountPath: "/select-cache"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vmselect"
          topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
    resources:
      limits:
        cpu: "8"
        memory: "4096Mi"
  vminsert:
    replicaCount: 5
    image:
      repository: victoriametrics/vmselect
      tag: v1.96.0-cluster
      pullPolicy: Always
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vminsert"
          topologyKey: "kubernetes.io/hostname"
    resources:
      limits:
        cpu: "8"
        memory: "4096Mi"
```

This issue is 100% reproducible, and I would like to know if this is by design or a bug in the operator?
