### ISSUE TITLE
VMAgent Stops Scraping Metrics in WatchNamespace Mode

### ISSUE THREAD

**Issue by knechtionscoding** [VictoriaMetrics/operator#886]
I currently have the VM Operator installed into the victoria-metrics-operator namespace. I have a VMCluster installed into the victoria-metrics namespace. In the victoria-metrics namespace I have a number of VMServiceScrapes, VMPodScrapes, etc.

Here is an example of the VMPodScrape:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kubernetes-pods
spec:
  podMetricsEndpoints:
    - scheme: http
      scrape_interval: 1m
      scrapeTimeout: 10s
      relabelConfigs:
...
  selector: {}
  namespaceSelector:
    any: true
```
When the VM Operator is running in Cluster mode metrics are properly scraped from all pods in all namespaces.

However, when I swap the VM Operator to only watch the victoria-metrics namespace:

```
watchNamespace: victoria-metrics
```

Then metrics are no longer scraped by VMAgent from pods in non victoria-metrics namespaces.

I've granted the correct Cluster role and Role  to VMAgent with a specific CustomServiceAccount:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent
rules:
- apiGroups:
  - ""
  - networking.k8s.io
  - extensions
  - discovery.k8s.io
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - endpointslices
  - pods
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  - /metrics/resources
  verbs:
  - get
- apiGroups:
  - route.openshift.io
  - image.openshift.io
  resources:
  - routers/metrics
  - registry/metrics
  verbs:
  - get
```

I've also confirmed that the VM Operator has rbac into the victoria-metrics namespace per [this](https://docs.victoriametrics.com/operator/configuration/#namespaced-mode)

I can also see the VMPodScrape referenced as found by the VM Operator in NamespacedMode:

```
victoria-metrics-operator-8494975597-7qs59 victoria-metrics-operator {"level":"info","ts":1709297411.4290285,"logger":"factory","msg":"selected PodScrapes","podscrapes":"victoria-metrics/all-scrape,victoria-metrics/kubernetes-pods,victoria-metrics/kubernetes-pods-secondary,victoria-metrics/kubernetes-pods-slow","namespace":"victoria-metrics","vmagent":"..."}
```

I'm very confused why this is occuring/what I've missed about watchNamespace mode.

My end goal is to limit the permissions of the victoria-metrics operator while still having the VM Cluster/VM Agent get metrics from an entire cluster.
