### ISSUE TITLE
ServiceMonitor conversion drops "attachMetadata"

### ISSUE THREAD

**Issue by k1rk** [VictoriaMetrics/operator#893]
Hi
During automatic resource conversion by operator seems like data inside `attachMetadata` is lost

Following ServiceMonitor
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  attachMetadata:
    node: true
  endpoints:
    - metricRelabelings:
        - action: drop
          regex: /var/lib/kubelet/pods.+
          sourceLabels:
            - mountpoint
      port: metrics
      scheme: http
      scrapeTimeout: 10s
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-exporter
      app.kubernetes.io/name: node-exporter
```

results in following VMServiceScrape
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
    - attach_metadata: {}
      metricRelabelConfigs:
        - action: drop
          regex: /var/lib/kubelet/pods.+
          sourceLabels:
            - mountpoint
      port: metrics
      scheme: http
      scrapeTimeout: 10s
  jobLabel: app.kubernetes.io/name
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-exporter
      app.kubernetes.io/name: node-exporter
```

as you can see now `attach_metadata` is an empty object

no errors observed in VMOperator logs
