### ISSUE TITLE
VMAgent livenessProbe not using TLS

### ISSUE THREAD

**Issue by lassizci** [VictoriaMetrics/operator#896]
I have VMAuth with tls enabled and with:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vmauth
  namespace: monitoring
spec:
  image:
    tag: v1.99.0
  secrets:
    - vmauth-cert
  extraArgs:
    tls: "true"
    tlsCertFile: /etc/vm/secrets/vmauth-cert/tls.crt
    tlsKeyFile: /etc/vm/secrets/int-vmauth-cert/tls.key
```

the container spec has:
```
    livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /health
        port: 8427
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /health
        port: 8427
        scheme: HTTPS
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
```

So the `livenessProbe` doesn't have proper `scheme` while `readinessProbe` does. As a result the container keeps crashing.

The operator image is `docker.io/victoriametrics/operator:v0.42.2`
