### ISSUE TITLE
Question: How Does VMStorage Handle Data Duplication from Asynchronous Scrapes by VMAgent Instances?

### ISSUE THREAD

**Issue by hansedong** [VictoriaMetrics/operator#898]
I have been trying to use VictoriaMetrics in our infrastructure to replace the Prometheus architecture I used before to solve the problem of time series data storage, especially, I hope VictoriaMetrics can achieve data of automation collection and data storage high availability.

Based on my current understanding of VictoriaMetrics, in VMCluster, data replication can be achieved by defining `replicationFactor: 2`. This means that when collecting data from a Target, there will be 2 replicas of the data stored in the VMStorage instances in the cluster.

In addition, to solve the HA problem of VMAgent, this CRD resource also has a `replicaCount: 2` field, which can be configured with multiple copies.

I have a doubt, which is whether this situation could lead to storing the data as 4 copies?

Currently, I understand that in the process of VMAgent->VMInsert->VMStorage, VMStorage has a mechanism `dedup.minScrapeInterval: 3s` to avoid duplicate storage of time-series data for the same target.

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
  namespace: monitor
spec:
  replicationFactor: 2
  retentionPeriod: 60d
  vmstorage:
    replicaCount: 5
    vmBackup:
      acceptEULA: false
      concurrency: 5
      destination: "s3://product/victoria-metrics-backup"
      customS3Endpoint: https://microservices-1258295365.cos.ap-beijing.myqcloud.com
      credentialsSecret:
        name: tencent-s3-remote-storage-keys
        key: credentials.json
    extraArgs:
      dedup.minScrapeInterval: 3s
```

However, for multiple VMAgents, for example, instances agent-1-0 and agent-1-1, their instance startup cycle and data collection cycle may be different. For example, it is possible that agent-1-0 collects data in a cycle of 0-10-20, while agent-1-1 collects data in a time cycle of 5-15-25. 

In this case, does it mean that `dedup.minScrapeInterval: 3s` has no effect and ultimately results in the data becoming a 4-replica?

Hope to get clarification, thanks a lot.
