### ISSUE TITLE
argocd misbehaves if removePvcAfterDelete is false

### ISSUE THREAD

**Issue by kernel164** [VictoriaMetrics/operator#90]
e.g yaml used to created VMSingle.

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: test
spec:
  retentionPeriod: "1"
  removePvcAfterDelete: true
  serviceAccountName: "test"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```

if removePvcAfterDelete: true, it works perfectly via argocd. as the owner reference of pvc is set to vmsingle object. but pvc will be deleted when vmsingle is deleted in this case as per doc.

if removePvcAfterDelete: false, it doesn't work properly in argocd as the owner reference of pvc is not set to vmsingle object. so argo tries to delete the pvc immediately.

Is it possible to set owner reference of pvc to vmsingle object irrespective of setting removePvcAfterDelete: true/false ?

**Comment by f41gh7** [comment]
Hello. Operator objects deletion relies on kubernetes garbage-collection mechanism. That's why object reference is missing at PVC with `removePvcAfterDelete: false` -  to prevent  removing it after `VMSingle` object was deleted.  

 I found an issue at argocd https://github.com/argoproj/argo-cd/issues/1250 

 Seems like, it's your case, coz operators adds label `app.kubernetes.io/instance`

 Possible work-around: ```setting the application.instanceLabelKey value in the argocd-cm. We recommend that you use argocd.argoproj.io/instance```

 https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing

**Comment by amkartashov** [comment]
@f41gh7,

Labels from VMSingle propagate without change to PVC here: https://github.com/VictoriaMetrics/operator/blob/66f1f283e226e04317cc87dbb18cb59a655697f4/controllers/factory/vmsingle.go#L71

This should not happen, because this copies well-known labels like `app.kubernetes.io/managed-by`. This is the reason why ArgoCD thinks that PVC is argocd-managed resource created earlier and tries to delete it because it does not see it after manifests generation. Suggested workaround with `application.instanceLabelKey` won't work because of the same reason, label `argocd.argoproj.io/instance` will propagate further.

You should compare how it works with other operators/controllers. Simple case is Deployment which creates Replicaset which creates Pods:

```
$ kubectl get deploy monitoring-grafana -o jsonpath={.metadata.labels} | jq .
{
  "app.kubernetes.io/instance": "monitoring",
  "app.kubernetes.io/managed-by": "Helm",
  "app.kubernetes.io/name": "grafana",
  "app.kubernetes.io/version": "8.3.5",
  "argocd.argoproj.io/instance": "monitoring",
  "helm.sh/chart": "grafana-6.21.5"
}

$ kubectl get rs monitoring-grafana-679fcbf7bd -o jsonpath={.metadata.labels} | jq .
{
  "app.kubernetes.io/instance": "monitoring",
  "app.kubernetes.io/name": "grafana",
  "pod-template-hash": "679fcbf7bd"
}

$ kubectl get pod monitoring-grafana-679fcbf7bd-q6r7n -o jsonpath={.metadata.labels} | jq .
{
  "app.kubernetes.io/instance": "monitoring",
  "app.kubernetes.io/name": "grafana",
  "pod-template-hash": "679fcbf7bd"
}
```

As you can see, only `app.kubernetes.io/name` and `app.kubernetes.io/instance` propagate further.

**Comment by gecube** [comment]
@amkartashov Hi! You are not right. In your example `app.kubernetes.io/name` and `app.kubernetes.io/instance` are not propagated further, because I bet that they are defined in PodTemplate object of Deployment.

The simple experiment:

```
cat olo.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app.kubernetes.io/name: OLOLO
    app.kubernetes.io/instance: OLOLO-XXX
    app.kubernetes.io/version: 5.7.12
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: server
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
and apply this manifest.
You will get the next pod:

```
kubectl get pods nginx-deployment-66b6c48dd5-kz2m6 -oyaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-02-19T08:06:47Z"
  generateName: nginx-deployment-66b6c48dd5-
  labels:
    app: nginx
    pod-template-hash: 66b6c48dd5
  name: nginx-deployment-66b6c48dd5-kz2m6
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-deployment-66b6c48dd5
    uid: ce26af2e-433b-442d-9196-d0c09d4e9573
  resourceVersion: "286059335"
  uid: dbbfc0c7-e4c4-4df8-9054-d51648f76286
spec:
  containers:
  - image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-74xpp
      readOnly: true
...
```

As you may see only labels from pod template are present...
