### ISSUE TITLE
bearerTokenSecret missing on Conversion from ServiceMonitor to VMServiceScrape since 0.43.0

### ISSUE THREAD

**Issue by marrau** [VictoriaMetrics/operator#932]
When Upgrading from 0.42.4 to 0.43.1 any ServiceMonitor with a bearerTokenSecret set, gets Permission denied on scraping.

Example:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-service
spec:
  endpoints:
  - bearerTokenSecret:
      key: PRIVATE_API_KEY
      name: test-secret
    honorLabels: false
    interval: 15s
    path: /metrics
    scrapeTimeout: 15s
    targetPort: 80
  jobLabel: test
  selector:
    matchLabels:
      test: test
```

Result on 0.43.+ (shortened Output):
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: test-service
spec:
  attach_metadata: {}
  endpoints:
  - attach_metadata: {}
    interval: 15s
    path: /metrics
    scrapeTimeout: 15s
    targetPort: 80
  jobLabel: test
  namespaceSelector: {}
  selector:
    matchLabels:
      test: test
```

Result on 0.42.4 (shortened Output):
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: test-service
spec:
  endpoints:
  - attach_metadata: {}
    bearerTokenSecret:
      key: PRIVATE_API_KEY
      name: test-secret
    interval: 15s
    path: /metrics
    scrapeTimeout: 15s
    targetPort: 80
  jobLabel: test
  namespaceSelector: {}
  selector:
    matchLabels:
      test: test
```
