### ISSUE TITLE
Option to add maxScrapeSize to vmagent

### ISSUE THREAD

**Issue by pmitra43** [VictoriaMetrics/operator#96]
**Type**
Feature request

**Problem Statement**
For some services in a big cluster, `kube-state-metrics` for example, the scrape response size is much larger than the default promscrape.maxScrapeSize(16777216). Hence, VMAgent ignores the scrape with an error.

**Describe the solution you'd like**
Having a `maxScrapeSize` as a parameter for the VMAgentSpec API would be a good start to unblock this.

**Additional context**
Error log:
```
2020-10-28T18:51:37.921Z	error	VictoriaMetrics/lib/promscrape/scrapework.go:199	error when scraping "https://10.140.56.100:8443/metrics" from job "kube-state-metrics" with labels {endpoint="https-main", instance="10.140.56.100:8443", job="kube-state-metrics", namespace="monitoring", pod="kube-state-metrics-76b65c475d-j4ww6", prometheus="victoria-metrics/example-vmagent", service="kube-state-metrics"}: the response from "https://10.140.56.100:8443/metrics" exceeds -promscrape.maxScrapeSize=16777216; either reduce the response size for the target or increase -promscrape.maxScrapeSize
```

**Comment by f41gh7** [comment]
Hello, can you try to pass additional arg to `vmagent` with extraArg, something like that:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
spec:
....
  extraArgs:
    promscrape.maxScrapeSize: "56777216"
```
Does it solve an issue? 

 All vmagents args can be added with this option.
