### ISSUE TITLE
VMAgent: unable to configure additional volumes

### ISSUE THREAD

**Issue by GagarinX** [VictoriaMetrics/operator#97]
Hello.

I'm trying to setup a sidecar container in VMAgent and mount an additional volume inside it, using `spec.volumes` and `spec.containers.volumeMounts` like this:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
  volumes:
  - name: vm-shared
    emptyDir: {}
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  replicaCount: 1
  serviceAccountName: vmagent
  scrapeInterval: 60s
  remoteWrite:
    - url: "http://vmsingle-vmsingle-persisted.default.svc:8429/api/v1/write"
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /etc/vm-shared
      name: vm-shared
```

After applying this manifest, no deployment appears and there is an error in VM Operator logs:

```
{"level":"error","ts":1604322110.788751,"logger":"controllers.VMAgent","msg":"cannot create or update vmagent deploy","vmagent":"default/vmagent","error":"cannot create new vmagent deploy: Deployment.apps \"vmagent-vmagent\" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: \"vm-shared\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/VictoriaMetrics/operator/controllers.(*VMAgentReconciler).Reconcile\n\tgithub.com/VictoriaMetrics/operator/controllers/vmagent_controller.go:75\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

It looks like the operator ignores the volumes in `spec.volumes` part when creating a Deployment object.

Moving the volume list inside `spec.containers` also produces the same error, as well as moving `spec.volumeMounts` from `spec.containers` to `spec`. I'm able only to mount pre-set volumes inside my sidecar container (config, tls-assets and config-out).

VM Operator is version 0.3.0.
