### ISSUE TITLE
Deduplicate alerts when populating vmalert configmap

### ISSUE THREAD

**Issue by pmitra43** [VictoriaMetrics/operator#99]
**Type**
Feature request

**Description**
Operator creates alert configmaps for vmalert, from prometheusrules and vmrules. Since vmalert does not allow duplicated alerts([ref](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/vmalert.md#rules)), it would be good to have the operator to deduplicate the alerts from configmap.
Currently, vmalert fails to start if there is a duplicate alert.

**Expectation**
Rules with duplicate alerts should get deduplicated, so that vmalert can boot up.

**Comment by f41gh7** [comment]
@pmitra43  can you try to run operator from image: `victoriametrics/operator:adds-vmalert-rules-dedup`

 You need to add annotation with non-empty value to the `VMAlert` spec:
```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert-with-dedup
  annotations:
    operator.victoriametrics.com/vmalert-deduplicate-rules: "exist"
```
