### ISSUE TITLE
vmalert: add template variable to hold the "for:" alert rule value

### ISSUE THREAD

**Issue by rcowham** [VictoriaMetrics/operator#995]
It would be nice to be able to include 

```
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      summary: 'Instance {{ $labels.instance }} down'
```
E.g. allow something like this:
```
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than {{ $for }}.'
```

Thoughts?
